# -*- coding: utf-8 -*-
"""Build batch_011 translations: merge <<PAD>> markers with source padding runs."""
import json, re, sys, os

IN = "/Users/zlns/personal-www/pck-translate/.work/tr2/in/batch_011.jsonl"
OUT = "/Users/zlns/personal-www/pck-translate/.work/tr2/out/batch_011.jsonl"

T = {}
T[1] = "^c3dbffFeather Fan Sway^ffffff<<PAD>>^ffcc00Level<<PAD>>%d^ffffff<CRLF><CRLF>Strategy: Instant<<PAD>>Initial Cool-down: 20 sec<CRLF><CRLF>Soul Skill Type: Attack<CRLF>Summon the hero's soul merged into your body to unleash a soul attack on a single enemy<CRLF>within 7 meters in front of you.<CRLF><CRLF>^ffcc00Soul Skill Effect: ^ffffff<CRLF>1.<<PAD>>The attack deals one soul strike to the enemy; damage is doubled when cast in<CRLF>Awakened state;<CRLF>2.<<PAD>>When cast in Awakened state, has a %d%% chance to lower the enemy's Dodge by<CRLF>25 points and increase indirect damage taken by 6%%. This effect lasts at least 5 sec."
T[2] = "^c3dbffGraceful Dance<CRLF>^ffffffRequires at least 5 points invested in the \u201cCloud-Rain Dance \u00b7 Support\u201d Mastery.<CRLF><CRLF>While performing Cloud-Rain Dance, there is a chance for the \u201cGraceful Dance\u201d effect to appear,<CRLF>reducing the Stamina cost of the \u201cMurmuring Dance\u201d or \u201cTrickling Dance\u201d Move.<CRLF>Graceful Dance also shortens the preparation time of Trickling Dance."
T[3] = "^c3dbffSoaring Swan^ffffff<<PAD>>^ffcc00Level<<PAD>>%d^ffffff<CRLF><CRLF>Strategy: Instant<<PAD>>Cool-down: 120 sec<CRLF><CRLF>Soul Skill Type: Protection<CRLF>Summons the hero's soul merged into your body to cast the Swan state on yourself.<CRLF>Lasts at least 40 sec.<CRLF><CRLF>^ffcc00Soul Skill Effect: ^ffffff<CRLF>Crit + %d points.<CRLF>When cast in Awakened state, the Crit bonus increases to %d points."
T[4] = "^c3dbffWing Rend Slash^ffffff<CRLF><CRLF>Chariot Only<<PAD>>Cool-down: 12 sec<CRLF><CRLF>The chariot rears up, its side saw-blades spinning at full speed, dealing 144%% base Damage to targets within 6 meters ahead<CRLF>and 12000 extra Damage to chariots."
T[5] = "^c3dbffWing Rend Slash^ffffff<CRLF><CRLF>Chariot Only<<PAD>>Cool-down: 12 sec<CRLF><CRLF>The chariot rears up, its side saw-blades spinning at full speed, dealing 144%% base Damage to targets within 6 meters ahead<CRLF>and 12000 extra Damage to chariots.<CRLF><CRLF>^99ccffChariots deal only 10%% damage to characters"
T[6] = "^c3dbffWing Rend Slash^ffffff<CRLF><CRLF>Chariot Only<<PAD>>Cool-down: 12 sec<CRLF><CRLF>The chariot rears up, its side saw-blades spinning at full speed, dealing 144%% base Damage to targets within 6 meters ahead<CRLF>and 12000 extra Damage to chariots.<CRLF><CRLF>^99ccffChariots deal only 60%% damage to characters<CRLF>Chariots deal 200%% damage to arrow towers"
T[7] = "^c3dbffRadiant Light^ffffff<CRLF><CRLF>Skill Category: Valiant Line<CRLF>Skill Quality: I<CRLF>Requirement: Ranged<CRLF>Basic Move<CRLF><CRLF>Attack the enemy with swift, forceful strikes.<CRLF>Deals 85%% base Damage."
T[8] = "^c3dbffRadiant Light \u00b7 Force Attack<CRLF><CRLF>Skill Category: Valiant Line<CRLF>Skill Quality: IV<CRLF>Requirement: Ranged<CRLF><CRLF>^ffffffBoosts the Damage dealt by Radiant Light."
T[9] = "^c3dbffRadiant Light \u00b7 Rend<CRLF><CRLF>Skill Category: Valiant Line<CRLF>Skill Quality: IV<CRLF>Requirement: Ranged<CRLF><CRLF>^ffffffRadiant Light has a chance to send the enemy into the Rend state,<CRLF>draining HP continuously for 10 sec."
T[10] = "^c3dbffHale and Hearty^ffffff<CRLF><CRLF>Skill Category: Wisdom Line<CRLF>Skill Quality: V<CRLF>Requirement: None<CRLF>Support Move<CRLF>Cool-down: 5 min<CRLF><CRLF>Ignites blazing Battle Will, boosting your master's Max HP<CRLF>for 1 min.<CRLF>Also has a chance to Recover your master's HP<CRLF>for 15 sec."
T[11] = "^c3dbffGather Essence, Transform Qi<CRLF><CRLF>^ffffffWeapon: Battleaxe<<PAD>>No Cost<CRLF>Strategy: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>Gathers vital energy, using Stamina to neutralize half of the enemy's Damage.<CRLF>Lasts 10 sec; the effect ends after being hit 4 times."
T[12] = "^c3dbffSpirit Convergence^ffffff<CRLF><CRLF>Skill Quality: V<CRLF>Requirement: None<CRLF>Support Move<CRLF>Cool-down: 2 min<CRLF><CRLF>Condenses your own spirit energy to continuously Recover your master's HP."
T[13] = "^c3dbffFocused Spirit<CRLF><CRLF>^ffffffBoosts the Skill Damage of Taunt attacks.<CRLF><CRLF>^99ccffTaunt Skill Mastery. Only one can be learned."
T[14] = "^c3dbffThunder Gathering Stance<CRLF><CRLF>^ffffffWeapon: Mace<<PAD>>30 Battle Qi<CRLF>Martial Art: Instant<<PAD>>Cool-down 15 sec<CRLF><CRLF>Draws down heavenly lightning to strike the selected enemy,<CRLF>dealing 150%% base Damage<CRLF>and stopping the target's Normal Attacks for 4 sec."
T[15] = "^c3dbffThunder Gathering Stance \u00b7 Force<CRLF>^ffffffRequires at least 15 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffBoosts the Damage multiplier of Thunder Gathering Stance"
T[16] = "^c3dbffThunder Gathering Stance \u00b7 Burst<CRLF>^ffffffRequires at least 5 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffImproves the Crit Rate check when Thunder Gathering Stance attacks"
T[17] = "^c3dbffBackstab<CRLF><CRLF>^ffffffWeapon: Claws<<PAD>>5 Stamina<CRLF>Move: Instant<<PAD>>Cool-down 6 sec<CRLF><CRLF>Strike the target enemy from behind with a higher-damage Move.<CRLF>Generates 10 Battle Qi.<CRLF>Applies one stack of Assassination to yourself. Has a chance to wound the enemy.<CRLF>Deals 166%% base Damage; attacking from behind deals an extra<CRLF>60%% base Damage."
T[18] = "^c3dbffBackstab \u00b7 Assassination<CRLF>^ffffffRequires at least 5 points invested in the \u201cBackstab \u00b7 Force\u201d Mastery.<CRLF><CRLF>^ffffffWhile under the Ambush effect, Backstab attacks<CRLF>grant an additional stack of Assassination."
T[19] = "^c3dbffBackstab \u00b7 Force<CRLF>^ffffffRequires at least 5 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffBoosts the Damage dealt by Backstab."
T[20] = "^c3dbffBackstab \u00b7 Skill<CRLF>^ffffffRequires at least 5 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffBoosts the chance of Backstab causing a wound. At 5 stacks, there is a 20%% chance to cause<CRLF>a Mortal Wound effect; the wound lasts up to 30 sec."
T[21] = "^c3dbffConfusion in Fan-Shaped Area Behind"
T[22] = "^c3dbffRear Confusion<CRLF><CRLF>^ffffffWeapon: Ring Blade<<PAD>>5 Stamina<CRLF>Move: Instant<<PAD>>Cool-down 4 sec<CRLF><CRLF>Strike the enemy swiftly with the Ring Blade for 135%% base Damage,<CRLF>recovering 5 Battle Qi."
T[23] = "^c3dbffBack to the River^ffffff<<PAD>>^ffcc00Level<<PAD>>%d^ffffff<CRLF><CRLF>Strategy: Instant<<PAD>>Cool-down: 2 min<CRLF><CRLF>Soul Skill Type: Protection<CRLF>Summons the hero's soul merged into your body to strengthen your stats,<CRLF>greatly boosting Attack Power and Max HP,<CRLF>and increasing Crit Resistance by %d<CRLF><CRLF>^99ccffOnly takes effect when used in Awakened state"
T[24] = "^c3dbffAmbush<CRLF><CRLF>^ffffffWeapon: Claws<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>A signature dual-claw stance; certain Moves attack the enemy from behind,<CRLF>dealing greater Damage with a higher Crit Rate.<CRLF>Empowers your Moves for 30 sec. While active, attacking an enemy from behind with<CRLF>Fierce Thrust, Backstab, Double Thrust, or Throat-Piercing Claws \u00b7 Ambush<CRLF>deals an extra 20%% base Damage and adds a 20 Crit Rate check (not<CRLF>shown on the status panel), and increases your Crit Damage by 10%%."
T[25] = "^c3dbffAmbush \u00b7 Execution<CRLF>^ffffffRequires at least 25 points invested in Skill-type Mastery.<CRLF><CRLF>Increases your Crit Damage while the Ambush effect is active."
T[26] = "^c3dbffHu Pierce^ffffff<CRLF><CRLF>Weapon: Halberd<<PAD>>5 Battle Qi, 5 Stamina<CRLF>Move: Instant<<PAD>>Cool-down 6 sec<CRLF><CRLF>Sweep the enemy with the halberd's side Hu blade.<CRLF>The attack generates 15 Battle Qi and may cause a Cleave Wound.<CRLF>Deals 100%% base Damage.<CRLF>After learning the follow-ups:<CRLF>^c3dbffLift Strike^ffffff followed by ^c3dbffHu Pierce^ffffff grants the ^ff0000Battle Spirit^ffffff effect; the next attack gains 20 Battle Qi;<CRLF>^c3dbffReverse Strike^ffffff followed by ^c3dbffHu Pierce^ffffff grants the ^ff0000Focused Heart^ffffff effect; the next attack gains 15 Crit.<CRLF><CRLF>^c3dbffNote: Recommended for farming; serves as a Battle Qi builder."
T[27] = "^c3dbffHu Pierce \u00b7 Force<CRLF>^ffffffRequires at least 5 points invested in Force-type Mastery.<CRLF><CRLF>Boosts the base Damage of the Hu Pierce Move."
T[28] = "^c3dbffHu Pierce \u00b7 Skill^ffffff<CRLF>^ffffffRequires at least 5 points invested in Skill-type Mastery.<CRLF><CRLF>Hu Pierce has a chance to Sweep-Wound the target,<CRLF>rendering them unable to use Skills for the next 2 sec."
T[29] = "^c3dbffHu Pierce \u00b7 Confusion<CRLF>^ffffffRequires at least 5 points invested in the \u201cHu Pierce \u00b7 Force\u201d Mastery.<CRLF><CRLF>Hu Pierce has a chance to trigger the Confusion effect,<CRLF>reversing the target's movement direction for the next 3 sec."
T[30] = "^c3dbffLeap<CRLF><CRLF>^ffffffWeapon: Any<CRLF>^ffffffCost: 20 Stamina<CRLF>^ffffffRiding: Duration 1 sec<<PAD>>Cool-down 2 min<CRLF><CRLF>^ffffffMakes your mount leap forward,<CRLF>affecting the target area for up to 8 targets.<CRLF>^99ccffCan only be used in Mounted Combat.<CRLF><CRLF>^ffcc00Acquisition^ffffff<<PAD>>-<<PAD>>Granted by the Official Seal skill.<CRLF>^ffcc00Effect^ffffff<<PAD>>-<<PAD>>Dispels all Limiting states on yourself,<CRLF>leaping up to %d meters and dealing 80 Damage to enemies."
T[31] = "^c3dbffInjury \u00b7 Force<CRLF>^ffffffRequires at least 25 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffBoosts the chance of inflicting \u201cInjury\u201d. With the Mastery maxed, while in the Injury state,<CRLF>Wind-Thunder Rend's Cool-down is reduced by 0.5 sec per Injury stack, and<CRLF>Blooming Flowers<<PAD>>Cool-down is reduced by 1 sec per Injury stack<CRLF>(Injury points are only gained when using the corresponding Skills<<PAD>>after investing in<CRLF>the two Skill-type Masteries \u201cWind-Thunder Rend \u00b7 Injury\u201d and<CRLF>\u201cBlooming Flowers \u00b7 Injury\u201d)"
T[32] = "^c3dbffApex of Injury<CRLF>^ffffffRequires at least 30 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffWeapon: Mace<<PAD><CRLF>Martial Art: Instant<<PAD>>Cool-down 45 sec<CRLF><CRLF>Deals 100%% base Damage to the enemy per Injury point<CRLF>(Injury points are only gained when using the corresponding Skills after investing in the two Skill-type Masteries<CRLF>\u201cWind-Thunder Rend \u00b7 Injury\u201d and \u201cBlooming Flowers \u00b7 Injury\u201d)"
T[33] = "^c3dbffPrison of Injury<CRLF>^ffffffRequires at least 30 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffWeapon: Mace<<PAD><CRLF>Martial Art: Instant<<PAD>>Cool-down 45 sec<CRLF><CRLF>Binds the enemy to yourself, Immobilizing them for 4 sec; the target can neither Attack nor move.<CRLF>Each second, drains the target's Stamina equal to 5 * Injury points,<CRLF>and HP equal to 15%% * Injury points * your Attack Power,<CRLF>(Injury points are only gained when using the corresponding Skills after investing in the two Skill-type Masteries<CRLF>\u201cWind-Thunder Rend \u00b7 Injury\u201d and \u201cBlooming Flowers \u00b7 Injury\u201d)"
T[34] = "^c3dbffFatal Spin<CRLF>^ffffffRequires at least 2 points invested in the \u201cFurious Spin\u201d Mastery.<CRLF><CRLF>^ffffffBoosts the effectiveness of all Spinning Blade Throw Moves."
T[35] = "^c3dbffDance Intent<CRLF><CRLF>^ffffffAttribute: Passive<CRLF><CRLF>A power grasped after fully comprehending the subtleties of Dance;<CRLF>even without a Dance Fan in hand, you can still express the ultimate meaning of Dance."
T[36] = "^c3dbffDance Soul<CRLF><CRLF>^ffffffAttribute: Passive<CRLF><CRLF>A power grasped after fully comprehending the subtleties of Dance;<CRLF>even without a Dance Fan in hand, you can still express the ultimate meaning of Dance."
T[37] = "^c3dbffPetals on the Stream<CRLF><CRLF>^ffffffUsing Empty Blade has a chance to cause Freeze Immobilize.<CRLF><CRLF>^99ccffTaunt Skill Mastery. Only one can be learned."
T[38] = "^c3dbffAzure Cloud, Merciful Mist<CRLF><CRLF>^ffffffWeapon: Any<<PAD>>10 Stamina<CRLF>Combat: Instant<<PAD>>Cool-down 10 min<CRLF><CRLF>Sacrifice Dodge to gain increased Max HP and Recover HP.<CRLF>Increases Max HP by 10%% and Recovers HP equal to 10%% of your Max HP.<CRLF>The effect lasts 20 sec; when it ends, the Recovered HP is deducted."
T[39] = "^c3dbffAzure Inferno^ffffff<CRLF><CRLF>Skill Category: Hot-Blooded Line<CRLF>Skill Quality: II<CRLF>Requirement: Melee<CRLF>Advanced Move<CRLF><CRLF>Attack the 3 enemies in front of you<CRLF>dealing 82%% base Damage."
T[40] = "^c3dbffSky Wild Dance<CRLF>^ffffffRequires at least 20 points invested in Dance-type Mastery.<CRLF><CRLF>^ffffffWeapon: Hammer<<PAD>>20 Battle Qi<CRLF>Martial Art: Instant<<PAD>>Cool-down 20 sec<CRLF><CRLF>Where the mind leads, the heavy twin hammers become part of your body, swinging freely.<CRLF>Attacks have a high chance to briefly hold the enemy in place, unable to move,<CRLF>dealing damage three times in a row.<CRLF><CRLF>^c3dbffNote: Can only be cast after earning Combat Art points. ^ffffff<CRLF>The Move releases all accumulated Force Attack or Wild Dance points:<CRLF>each Force Attack point adds 26%% base Damage to the Move;<CRLF>each Wild Dance point extends the enemy's Immobilize duration by 0.5 sec."
T[41] = "^c3dbffSky Wild Dance \u00b7 Lock<CRLF>^ffffffRequires at least 5 points invested in the \u201cSky Wild Dance\u201d Mastery.<CRLF><CRLF>^ffffffBoosts the chance of \u201cSky Wild Dance\u201d Immobilizing enemies."
T[42] = "^c3dbffAzure Thunderfall^ffffff<CRLF><CRLF>Skill Category: Wisdom Line<CRLF>Skill Quality: II<CRLF>Requirement: Melee<CRLF>Advanced Move<CRLF><CRLF>Attack the enemy in two ferocious, powerful stages.<CRLF>The first stage deals 191%% base Damage,<CRLF>the second stage deals 85%% base Damage."
T[43] = "^c3dbffAzure Thunderfall \u00b7 Force Attack<CRLF><CRLF>Skill Category: Wisdom Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffBoosts the Damage dealt by Azure Thunderfall."
T[44] = "^c3dbffAzure Thunderfall \u00b7 Flying General<CRLF><CRLF>Skill Category: Wisdom Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffAzure Thunderfall has a chance to deal Ignore-Defense Damage equal to<CRLF>30%% of your Guard's Attack Power."
T[45] = "^c3dbffSelf-Inflicted Wound<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Hero Lv.50<CRLF>^ffffffAncestral Origin Restriction: Jingzhou<CRLF><CRLF>The ruse of the flesh wound won Shu-Wu the war against Cao;<CRLF>when attacked, there is a 5%% chance to reflect the Wounded state<CRLF>so the target cannot Recover HP.<CRLF><CRLF>^99ccffBased on Huang Gai.<CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[46] = "^c3dbffArea Entry Count<CRLF><CRLF>^ffffffWeapon: Ring Blade<<PAD>>15 Battle Qi<CRLF>Move: Instant Strike<<PAD>>Cool-down 15 sec<CRLF><CRLF><CRLF>Move toward the selected target, dealing 189%% base Damage to up to three enemies<CRLF>along the path and slowing them by 1 m/sec,<CRLF>while also increasing your own Movement Speed."
T[47] = "^c3dbffBandit Suppression<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Hero Lv.36<CRLF>^ffffffAncestral Origin Restriction: Youzhou<CRLF><CRLF>The Wu Bandit-Suppression General who aided Sun Quan and achieved unparalleled merit;<CRLF>when attacked, there is a 5%% chance to gain the Bandit Suppression state,<CRLF>boosting Crit and Crit Damage. Triggers once.<CRLF><CRLF>^99ccffBased on Cheng Pu.<CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[48] = "^c3dbffHerbal Aura<CRLF><CRLF>^ffffffSpecial Move: Instant<<PAD>>Cool-down 10 min<CRLF><CRLF>^ffffffFor 15 sec, whenever you take any attack,<CRLF>you Recover HP. Triggers up to 20 times.<CRLF>Beyond Hero level, the Recovery effect increases by 10%% per level."
T[49] = "^c3dbffLotus-Rinsed Robe<CRLF><CRLF>^ffffff\u201cSummon Wind and Rain\u201d causes the target's Indirect Resistance to be further Reduced.<CRLF><CRLF>^99ccffFinisher Attack Mastery. Only one can be learned."
T[50] = "^c3dbffFalling Cherry Blossoms<CRLF><CRLF>^ffffffDance this dance like a fairy descending to the mortal realm,<CRLF>one dance beneath the umbrella to topple a city, blossoms falling and blooming as the years drift by."
T[51] = "^c3dbffFalling Tassel Shot<CRLF><CRLF>^ffffffWeapon: Bow<<PAD>>10 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 8 sec<CRLF><CRLF>The Move echoes the tale of Huang Zhong's duel with Guan Yu at Changsha.<CRLF>A deadly arrow flies straight at the enemy's face.<CRLF>Can be fired directly while moving; has a chance to wound the target.<CRLF>Deals 120%% base Damage and generates 10 Battle Qi.<CRLF>When the Skill Crits, it can Immobilize the target for 2 sec."
T[52] = "^c3dbffFalling Tassel Shot \u00b7 Force<CRLF>^ffffffRequires at least 20 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffBoosts the Damage dealt by Falling Tassel Shot."
T[53] = "^c3dbffFalling Tassel Shot \u00b7 Skill<CRLF>^ffffffRequires at least 15 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffBoosts the chance of Falling Tassel Shot causing an arrow wound."
T[54] = "^c3dbffFalling Tassel Shot \u00b7 Crit<CRLF>^ffffffRequires at least 3 points invested in Falling Tassel Shot \u00b7 Skill.<CRLF><CRLF>^ffffffBoosts the chance of Falling Tassel Shot Critting."
T[55] = "^c3dbffFalling Wild Goose Sweep<CRLF><CRLF>^ffffffWeapon: Whip<<PAD>>5 Stamina<<PAD>>10 Battle Qi<CRLF>Move: Instant<<PAD>>Cool-down 8 sec<CRLF><CRLF>A combo Move used after Autumn Wind Sweep.<CRLF>Sweep horizontally with the whip, hitting up to 5 enemies in front of you<CRLF>for 111%% base Damage,<CRLF>and slowing them by 1 m/sec for 3 sec.<CRLF><CRLF>^c3dbffNote: Used while in the National Beauty state, it can combo into Face Sweep;<CRLF>^c3dbffUsed while in the Heavenly Fragrance state, it can combo into Soul-Seizing Sweep."
T[56] = "^c3dbffFalling Wild Goose Sweep<CRLF><CRLF>^ffffffWeapon: Whip<<PAD>>5 Stamina<<PAD>>10 Battle Qi<CRLF>Move: Instant<<PAD>>Cool-down 9 sec<CRLF><CRLF>Strike the enemy swiftly with the whip for 74%% base Damage."
T[57] = "^c3dbffFalling Wild Goose Sweep \u00b7 Shadow<CRLF>^ffffffRequires at least 5 points invested in Shadow-type Mastery.<CRLF><CRLF>^ffffffRaises the target cap of Falling Wild Goose Sweep,<CRLF>with a chance to Reduce the target's Attack Speed by 20%%."
T[58] = "^c3dbffFalling Thunder Technique<CRLF><CRLF>^ffffffWeapon: Staff<<PAD>>10 Battle Qi, 20 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 12 sec<CRLF><CRLF>An instant Falling Thunder strike against a nearby target.<CRLF>Deals 100%% base Damage.<CRLF>Also has a 35%% chance to put the enemy into the Electric Paralyze state.<CRLF>^99ccffElectric Paralyze slows the target by 3.5 m/sec,<CRLF>^99ccffand the effect gradually fades over 5 sec.<CRLF>Has a chance to cause a Splash effect on the target."
T[59] = "^c3dbffFalling Thunder Technique \u00b7 Curse<CRLF>^ffffffRequires at least 10 points invested in Curse-type Mastery.<CRLF><CRLF>^ffffffReduces Falling Thunder Technique's Cool-down.<CRLF>Boosts the Skill's Crit Rate under Thunder Armor.<CRLF>At 5 stacks, when Falling Thunder Technique fails to Electric Paralyze the enemy,<CRLF>you have a 90%% chance to gain the Heavenly Thunder Curse state.<CRLF>Boosts the chance of Falling Thunder Technique dealing Splash Damage."
T[60] = "^c3dbffFalling Thunder Technique \u00b7 Curse<CRLF>^ffffffRequires at least 15 points invested in Curse-type Mastery.<CRLF><CRLF>^ffffffBoosts Falling Thunder Technique's Crit Rate."
T[61] = "^c3dbffFalling Thunder Technique \u00b7 Heavenly Thunder<CRLF>^ffffffRequires at least 5 points invested in Falling Thunder Technique \u00b7 Tactic.<CRLF><CRLF>^ffffffWhen Falling Thunder Technique fails to Electric Paralyze the enemy,<CRLF>you have a chance to gain the Heavenly Thunder Curse state.<CRLF>^99ccffWhile in the Heavenly Thunder Curse state, using Swift Lightning shortens its<CRLF>preparation time by 1 sec and always causes Electric Paralyze.<CRLF>It can also apply a 3-sec Move Break to the enemy."
T[62] = "^c3dbffFalling Wind Shift<CRLF><CRLF>^ffffffWeapon: Shield<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down Time: 25 sec<<PAD><CRLF><CRLF>Attack a single target,<CRLF>dealing 195%% base Damage.<CRLF>After use, randomly allows one of Shadow Rend Strike, Cloud-Break Slash, or Moon-Seal Strike,<CRLF>clearing that Skill's Cool-down.<CRLF>Recovers 10 Battle Qi."
T[63] = "^c3dbffFalling Wind Shift \u00b7 Fierce<CRLF>^ffffffRequires at least 25 points invested in Fierce-type Mastery.<CRLF><CRLF>^ffffffReduces Falling Wind Shift's Cool-down."
T[64] = "^c3dbffCharge<CRLF><CRLF>^ffffffWeapon: Any<CRLF>^ffffffCost: 10 Stamina<CRLF>^ffffffRiding: Duration 3 sec<<PAD>>Cool-down 6 sec<CRLF><CRLF>^ffffffGather strength into your wrists to make your next attack more threatening.<CRLF>^99ccffCan only be used in Mounted Combat."
T[65] = "^c3dbffStore Power<CRLF><CRLF>^ffffffWeapon: Saber<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down 8 sec<CRLF><CRLF>Spend time gathering power to strengthen Attack Power.<CRLF>A channeled Move; after use you enter a charging motion,<CRLF>and using other attack Moves during the motion grants increased Attack Power.<CRLF>Certain special Moves gain special enhancements as well; see each Move's description for details."
T[66] = "^c3dbffStore Rage<CRLF><CRLF>Skill Quality: V<CRLF>Requirement: None<CRLF><CRLF>^ffffffPermanently increases your Guard's Crit Damage."
T[67] = "^c3dbffStore Rage<CRLF>^ffffffRequires at least 2 points invested in \u201cEnhanced Store Power\u201d.<CRLF><CRLF>^ffffffWhile using the Store Power Skill, you gain Battle Qi per second,<CRLF>and increase the knockdown duration caused by Crescent Moon Slash while in the Store Power state."
T[68] = "^c3dbffPremeditated Stratagem<CRLF><CRLF>^ffffffBoosts the Skill Damage of Dragging Saber Stance, Skyward Thrust, \u201cSummon Wind and Rain\u201d,<CRLF>and Chain of Divine Arrows.<CRLF><CRLF>^99ccffFinisher Attack Mastery. Only one can be learned."
T[69] = "^c3dbffMoon Veil^ffffff<<PAD>>^ffcc00Level<<PAD>>%d^ffffff<CRLF><CRLF>Strategy: Instant<<PAD>>Cool-down: 2 min<CRLF><CRLF>Soul Skill Type: Protection<CRLF>Summons the hero's soul merged into your body to strengthen your stats,<CRLF>greatly boosting Attack Power and Max HP,<CRLF>and increasing Crit Bonus Damage by %d<CRLF><CRLF>^99ccffOnly takes effect when used in Awakened state"
T[70] = "^c3dbffBottled Rage<CRLF><CRLF>^ffffffWeapon: Axe<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down 1 min<CRLF><CRLF>Bottle up rage to burst out at a more opportune moment.<CRLF>Self effect; takes effect after 3 sec, instantly granting 50 Battle Qi.<CRLF>Then deducts 50 after another 6 sec."
T[71] = "^c3dbffBottled Rage<CRLF><CRLF>^ffffffWeapon: Axe<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>Bottle up rage to burst out at a more opportune moment.<CRLF>Self effect; takes effect after 6 sec, instantly granting 50 Battle Qi.<CRLF>Then deducts 50 after another 3 sec, down to a minimum of 0."
T[72] = "^c3dbffFragile Fate<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Hero Lv.36<CRLF>^ffffffAncestral Origin Restriction: Jizhou<CRLF><CRLF>A peerless beauty who fell from favor in the harem, fated as fragile as paper;<CRLF>when attacked, there is a 5%% chance to gain the Fragile Fate state.<CRLF>When HP falls below 30%%, a large amount of HP can be Recovered;<CRLF>the state lasts 5 sec.<CRLF><CRLF>^99ccffBased on Lady Zhen.<CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[73] = "^c3dbffHidden Strike<CRLF><CRLF>^ffffffAssault Strike has a chance to Stun the target for 3 sec.<CRLF><CRLF>^99ccffFinisher Attack Mastery. Only one can be learned."
T[74] = "^c3dbffHidden Edge<CRLF><CRLF>Skill Quality: V<CRLF>Requirement: None<CRLF><CRLF>^ffffffGreat skill needs no ornament; the heaviest sword has no edge.<CRLF>Permanently increases your Attack Power."
T[75] = "^c3dbffTiger Among the Flock<CRLF><CRLF>^ffffffWeapon: Shield<<PAD>>60 Battle Qi<<PAD>>5 Stamina<CRLF>Finisher: Charge 2 sec<<PAD>>Cool-down 2 min<CRLF><CRLF>A tiger among the flock; burns part of your Current HP,<CRLF>dealing 300%% base Damage to multiple enemies in an area around you,<CRLF>applying a Concussive Wound to all enemies hit,<CRLF>with a 25%% chance to Stun them."
T[76] = "^c3dbffTiger Guard<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Hero Lv.50<CRLF>^ffffffAncestral Origin Restriction: Yuzhou<CRLF><CRLF>Elite troops of Wei's \u201cPalace Guard\u201d, led by Xu Chu,<CRLF>charging the fray wherever they went.<CRLF>When you use a Block Skill and are attacked,<CRLF>there is a chance to Stun the attacker for 3 sec.<CRLF><CRLF>^99ccffBased on the Palace Guard.<CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[77] = "^c3dbffTiger's Roar^ffffff<CRLF><<PAD>>Cool-down Time: 180 sec<CRLF><CRLF>^a800ffSummons two powerful beasts to fight alongside you."
T[78] = "^c3dbffTiger's Roar, Burning Cloud<CRLF>^ffffffAttribute: Passive<CRLF><CRLF>Power granted by your lineage greatly boosts the effectiveness of Ultimate Skills.<CRLF>Offensive Ultimate Skills apply the \u201cTerror-Struck\u201d state, greatly weakening the enemy's combat ability.<CRLF>\u201cTerror-Struck\u201d has no effect on Ultimate Skills of the Staff, Fan, Dance, and Trident classes."
T[79] = "^c3dbffTiger Madman<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Hero Lv.36<CRLF>^ffffffAncestral Origin Restriction: Yuzhou<CRLF><CRLF>Cao Cao's personal bodyguard, peerlessly brave, known as the \u201cTiger Madman\u201d;<CRLF>when attacked, there is a 5%% chance to gain the Tiger Madman state.<CRLF>The lower your remaining HP, the greater the Attack Power boost.<CRLF>Triggers once.<CRLF><CRLF>^99ccffBased on Xu Chu.<CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[80] = "^c3dbffPhantom Kill Stance<CRLF><CRLF>^ffffffWeapon: Battleaxe<<PAD>>10 Battle Qi<<PAD>>5 Stamina<CRLF>Mastery: Instant<<PAD>>Cool-down 8 sec<CRLF><CRLF>Whirl your weapon into a storm, attacking up to 5 enemies around you.<CRLF>Deals 100%% base Damage and Immobilizes enemies for 3 sec."
T[81] = "^c3dbffPhantom Kill Stance \u00b7 Wound<CRLF>^ffffffRequires at least 15 points invested in Wound-type Mastery.<CRLF><CRLF>^ffffffPhantom Kill Stance can Reduce the healing the enemy receives, lasting 3 sec."
T[82] = "^c3dbffPhantom Kill Stance \u00b7 Rage<CRLF>^ffffffRequires at least 15 points invested in Rage-type Mastery.<CRLF><CRLF>^ffffffBoosts the Damage dealt by Phantom Kill Stance."
T[83] = "^c3dbffVoid Slash^ffffff<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: II<CRLF>Requirement: Melee<CRLF>Advanced Move<CRLF><CRLF>Attack the target, dealing 155%% base Damage."
T[84] = "^c3dbffVoid Slash \u00b7 Seal<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffVoid Slash has a chance to send the enemy into the Seal-Bound state,<CRLF>Reducing Seal Resistance by 10 points and putting them into Starvation, unable to use potions,<CRLF>while continuously draining HP. The effect scales with your Guard's Stratagem value and lasts 10 sec."
T[85] = "^c3dbffVoid Slash \u00b7 Force Attack<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffBoosts the Damage dealt by Void Slash."
T[86] = "^c3dbffSun Erosion^ffffff<CRLF><CRLF>Skill Category: Valiant Line<CRLF>Skill Quality: I<CRLF>Requirement: Ranged<CRLF>Basic Move<CRLF><CRLF>Attack the enemy with swift, forceful strikes.<CRLF>Deals 105%% base Damage."
T[87] = "^c3dbffSun Erosion \u00b7 Ferocity<CRLF><CRLF>Skill Category: Valiant Line<CRLF>Skill Quality: IV<CRLF>Requirement: Ranged<CRLF><CRLF>^ffffffSun Erosion has a chance to increase your Attack Power;<CRLF>the state lasts 10 sec."
T[88] = "^c3dbffSun Erosion \u00b7 Force Attack<CRLF><CRLF>Skill Category: Valiant Line<CRLF>Skill Quality: IV<CRLF>Requirement: Ranged<CRLF><CRLF>^ffffffBoosts the Damage dealt by Sun Erosion."
T[89] = "^c3dbffSerpent Shadow \u00b7 Legion<CRLF><CRLF>^ffffffWeapon: Whip<<PAD>>20 Battle Qi<<PAD>>10 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>Whip the long lash, dealing heavy Damage to up to 5 enemies within an 8-meter radius in front of you<CRLF>and Immobilizing them for 2 sec.<CRLF>After learning the corresponding \u201cRage\u201d or \u201cBreak\u201d Skill, the<CRLF>Move deals double Damage.<CRLF><CRLF>^c3dbffNote: Using this Skill after Serpent Shadow \u00b7 Rage can Reduce the target's<CRLF>Indirect Damage Resistance;<CRLF>using this Skill after Serpent Shadow \u00b7 Legion can extend the time the target<CRLF>is Immobilized."
T[90] = "^c3dbffSerpent Shadow \u00b7 Rage<CRLF><CRLF>^ffffffWeapon: Whip<<PAD>>15 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>Bless yourself, increasing your Stun Resistance rate<CRLF>or Crit Resistance for 10 sec.<CRLF><CRLF>^c3dbffNote: Using this Skill after Serpent Shadow \u00b7 Break can enhance<CRLF>your Resistance boost;<CRLF>using this Skill after Serpent Shadow \u00b7 Legion grants both stat boosts<CRLF>at once, with slightly reduced effect."
T[91] = "^c3dbffSerpent Shadow \u00b7 Break<CRLF><CRLF>^ffffffWeapon: Whip<<PAD>>15 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>Weaken up to 5 enemies within 8 meters around you,<CRLF>so that for 6 sec every time they hit a target<CRLF>their own Attack Power is Reduced,<CRLF>stacking up to 5 times.<CRLF><CRLF>^c3dbffNote: Using this Skill after Serpent Shadow \u00b7 Rage can further Reduce the target's<CRLF>Attack Power;<CRLF>using this Skill after Serpent Shadow \u00b7 Legion gives the target a 50%% chance when hitting<CRLF>to additionally Reduce their own Attack Power."
T[92] = "^c3dbffSerpent Spear Formation<CRLF><CRLF>^ffffffWield this spear and tiger and serpent follow, howling across the heavens."
T[93] = "^c3dbffBarbarian King<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Hero Lv.36<CRLF>^ffffffAncestral Origin Restriction: Yizhou<CRLF><CRLF>A chieftain of the southern tribes; Kongming captured and released him seven times until he submitted.<CRLF>When attacked, there is a 5%% chance to reflect the Barbarian King state,<CRLF>increasing the Direct Damage taken. The state lasts 4 sec.<CRLF><CRLF>^99ccffBased on Meng Huo.<CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[94] = "^c3dbffPrimordial Thunder<CRLF><CRLF>^ffffffWeapon: Saber, Spear, Halberd, Staff, Battleaxe, Trident, Shield<<PAD>>100 Stamina<<PAD><CRLF>Move: Instant<<PAD>>Cool-down 120 sec<CRLF><CRLF>Summon the primordial thunder of the nine heavens<CRLF>to strike a designated location continuously,<CRLF>dealing 50%% base Damage every 0.5 sec"
T[95] = "^c3dbffPrimordial Thunder<CRLF><CRLF>^ffffffWeapon: Hooksword<<PAD>>50 Stamina<<PAD><CRLF>Move: Instant<<PAD>>Cool-down 60 sec<CRLF><CRLF>Summon the primordial thunder of the nine heavens<CRLF>to strike a designated location continuously,<CRLF>dealing one hit of damage every 0.5 sec"
T[96] = "^c3dbffButterfly Fan Dance<CRLF><CRLF>^ffffffWeapon: Dance Fan<<PAD>>20 Stamina<CRLF>Strategy: 0.5 sec execution<<PAD>>Cool-down 4 sec<CRLF><CRLF>Hurl the Dance Fan to strike the enemy first.<CRLF>Generates 10 Battle Qi.<CRLF>Concusses the enemy; must be used outside of combat.<CRLF>120%% base Attack.<CRLF>After the Move hits, boosts Attack Speed by 15%% for 15 sec,<CRLF>ending when any attack Move is used.<CRLF><CRLF>^c3dbffNote: Recommended for farming; serves as an opener."
T[97] = "^c3dbffButterfly Fan Dance \u00b7 Wild Dance<CRLF><CRLF>^ffffffEnhances the Attack Speed boost caused by Butterfly Fan Dance."
T[98] = "^c3dbffButterfly Dance^ffffff<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: I<CRLF>Requirement: Ranged<CRLF>Basic Move<CRLF><CRLF>Attack the enemy with swift, forceful strikes.<CRLF>Deals 122%% base Damage."
T[99] = "^c3dbffButterfly Dance \u00b7 Force Attack<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Ranged<CRLF><CRLF>^ffffffBoosts the Damage dealt by Butterfly Dance."
T[100] = "^c3dbffButterfly Dance \u00b7 Frailty<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffButterfly Dance has a chance to send the enemy into the Frailty state,<CRLF>Reducing Frailty Resistance by 10 points and randomly entering the Blunted Weapon, Armor Break, or Sluggish state.<CRLF>The effect scales with your Guard's Stratagem value and lasts 10 sec."
T[101] = "^c3dbffBlood Frenzy^ffffff<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: III<CRLF>Requirement: Melee<CRLF>High-Tier Move<CRLF><CRLF>Swing your weapon to attack 5 enemies around you<CRLF>dealing 88%% base Damage."
T[102] = "^c3dbffThirst for Blood<CRLF><CRLF>^ffffffWeapon: Hooksword<<PAD>>15 Battle Qi<<PAD>>10 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 15 sec<CRLF><CRLF>A highly toxic attack craving a gush of blood, instantly dealing 50%% base Damage.<CRLF>Hatred points deal extra damage over time to the target.<CRLF>Combat Tattoo: 50%% chance to Reduce the target's Direct Resistance by 10 points, lasting 5 sec<CRLF>Rock Tattoo: adds 6 sec to the damage-over-time duration<CRLF>Gale Tattoo: Reduces the target's Movement Speed by 1.5 m/sec and increases yours by 2 m/sec<CRLF>Boiling Blood Tattoo: the target loses 2.5%% of its Current HP every 3 sec, lasting 9 sec"
T[103] = "^c3dbffThirst for Blood \u00b7 Hatred<CRLF>^ffffffRequires at least 15 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffHatred value boosts Thirst for Blood's effects under each Tattoo"
T[104] = "^c3dbffThirst for Blood \u00b7 Gale<CRLF>^ffffffRequires at least 10 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffUnder the \u201cGale Tattoo\u201d, Thirst for Blood deals Ignore-Defense Damage to the target,<CRLF>scaled to the target's Movement Speed"
T[105] = "^c3dbffThirst for Blood \u00b7 Boiling Blood<CRLF>^ffffffRequires at least 10 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffUnder the \u201cBoiling Blood Tattoo\u201d, using \u201cThirst for Blood\u201d to damage the target also<CRLF>Recovers some HP for yourself"
T[106] = "^c3dbffBlood Slaughter^ffffff<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: I<CRLF>Requirement: Melee<CRLF>Basic Move<CRLF><CRLF>Attack the enemy with swift, forceful strikes.<CRLF>Deals 116%% base Damage."
T[107] = "^c3dbffBlood Slaughter \u00b7 Force Attack<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffBoosts the Damage dealt by Blood Slaughter."
T[108] = "^c3dbffBlood Slaughter \u00b7 Frailty<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffBlood Slaughter has a chance to send the enemy into the Frailty state,<CRLF>Reducing Frailty Resistance by 10 points and randomly entering the Blunted Weapon, Armor Break, or Sluggish state.<CRLF>The effect scales with your Guard's Stratagem value and lasts 10 sec."
T[109] = "^c3dbffBlood Courage<CRLF><CRLF>^ffffffWeapon: Trident<<PAD>>20 Stamina<CRLF>Strategy: Instant<<PAD>>Duration: 10 min<CRLF><CRLF>Hot-blooded energy surges within your weapon,<CRLF>letting each attack Recover a small amount of HP for yourself,<CRLF>boosting your sustained combat ability.<CRLF>Cannot coexist with the Wind Array effect.<CRLF><CRLF>^c3dbffNote: Recommended for self combat buffs."
T[110] = "^c3dbffBlood Rage<CRLF><CRLF>^ffffffAttribute: Passive<CRLF>^ffffffLevel Requirement: Lv.20<CRLF><CRLF>A blessing from your ancestral homeland;<CRLF>Max HP increased.<CRLF><CRLF>^99ccffRequires the corresponding Skill Book to learn."
T[111] = "^c3dbffBlood Rage^ffffff<CRLF><CRLF>Skill Quality: V<CRLF>Requirement: None<CRLF>Support Move<CRLF>Cool-down: 5 min<CRLF><CRLF>Hot blood that craves battle flows through your veins,<CRLF>increasing your Attack Power for 1 min."
T[112] = "^c3dbffBlooded Wild Dance<CRLF>^ffffffRequires at least 5 points invested in the \u201cLifting the Heavy as Light\u201d Mastery.<CRLF><CRLF>^ffffffAfter activating a Combat Art, increases the chance of gaining Combat Art points from attacks."
T[113] = "^c3dbffBlood Battle Against a Thousand^ffffff<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: II<CRLF>Requirement: Melee<CRLF>Advanced Move<CRLF><CRLF>Attack the 3 enemies in front of you<CRLF>dealing 78%% base Damage."
T[114] = "^c3dbffBoiling Blood Mark<CRLF>^ffffffRequires at least 30 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffUsing a Skill under the Boiling Blood Tattoo places the Boiling Blood Mark on the target.<CRLF>Each stack Reduces the target's healing received by 10%%, lasting 8 sec, stacking up to 3 times.<CRLF>At 3 stacks, using the corresponding Skill (Lightning-Calling Hook, Hundred Poisons Marrow-Piercing, Wu Hong Hu Ji,<CRLF>Thirst for Blood, Eight-Piece Cut) sets the target's HP Recovery rate to zero for 5 sec,<CRLF>with a 40%% chance to send the target into the \u201cWeak Battle\u201d state for 5 sec,<CRLF>causing the target to take Ignore-Defense Damage whenever healed."
T[115] = "^c3dbffBoiling Blood Tattoo<CRLF><CRLF>^ffffffWeapon: Hooksword<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down 5 sec<CRLF><CRLF>Use the Boiling Blood Tattoo to awaken dormant power,<CRLF>increasing HP Recovery rate for 1 min.<CRLF>In combat, half of the HP Recovery boost applies.<CRLF>While the Boiling Blood Tattoo is active, other Skills gain additional effects"
T[116] = "^c3dbffBoiling Blood Tattoo \u00b7 Skill<CRLF><CRLF>^ffffffBoosts the HP Recovery bonus of the Boiling Blood Tattoo.<CRLF>At 3 Mastery levels, gain the \u201cBoiling Blood Imprint\u201d,<CRLF>increasing Max HP by 6%%"
T[117] = "^c3dbffSupply Provisions^ffffff<CRLF><CRLF>Transformation Only<<PAD>>Cool-down Time: 1 sec<CRLF><CRLF>After use, the granary is restocked with large amounts of provisions."
T[118] = "^c3dbffHeart-Striking Art^ffffff<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: II<CRLF>Requirement: Melee<CRLF>Advanced Move<CRLF><CRLF>Attack the target, dealing 194%% base Damage."
T[119] = "^c3dbffHeart-Striking Art \u00b7 Force Attack<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffBoosts the Damage dealt by Heart-Striking Art."
T[120] = "^c3dbffHeart-Striking Art \u00b7 Hinder<CRLF><CRLF>Skill Category: Agility Line<CRLF>Skill Quality: IV<CRLF>Requirement: Melee<CRLF><CRLF>^ffffffHeart-Striking Art has a chance to send the enemy into the Hindered state,<CRLF>Reducing Restriction Resistance by 10 points and lowering Movement Speed.<CRLF>The effect scales with your Guard's Stratagem value and lasts 10 sec."
T[121] = "^c3dbffWind Assault Shield<CRLF>^ffffffRequires at least 59 points invested in Tactic-type Mastery.<CRLF><CRLF>^ffffffWeapon: Fan<CRLF>Strategy: Instant<<PAD>>Cool-down 120 sec<CRLF><CRLF>Condense raging winds around yourself,<CRLF>immediately applying the Wind Assault state to surrounding targets.<CRLF>Meanwhile, Absorbs the damage you take for 6 sec.<CRLF>Also dispels and renders you Immune to most Limiting states for 4 sec."
T[122] = "^c3dbffCloud Rend Strike<CRLF><CRLF>^ffffffWeapon: Shield<<PAD>>15 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 3 sec<CRLF><CRLF>Hold the shield in your left hand and slam it down hard,<CRLF>damaging up to 5 enemies within 5 meters around you.<CRLF>Deals 121%% base Damage.<CRLF>Recovers 10 Battle Qi.<CRLF><CRLF>^c3dbffNote: Recommended for farming; serves as a Battle Qi builder."
T[123] = "^c3dbffCloud Rend Strike \u00b7 Fortitude<CRLF><CRLF>^ffffffUsing Cloud Rend Strike while in the Fortitude state has a chance to gain the Cloud Rend state,<CRLF>raising the target cap of your next Combo Skill by 3.<CRLF><CRLF>^c3dbffNote: This Cloud Rend state only takes effect while in the Fortitude state."
T[124] = "^c3dbffCloud Rend Strike \u00b7 Fortitude<CRLF>^ffffffRequires at least 5 points invested in \u201cShield Counter\u201d.<CRLF><CRLF>^ffffffShield Counter points can Reduce the Cool-down of Savage Charge.<CRLF>For every 1 sec of Cool-down Reduced, the chance of Savage Charge \u00b7 Skill<CRLF>Immobilizing the target is Reduced by 8%%."
T[125] = "^c3dbffCloud Rend Strike \u00b7 Force<CRLF>^ffffffRequires at least 15 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffUsing Cloud Rend Strike drains the enemy's Defense, lasting 30 sec.<CRLF>The enemy's Defense is Reduced by \u201cenemy level / 4\u201d.<CRLF>Your own Defense is increased by \u201cyour level / 2\u201d."
T[126] = "^c3dbffCloud Rend Strike \u00b7 Skill<CRLF>^ffffffRequires at least 15 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffUsing Cloud Rend Strike drains the enemy's Crit, lasting 30 sec."
T[127] = "^c3dbffCloud Rend Strike \u00b7 Fierce<CRLF><CRLF>^ffffffUsing Cloud Rend Strike while in the Fierce Might state,<CRLF>there is a %d%% chance to gain the Fierce Cloud state.<CRLF>The Crit Rate of your next Combo Skill is boosted.<CRLF><CRLF>^c3dbffNote: This Cloud Rend state only takes effect while in the Fierce Might state."
T[128] = "^c3dbffEarth Rend, Sky Break^ffffff<CRLF><CRLF>Skill Category: Focus Line<CRLF>Skill Quality: III<CRLF>Requirement: Melee<CRLF>High-Tier Move<CRLF><CRLF>Swing your weapon to attack 5 enemies around you<CRLF>dealing 79%% base Damage."
T[129] = "^c3dbffShadow Rend Strike<CRLF><CRLF>^ffffffWeapon: Shield<<PAD>>20 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down Time: 6 sec<CRLF><CRLF>A Combo Skill; requires casting Cloud Rend Strike, Shadow-Seal Slash, and Moon-Break Strike in sequence.<CRLF>Slam the shield into the ground, hitting up to 5 enemies within 5 meters around you<CRLF>for 138%% base Damage.<CRLF>Recovers 20 Battle Qi."
T[130] = "^c3dbffShadow Rend Strike \u00b7 Fortitude<CRLF>^ffffffRequires at least 5 points invested in Fortitude-type Mastery.<CRLF><CRLF>^ffffffUsing Shadow Rend Strike while in the Fortitude state,<CRLF>there is a 60%% chance to send the target into the Shadow Rend state,<CRLF>Reducing Attack Speed and Attack Power.<CRLF>The state lasts 3 sec."
T[131] = "^c3dbffShadow Rend Strike \u00b7 Fortitude<CRLF>^ffffffRequires at least 20 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffWeapon: Shield<<PAD>>10 Stamina<CRLF>Strategy: Instant<<PAD>>Cool-down 30 sec<CRLF><CRLF>Focus your mind and switch to \u201cShield Counter\u201d mode. In this mode,<CRLF>each attack has a chance to gain Shield Counter points.<CRLF>Each Shield Counter point boosts Attack Power by 3%%,<CRLF>and up to 10 points can be accumulated.<CRLF><CRLF>In Shield Counter mode, certain Skills gain additional effects.<CRLF><CRLF>^99ccffNote: Only one mode can be active at a time."
T[132] = "^c3dbffShadow Rend Strike \u00b7 Fierce<CRLF>^ffffffRequires at least 5 points invested in Fierce-type Mastery.<CRLF><CRLF>^ffffffUsing Shadow Rend Strike while in the Fierce Might state<CRLF>increases the base Damage dealt."
T[133] = "^c3dbffMoon Rend Slash<CRLF>^ffffffRequires at least 5 points invested in Fortitude-type Mastery.<CRLF><CRLF>^ffffffWeapon: Shield<<PAD>>15 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down Time: 6 sec<CRLF><CRLF>A Combo Skill; requires casting Cloud Rend Strike, Moon-Break Strike, and Shadow-Seal Slash in sequence.<CRLF>Slam the shield into the ground, damaging up to 5 enemies within 5 meters around you."
T[134] = "^c3dbffMoon Rend Slash<CRLF>^ffffffRequires at least 15 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffBoosts the chance of the Fortified Shield Strike causing a Concussive Wound."
T[135] = "^c3dbffMoon Rend Slash \u00b7 Fortitude<CRLF>^ffffffRequires at least 3 points invested in the \u201cMoon Rend Slash\u201d Mastery.<CRLF><CRLF>^ffffffUsing Moon Rend Slash while in the Fortitude state,<CRLF>has a chance to Slow hit targets by 1.5 m/sec,<CRLF>lasting 4 sec."
T[136] = "^c3dbffMoon Rend Slash \u00b7 Fierce<CRLF>^ffffffRequires at least 5 points invested in Fierce-type Mastery.<CRLF><CRLF>^ffffffUsing Moon Rend Slash while in the Fierce Might state,<CRLF>has a chance to deal extra Ignore-Defense Damage to the target,<CRLF>scaled to the target's Max HP and your distance from them."
T[137] = "^c3dbffFlame Rend Technique<CRLF><CRLF>^ffffffWeapon: Staff<<PAD>>10 Battle Qi, 15 Stamina<CRLF>Move: Instant<CRLF><CRLF>The ground beneath your feet cracks from the searing heat,<CRLF>dealing 60%% base Damage to enemies within 8 meters around you.<CRLF>Affects up to 7 targets.<CRLF>Has a 30%% chance to apply the Burning effect to the target."
T[138] = "^c3dbffFlame Rend Technique \u00b7 Curse<CRLF>^ffffffRequires at least 10 points invested in Curse-type Mastery.<CRLF><CRLF>^ffffff<CRLF>When Flame Rend Technique hits a target in the Burning state,<CRLF>there is a chance to Immobilize the enemy for 3 sec.<CRLF>While Fire Armor is active, repeatedly using Flame Rend Technique has<CRLF>a chance to enter the Fire-Baptized state, dispelling Immobilize and Slow effects,<CRLF>and becoming Immune to them for a time.<CRLF>Direct Resistance +5 points, lasting 5 sec.<CRLF>Boosts Flame Rend Technique's Damage under Fire Armor.<CRLF>At 5 stacks, when Flame Rend Technique hits a target from the front, add an extra<CRLF>30%% chance to Immobilize Burning targets."
T[139] = "^c3dbffFlame Rend Technique \u00b7 Curse<CRLF>^ffffffRequires at least 15 points invested in Curse-type Mastery.<CRLF><CRLF>^ffffffBoosts Flame Rend Technique's Attack.<CRLF>Enemies hit by Flame Rend Technique have a chance to Burn for 6 sec,<CRLF>losing HP equal to (enemy level) per second while Burning."
T[140] = "^c3dbffWrapped Collapse Pounce<CRLF><CRLF>^ffffffThe Damage bonus per stack of Iron Cavalry is further increased.<CRLF><CRLF>^99ccffStandard Attack Mastery. Only one can be learned."
T[141] = "^c3dbffVital Point<CRLF>^ffffffRequires at least 25 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffInsight and Precision gain additional effects."
T[142] = "^c3dbffHeart-Seeking Thrust<CRLF><CRLF>^ffffffWeapon: Sword<<PAD>>30 Battle Qi<<PAD>>5 Stamina<CRLF>Martial Art: Instant<<PAD>>Cool-down 8 sec<CRLF><CRLF>A deadly thrust driving the sword straight into the enemy's heart;<CRLF>once it lands, the foe suffers unimaginably.<CRLF>Adds 25%% Crit Damage,<CRLF>deals 150%% base Damage and may Splash to nearby enemies.<CRLF>While the Combo effect is active, using the Move adds \u201ccurrent combo count \u00d7 10\u201d Crit Rate.<CRLF><CRLF>^c3dbffNote: Recommended for Single-Target attacks; stronger when used with \u201cCombo\u201d.<CRLF><CRLF>^ffffffEach Gale point adds an extra 9%% base Damage to the Move<CRLF>Each Combo point adds an extra 4%% base Damage to the Move"
T[143] = "^c3dbffHeart-Seeking Thrust \u00b7 Force<CRLF>^ffffffRequires at least 4 points invested in Force-type Mastery.<CRLF><CRLF>^ffffffBoosts the Damage dealt by Heart-Seeking Thrust."
T[144] = "^c3dbffHeart-Seeking Thrust \u00b7 Skill<CRLF>^ffffffRequires at least 10 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffBoosts the chance of Heart-Seeking Thrust causing a wound. At 5 stacks, there is a 20%% chance to cause<CRLF>a Mortal Wound effect; the wound lasts up to 30 sec."
T[145] = "^c3dbffHeart-Seeking Thrust \u00b7 Skill<CRLF>^ffffffRequires at least 10 points invested in Skill-type Mastery.<CRLF><CRLF>^ffffffBoosts the Crit Damage dealt by Heart-Seeking Thrust,<CRLF>with a chance to further increase the Crit Damage of Heart-Seeking Thrust."
T[146] = "^c3dbffHeart-Seeking Thrust \u00b7 Heart-Piercing<CRLF>^ffffffRequires at least 5 points invested in \u201cHeart-Seeking Thrust \u00b7 Skill\u201d.<CRLF><CRLF>^ffffffWhile in the Combo state, resets Heart-Seeking Thrust's Cool-down.<CRLF>Triggers at most once every 20 sec."

def norm(t):
    """Normalize <<PAD> (end-of-line variant) to <<PAD>>."""
    t = t.replace("<<PAD>>", "\x00")
    t = t.replace("<<PAD>", "<<PAD>>")
    t = t.replace("\x00", "<<PAD>>")
    return t

PADRUN = re.compile(r"[ \t\u3000]+")
COLOR = re.compile(r"\^[0-9a-fA-F]{6}")
PLACE = re.compile(r"%%|%[0-9$.*]*[a-zA-Z]")
CJK = re.compile(r"[\u4e00-\u9fff\uff00-\uffef]")  # U+3000 padding allowed

def pads(src, tpl):
    if src.count("<CRLF>") != tpl.count("<CRLF>"):
        return None, "CRLF count src=%d tpl=%d" % (src.count("<CRLF>"), tpl.count("<CRLF>"))
    sl = src.split("<CRLF>")
    tl = tpl.split("<CRLF>")
    outl = []
    for i, (s, t) in enumerate(zip(sl, tl)):
        runs = PADRUN.findall(s)
        np = t.count("<<PAD>>")
        if np != len(runs):
            return None, "line %d: src runs=%r tpl PADs=%d | src=%r tpl=%r" % (i, runs, np, s, t)
        it = iter(runs)
        parts = t.split("<<PAD>>")
        merged = parts[0]
        for p in parts[1:]:
            merged += next(it) + p
        outl.append(merged)
    return "<CRLF>".join(outl), None

errors = []
results = []
with open(IN, encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)
        rid, src = rec["id"], rec["source"]
        tpl = T.get(rid)
        if tpl is None:
            errors.append((rid, "missing template"))
            continue
        tpl = norm(tpl)
        eng, err = pads(src, tpl)
        if err:
            errors.append((rid, err))
            continue
        if COLOR.findall(src) != COLOR.findall(eng):
            errors.append((rid, "color codes src=%s tpl=%s" % (COLOR.findall(src), COLOR.findall(eng))))
        if PLACE.findall(src) != PLACE.findall(eng):
            errors.append((rid, "placeholders src=%s tpl=%s" % (PLACE.findall(src), PLACE.findall(eng))))
        if '"' in eng:
            errors.append((rid, "straight double quote in english"))
        cjk = CJK.findall(eng)
        if cjk:
            errors.append((rid, "CJK remains: %r" % "".join(cjk)))
        if "<<PAD>>" in eng:
            errors.append((rid, "unreplaced PAD"))
        results.append({"id": rid, "english": eng})

if errors:
    for rid, msg in errors:
        print("ERROR id=%s: %s" % (rid, msg))
    sys.exit(1)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    for r in results:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print("OK wrote %d lines to %s" % (len(results), OUT))
