# -*- coding: utf-8 -*-
# Exact-substring pairs. Applied in listed order (specific before generic).
PAIRS_A = [
    # ---- record titles: generic "universal" passive skills ----
    ('^c3dbff通用历练', '^c3dbffUniversal Training'),
    ('^c3dbff通用国战', '^c3dbffUniversal Kingdom War'),
    ('^c3dbff通用图鉴', '^c3dbffUniversal Codex'),
    ('^c3dbff通用官渡', '^c3dbffUniversal Guandu'),
    ('^c3dbff通用官职', '^c3dbffUniversal Official Rank'),
    ('^c3dbff通用成长', '^c3dbffUniversal Growth'),
    ('^c3dbff通用护卫', '^c3dbffUniversal Guard'),
    ('^c3dbff通用探宝', '^c3dbffUniversal Treasure Hunt'),
    ('^c3dbff通用水战', '^c3dbffUniversal Naval Battle'),
    ('^c3dbff通用濮阳', '^c3dbffUniversal Puyang'),
    ('^c3dbff通用点卯', '^c3dbffUniversal Roll Call'),
    ('^c3dbff通用玄石', '^c3dbffUniversal Mystic Stone'),
    ('^c3dbff通用秘文', '^c3dbffUniversal Rune'),
    ('^c3dbff通用符玉', '^c3dbffUniversal Talisman Jade'),
    ('^c3dbff通用聚贤谷', '^c3dbffUniversal Sages Vale'),
    ('^c3dbff通用英雄志', '^c3dbffUniversal Heroes Chronicle'),
    ('^c3dbff通用葭萌关', '^c3dbffUniversal Jiameng Pass'),
    ('^c3dbff通用车战', '^c3dbffUniversal Chariot Battle'),
    ('^c3dbff通用钓鱼', '^c3dbffUniversal Fishing'),
    ('^c3dbff通用阅历', '^c3dbffUniversal Insight'),
    ('^c3dbff通用附魂', '^c3dbffUniversal Soul Imbue'),
    # ---- flavor sentences ----
    ('来自祖籍的祝福，打怪获得的历练值提升。', 'A blessing of your ancestral lineage; increases Training gained from defeating monsters.'),
    ('来自祖籍的祝福，打怪获得的阅历值提升。', 'A blessing of your ancestral lineage; increases Insight gained from defeating monsters.'),
    ('来自祖籍的祝福，参加国战的收益提升。', 'A blessing of your ancestral lineage; increases rewards from Kingdom Wars.'),
    ('来自祖籍的祝福，参加图鉴类战场时获得的收益提升。', 'A blessing of your ancestral lineage; increases rewards from Codex-type battlefields.'),
    ('来自祖籍的祝福，完成官渡之战获得奖励提升。', 'A blessing of your ancestral lineage; increases rewards from the Battle of Guandu.'),
    ('来自祖籍的祝福，领取聚财礼包时，将有几率获得官职包。', 'A blessing of your ancestral lineage; grants a chance to obtain an Official Rank Pack when claiming the Wealth Gift Pack.'),
    ('来自祖籍的祝福，装备成长时，直接进入下个成长等级的几率提高。', 'A blessing of your ancestral lineage; increases the chance of advancing straight to the next Growth level when growing equipment.'),
    ('来自祖籍的祝福，护卫提高声望直接进入下一档的几率提升。', 'A blessing of your ancestral lineage; increases the chance of a Guard’s Reputation jumping straight to the next tier.'),
    ('来自祖籍的祝福，完成神州探宝任务获得的收益提升。', 'A blessing of your ancestral lineage; increases rewards from Shenzhou Treasure Hunt quests.'),
    ('来自祖籍的祝福，参加赤壁水战获得的收益提升。', 'A blessing of your ancestral lineage; increases rewards from the Red Cliffs naval battle.'),
    ('来自祖籍的祝福，完成濮阳之战获得奖励提升。', 'A blessing of your ancestral lineage; increases rewards from the Battle of Puyang.'),
    ('来自祖籍的祝福，每日点卯获得的收益提升。', 'A blessing of your ancestral lineage; increases rewards from the daily roll call.'),
    ('来自祖籍的祝福，完成英雄玄石系列任务获得奖励的几率提升。', 'A blessing of your ancestral lineage; increases the chance of rewards from the Hero Mystic Stone quest series.'),
    ('来自祖籍的祝福，秘文升级成功率提升。', 'A blessing of your ancestral lineage; increases Rune upgrade success rate.'),
    ('来自祖籍的祝福，附加符玉时获得高级符玉的几率提升。', 'A blessing of your ancestral lineage; increases the chance of obtaining a high-tier Talisman Jade when inlaying.'),
    ('来自祖籍的祝福，完成聚贤谷任务获得的收益提升。', 'A blessing of your ancestral lineage; increases rewards from Sages Vale quests.'),
    ('来自祖籍的祝福，完成英雄志系列战场获得奖励提升。', 'A blessing of your ancestral lineage; increases rewards from Heroes Chronicle battlefields.'),
    ('来自祖籍的祝福，完成葭萌关战场获得奖励提升。', 'A blessing of your ancestral lineage; increases rewards from the Jiameng Pass battlefield.'),
    ('来自祖籍的祝福，参加襄阳之战的收益提升。', 'A blessing of your ancestral lineage; increases rewards from the Battle of Xiangyang.'),
    ('来自祖籍的祝福，每日钓鱼获得的收益提升。', 'A blessing of your ancestral lineage; increases rewards from daily fishing.'),
    ('来自祖籍的祝福，附魂时获得高级属性的几率提升。', 'A blessing of your ancestral lineage; increases the chance of obtaining a high-tier attribute when Soul Imbuing.'),
    ('来自祖籍的祝福，<CRLF>直接抗性提升。', 'A blessing from your ancestral lineage;<CRLF>Direct Resistance increased.'),
    ('来自祖籍的祝福，<CRLF>所受的间接伤害最终值降低。', 'A blessing from your ancestral lineage;<CRLF>final Indirect Damage taken is reduced.'),
    # ---- achievements ----
    ('前提成就：初出茅庐', 'Prerequisite Achievement: First Steps'),
    ('前提成就：风雨同舟', 'Prerequisite Achievement: Through Thick and Thin'),
    ('前提成就：游刃有余', 'Prerequisite Achievement: Ease and Grace'),
    ('前提成就：兴国安邦', 'Prerequisite Achievement: Pillar of the State'),
    ('前提成就：国家栋梁', 'Prerequisite Achievement: Backbone of the Nation'),
    ('前提成就：国之根本', 'Prerequisite Achievement: Foundation of the Realm'),
    ('前提成就：谈笑自若', 'Prerequisite Achievement: Cool and Collected'),
    ('前提成就：吉人天相', 'Prerequisite Achievement: Fortune’s Favor'),
    ('前提成就：天机下凡', 'Prerequisite Achievement: Heaven’s Secret Descends'),
    ('前提成就：官渡新兵', 'Prerequisite Achievement: Guandu Recruit'),
    ('前提成就：官渡名将', 'Prerequisite Achievement: Guandu General'),
    ('前提成就：官渡军神', 'Prerequisite Achievement: Guandu War God'),
    ('前提成就：初入仕途', 'Prerequisite Achievement: First Steps in Office'),
    ('前提成就：官运亨通', 'Prerequisite Achievement: Rising Career'),
    ('前提成就：鹏程万里', 'Prerequisite Achievement: Bright Prospects'),
    ('前提成就：忠实战友', 'Prerequisite Achievement: Loyal Comrade'),
    ('前提成就：同仇敌忾', 'Prerequisite Achievement: Shared Resolve'),
    ('前提成就：亲如兄弟', 'Prerequisite Achievement: Close as Brothers'),
    ('前提成就：挖地三尺', 'Prerequisite Achievement: Digging Deep'),
    ('前提成就：寻宝天下', 'Prerequisite Achievement: Treasure of the Realm'),
    ('前提成就：偷天换日', 'Prerequisite Achievement: Heaven-Swapping Ruse'),
    ('前提成就：初熟水性', 'Prerequisite Achievement: Sea Legs'),
    ('前提成就：南人善水', 'Prerequisite Achievement: Born of the South'),
    ('前提成就：如履平地', 'Prerequisite Achievement: Sure Footing'),
    ('前提成就：濮阳新兵', 'Prerequisite Achievement: Puyang Recruit'),
    ('前提成就：濮阳名将', 'Prerequisite Achievement: Puyang General'),
    ('前提成就：濮阳军神', 'Prerequisite Achievement: Puyang War God'),
    ('前提成就：准时准点', 'Prerequisite Achievement: Punctual'),
    ('前提成就：持之以恒', 'Prerequisite Achievement: Perseverance'),
    ('前提成就：风雨无阻', 'Prerequisite Achievement: Rain or Shine'),
    ('前提成就：英雄之路', 'Prerequisite Achievement: Path of the Hero'),
    ('前提成就：英姿勃发', 'Prerequisite Achievement: Heroic Presence'),
    ('前提成就：大显神通', 'Prerequisite Achievement: Display of Might'),
    ('前提成就：招贤纳士', 'Prerequisite Achievement: Talent Scout'),
    ('前提成就：任人唯贤', 'Prerequisite Achievement: Merit First'),
    ('前提成就：礼贤下士', 'Prerequisite Achievement: Honoring the Sages'),
    ('前提成就：精兵强将', 'Prerequisite Achievement: Elite Ranks'),
    ('前提成就：军中猛将', 'Prerequisite Achievement: Army Champion'),
    ('前提成就：万夫莫敌', 'Prerequisite Achievement: One Against All'),
    ('前提成就：葭萌新兵', 'Prerequisite Achievement: Jiameng Recruit'),
    ('前提成就：葭萌名将', 'Prerequisite Achievement: Jiameng General'),
    ('前提成就：葭萌军神', 'Prerequisite Achievement: Jiameng War God'),
    ('前提成就：出生入死', 'Prerequisite Achievement: Into the Breach'),
    ('前提成就：百炼成身', 'Prerequisite Achievement: Tempered Body'),
    ('前提成就：战无不胜', 'Prerequisite Achievement: Invincible'),
    ('前提成就：以渔为生', 'Prerequisite Achievement: Living by the Line'),
    ('前提成就：授人与渔', 'Prerequisite Achievement: Teach to Fish'),
    ('前提成就：钓鱼达人', 'Prerequisite Achievement: Fishing Master'),
    ('前提成就：身经百战', 'Prerequisite Achievement: Battle-Hardened'),
    ('前提成就：转战千里', 'Prerequisite Achievement: Thousand-Mile Campaign'),
    ('前提成就：戎马生涯', 'Prerequisite Achievement: Life of Warfare'),
    # ---- shared label text ----
    ('属性：被动', 'Type: Passive'),
    ('属性：铁骑', 'Type: Iron Cavalry'),
    ('技能生效祖籍限制：扬州', 'Ancestry Requirement for Effect: Yangzhou'),
    ('技能生效祖籍限制：兖州', 'Ancestry Requirement for Effect: Yanzhou'),
    ('技能生效祖籍限制：凉州', 'Ancestry Requirement for Effect: Liangzhou'),
    ('技能类别：勇猛系', 'Skill Category: Valor'),
    ('技能类别：灵活系', 'Skill Category: Agility'),
    ('技能类别：专注系', 'Skill Category: Focus'),
    ('技能类别：热血系', 'Skill Category: Zeal'),
    ('技能品质：壹', 'Skill Rank: I'),
    ('技能品质：贰', 'Skill Rank: II'),
    ('技能品质：叁', 'Skill Rank: III'),
    ('技能品质：肆', 'Skill Rank: IV'),
    ('技能品质：伍', 'Skill Rank: V'),
    ('学习需求：近程', 'Requirement: Melee'),
    ('学习需求：远程', 'Requirement: Ranged'),
    ('学习需求：无', 'Requirement: None'),
    ('基础招式', 'Basic Move'),
    ('进阶招式', 'Advanced Move'),
    ('高阶招式', 'Expert Move'),
    ('辅助招式', 'Support Move'),
    ('战车专用', 'Chariot Only'),
    ('学习消耗：荣耀值', 'Learning Cost: '),
    ('荣耀值', 'Glory'),
    ('兵器：', 'Weapon: '),
    ('消耗：', 'Cost: '),
    ('无消耗', 'No Cost'),
    ('魂技类型：攻击类', 'Soul Skill Type: Attack'),
    ('魂技效果：', 'Soul Skill Effect: '),
    ('骑术：激活', 'Mounted: Toggle'),
    ('骑术：移动施放', 'Mounted: Cast while moving'),
    ('骑术：瞬发', 'Mounted: Instant'),
    ('骑术：', 'Mounted: '),
    ('武技：瞬发', 'Martial Art: Instant'),
    ('武技：', 'Martial Art: '),
    ('策略：瞬发', 'Strategy: Instant'),
    ('策略：', 'Strategy: '),
    ('策略:', 'Strategy: '),
    # ---- R11 roll-call level lines ----
    ('点卯将获得初级历练包、初级阅历包，', 'Roll call grants a Basic Training Pack and a Basic Insight Pack,'),
    ('点卯将获得中级历练包、中级阅历包，', 'Roll call grants an Intermediate Training Pack and an Intermediate Insight Pack,'),
    ('点卯将获得高级历练包、高级阅历包，', 'Roll call grants an Advanced Training Pack and an Advanced Insight Pack,'),
    ('有5%%几率获得灵气包。', 'with a 5%% chance to obtain a Spirit Pack.'),
    ('有10%%几率获得灵气包。', 'with a 10%% chance to obtain a Spirit Pack.'),
    ('有15%%几率获得灵气包。', 'with a 15%% chance to obtain a Spirit Pack.'),
    # ---- R91-R93 full-line note blocks (must precede generic 注： rule) ----
    ('^c3dbff注：技能在铁壁·怒之后使用，可使自身<CRLF>受到的伤害降低；<CRLF>技能在铁壁·破之后使用，可使被击中目<CRLF>标定身。', '^c3dbffNote: Used after Iron Wall · Rage, reduces the damage you<CRLF>take;<CRLF>used after Iron Wall · Break, Immobilizes the<CRLF>target hit.'),
    ('^c3dbff注：技能在铁壁·破之后使用，可使攻击<CRLF>力与防御力额外提升；<CRLF>技能在铁壁·军之后使用，可使队友提升<CRLF>一定的攻击力与防御力。', '^c3dbffNote: Used after Iron Wall · Break, further Boosts your<CRLF>Attack Power and Defense;<CRLF>used after Iron Wall · Army, Boosts your allies’<CRLF>Attack Power and Defense by a certain amount.'),
    ('^c3dbff注：技能在铁壁·怒之后使用，可使攻击<CRLF>速度与攻击强度额外降低；<CRLF>技能在铁壁·军之后使用，可使目标概率<CRLF>眩晕2秒。', '^c3dbffNote: Used after Iron Wall · Rage, further reduces their<CRLF>Attack Speed and Attack Strength;<CRLF>used after Iron Wall · Army, has a chance to<CRLF>Stun the target for 2 seconds.'),
    ('招式：瞬发', 'Move: Instant'),
    ('武技：瞬发', 'Martial Art: Instant'),
    ('专精：瞬发', 'Mastery: Instant'),
    ('必杀：瞬发', 'Finisher: Instant'),
    ('每秒5斗气', '5 Battle Qi per second'),
    ('持续施放', 'Channeled'),
    ('学习需要相应的技能书。', 'Requires the corresponding skill book to learn.'),
    ('只能在骑战状态下使用。', 'Can only be used while mounted.'),
    ('只能在骑乘状态下使用。', 'Can only be used while mounted.'),
    ('注：打怪推荐技能，作为斗气积累技。', 'Note: Recommended for farming; used to build Battle Qi.'),
    ('注：国色状态下使用，可接连招：回龙乱；', 'Note: Used in the National Beauty state, chains into the combo: Dragon’s Return;'),
    ('天香状态下使用，可接连招：缠颈打。', 'Used in the Heavenly Fragrance state, chains into the combo: Neck Bind Strike.'),
    ('注：', 'Note: '),
    # ---- skill titles (skill-specific) ----
    ('^c3dbff速击·强攻', '^c3dbffSwift Strike · Onslaught'),
    ('^c3dbff速击·打断', '^c3dbffSwift Strike · Interrupt'),
    ('^c3dbff速击·技', '^c3dbffSwift Strike · Technique'),
    ('^c3dbff速击·撕裂', '^c3dbffSwift Strike · Rend'),
    ('^c3dbff速击·力', '^c3dbffSwift Strike · Power'),
    ('^c3dbff速打·力', '^c3dbffSwift Blow · Power'),
    ('^c3dbff速打·打断', '^c3dbffSwift Blow · Interrupt'),
    ('^c3dbff速打·技', '^c3dbffSwift Blow · Technique'),
    ('^c3dbff速攻·御', '^c3dbffSwift Assault · Guard'),
    ('^c3dbff速攻·打断', '^c3dbffSwift Assault · Interrupt'),
    ('^c3dbff速攻·破', '^c3dbffSwift Assault · Break'),
    ('^c3dbff速砍·力', '^c3dbffSwift Slash · Power'),
    ('^c3dbff速砍·打断', '^c3dbffSwift Slash · Interrupt'),
    ('^c3dbff速砍·技', '^c3dbffSwift Slash · Technique'),
    ('^c3dbff邪气入体·强攻', '^c3dbffSinister Qi · Onslaught'),
    ('^c3dbff邪气入体·归元', '^c3dbffSinister Qi · Reversion'),
    ('^c3dbff醉云击·强攻', '^c3dbffDrunken Cloud Strike · Onslaught'),
    ('^c3dbff醉云击·飞将', '^c3dbffDrunken Cloud Strike · Flying General'),
    ('^c3dbff野火燎原·咒', '^c3dbffPrairie Wildfire · Curse'),
    ('^c3dbff野火燎原·引燃', '^c3dbffPrairie Wildfire · Ignite'),
    ('^c3dbff野火燎原·忽视', '^c3dbffPrairie Wildfire · Pierce'),
    ('^c3dbff野火燎原·策', '^c3dbffPrairie Wildfire · Tactic'),
    ('^c3dbff金丝缠·魅', '^c3dbffGolden Coil · Charm'),
    ('^c3dbff金蛇乱舞·影', '^c3dbffGolden Serpent Dance · Shadow'),
    ('^c3dbff金蛇乱舞·魅', '^c3dbffGolden Serpent Dance · Charm'),
    ('^c3dbff铁壁·军', '^c3dbffIron Wall · Army'),
    ('^c3dbff铁壁·怒', '^c3dbffIron Wall · Rage'),
    ('^c3dbff铁壁·破', '^c3dbffIron Wall · Break'),
    ('^c3dbff铮铮之舞·策', '^c3dbffClanging Dance · Tactic'),
    ('^c3dbff铮铮之舞·辅', '^c3dbffClanging Dance · Support'),
    ('^c3dbff银蛇缚·魅', '^c3dbffSilver Serpent Bind · Charm'),
    ('^c3dbff速击', '^c3dbffSwift Strike'),
    ('^c3dbff速射', '^c3dbffRapid Shot'),
    ('^c3dbff速打', '^c3dbffSwift Blow'),
    ('^c3dbff速攻', '^c3dbffSwift Assault'),
    ('^c3dbff速砍', '^c3dbffSwift Slash'),
    ('^c3dbff遁形', '^c3dbffVanish'),
    ('^c3dbff遁袭', '^c3dbffShadow Raid'),
    ('^c3dbff遁走', '^c3dbffEscape'),
    ('^c3dbff邪气入体', '^c3dbffSinister Qi'),
    ('^c3dbff醉云击', '^c3dbffDrunken Cloud Strike'),
    ('^c3dbff醉舞补天', '^c3dbffDrunken Mending Dance'),
    ('^c3dbff重斩', '^c3dbffHeavy Slash'),
    ('^c3dbff重砸', '^c3dbffHeavy Smash'),
    ('^c3dbff重骑突进', '^c3dbffHeavy Cavalry Charge'),
    ('^c3dbff野火燎原', '^c3dbffPrairie Wildfire'),
    ('^c3dbff金丝炫舞', '^c3dbffGolden Flash Dance'),
    ('^c3dbff金丝缠', '^c3dbffGolden Bind'),
    ('^c3dbff金刀怒斩', '^c3dbffGolden Saber Rage'),
    ('^c3dbff金声玉振', '^c3dbffGolden Chime'),
    ('^c3dbff金蛇乱舞', '^c3dbffGolden Serpent Dance'),
    ('^c3dbff金蛇狂舞', '^c3dbffGolden Serpent Rampage'),
    ('^c3dbff金钟', '^c3dbffGolden Bell'),
    ('^c3dbff钝足', '^c3dbffDull Foot'),
    ('^c3dbff钩意诡谲', '^c3dbffHook Guile'),
    ('^c3dbff钩意', '^c3dbffHook Intent'),
    ('^c3dbff钩镰打', '^c3dbffHook Scythe Strike'),
    ('^c3dbff钩镰', '^c3dbffHook Scythe'),
    ('^c3dbff钺魂', '^c3dbffAxe Soul'),
    ('^c3dbff铁卫', '^c3dbffIron Guard'),
    ('^c3dbff铁壁', '^c3dbffIron Wall'),
    ('^c3dbff铁甲金汤', '^c3dbffIronclad Bulwark'),
    ('^c3dbff铁胄', '^c3dbffIron Helm'),
    ('^c3dbff铁门扣', '^c3dbffIron Gate Latch'),
    ('^c3dbff铁骑', '^c3dbffIron Cavalry'),
    ('^c3dbff野蛮冲撞', '^c3dbffSavage Charge'),
    ('^c3dbff铜雀锁', '^c3dbffBronze Sparrow Lock'),
    ('^c3dbff铭印', '^c3dbffInscription'),
    ('^c3dbff铮铮之舞', '^c3dbffClanging Dance'),
    ('^c3dbff银蛇缚', '^c3dbffSilver Serpent Bind'),
    ('^c3dbff锁定', '^c3dbffLock On'),
    ('^c3dbff挑打^ffffff后接^c3dbff锋刺^ffffff出现^ff0000稳健^ffffff效果，下一次攻击增加命中25点；', '^c3dbffUpward Strike^ffffff followed by ^c3dbffSharp Thrust^ffffff grants the ^ff0000Steady^ffffff effect, adding 25 Hit to the next attack;'),
    ('^c3dbff逆打^ffffff后接^c3dbff锋刺^ffffff出现^ff0000迅捷^ffffff效果，下一次攻击减少出招0.3秒<CRLF>和冷却时间2秒。', '^c3dbffReverse Strike^ffffff followed by ^c3dbffSharp Thrust^ffffff grants the ^ff0000Swift^ffffff effect, reducing the next attack’s wind-up by 0.3 seconds<CRLF>and its cool-down by 2 seconds.'),
    ('^c3dbff锋刺', '^c3dbffSharp Thrust'),
    ('^c3dbff锁灵术', '^c3dbffSpirit Lock'),
    ('^c3dbff逸群', '^c3dbffSupremacy'),
]
