# -*- coding: utf-8 -*-
# SEG: exact full-segment Chinese -> English (prose, notes, REQ lines, headers)
# Stat blocks (兵器/招式/冷却 etc with U+3000 padding) handled by regex in main script.
SEG_LIST = [
    ('1. 攻击将对敌人造成一次灵魂伤害，觉醒状态下', '1. The attack deals one Soul damage instance to the enemy; when cast in Awakened state'),
    ('1. 攻击将对敌人造成连续三次的灵魂伤害，觉', '1. The attack deals three consecutive Soul damage instances to the enemy; when cast in Awakened state'),
    ('100%%基础攻击。', '100%% base attack.'),
    ('10分钟内命中提升。', 'Hit increased for 10 min.'),
    ('2. 攻击有%d%%概率对生命值低于50%%的敌人造成额外伤害，', '2. The attack has a %d%% chance to deal bonus damage to enemies below 50%% HP,'),
    ('2. 觉醒状态下施放有%d%%的几率给敌人附加禁食效果，', '2. When cast in Awakened state, there is a %d%% chance to apply Starve to the enemy,'),
    ('2. 觉醒状态下施放有%d%%的机率击晕敌人3秒，该', '2. When cast in Awakened state, there is a %d%% chance to Stun the enemy for 3 sec; the'),
    ('50%%基础攻击。', '50%% base attack.'),
    ('9级之后，每级将额外获得4点攻击力。', 'After level 9, each level grants an additional 4 Attack Power.'),
    ('^99ccff只能在骑乘状态下使用。', '^99ccffCan only be used while mounted.'),
    ('^99ccff只能在骑战状态下使用。', '^99ccffCan only be used in mounted combat.'),
    ('^99ccff右键点击图标可激活或关闭自动释放功能', '^99ccffRight-click the icon to toggle auto-cast on or off'),
    ('^99ccff奋力攻击专精，只能学习一个。', '^99ccffOnslaught mastery. Only one can be learned.'),
    ('^99ccff学习需要相应的技能书。', '^99ccffRequires the corresponding skill book to learn.'),
    ('^99ccff必杀攻击专精，只能学习一个。', '^99ccffKilling Blow mastery. Only one can be learned.'),
    ('^99ccff战法类专精，只能学习一个。', '^99ccffWar Tactic mastery. Only one can be learned.'),
    ('^99ccff战车对人物只造成10%%伤害', '^99ccffChariots deal only 10%% damage to players'),
    ('^99ccff标准攻击专精，只能学习一个。', '^99ccffStandard Attack mastery. Only one can be learned.'),
    ('^99ccff源自荀彧。', '^99ccffFrom Xun Yu.'),
    ('^99ccff源自薛综。', '^99ccffFrom Xue Zong.'),
    ('^99ccff源自虎豹骑。', '^99ccffFrom the Tiger and Leopard Cavalry.'),
    ('^99ccff牵制技能专精，只能学习一个。', '^99ccffCrowd-control skill mastery. Only one can be learned.'),
    ('^99ccff终极专精，只能学习一个。', '^99ccffUltimate mastery. Only one can be learned.'),
    ('^99ccff觉醒状态下使用生效', '^99ccffTakes effect when used in Awakened state'),
    ('^c3dbff倒地效果对等级超过自己5级以上玩家不生效。', '^c3dbffThe knockdown effect does not apply to players 5 or more levels above you.'),
    ('^c3dbff同时消耗两层魅影状态。', '^c3dbffAlso consumes two Phantom stacks.'),
    ('^c3dbff技能伤害提升25%%/50%%/100%%，', '^c3dbffSkill damage increased by 25%%/50%%/100%%,'),
    ('^c3dbff注：只能在使用碎环式后2秒内使用。', '^c3dbffNote: Can only be used within 2 sec after using Ring-Shatter.'),
    ('^c3dbff注：打怪推荐技能，作为斗气积累技。', '^c3dbffNote: Recommended for grinding. Serves as a Battle Qi builder.'),
    ('^c3dbff注：打怪推荐技能，作为斗气释放技。', '^c3dbffNote: Recommended for grinding. Serves as a Battle Qi spender.'),
    ('^c3dbff注：打怪推荐技能，作为起始技。', '^c3dbffNote: Recommended for grinding. Serves as an opener.'),
    ('^c3dbff注：破系技能，只能在破军技法下使用。', '^c3dbffNote: A Break-line skill. Can only be used under the Break Army technique.'),
    ('^c3dbff注：群体攻击推荐技能，不需要选择目标。', '^c3dbffNote: Recommended AoE skill. No target required.'),
    ('^c3dbff注：自身属性强化推荐技能。', '^c3dbffNote: Recommended self-buff skill.'),
    ('^c3dbff注：轻弩状态下，基础伤害最多增加25%%。', '^c3dbffNote: In Light Crossbow state, base damage increased by up to 25%%.'),
    ('^c3dbff注：连击模式的状态效果需在以下三个25点以上的专精技能', '^c3dbffNote: The Combo Mode effect requires at least 25 points invested in one of the following three mastery skills'),
    ('^c3dbff注：魅影状态层数为1/3/5时，', '^c3dbffNote: When Phantom stacks are at 1/3/5,'),
    ('^c3dbff等级1^ffffff：驱散减速，并在3秒内无视这类效果。', '^c3dbffLevel 1^ffffff: Removes Slows, and ignores such effects for 3 sec.'),
    ('^c3dbff等级2^ffffff：驱散减速、定身，并在3秒内无视这类效果。', '^c3dbffLevel 2^ffffff: Removes Slows and Immobilize, and ignores such effects for 3 sec.'),
    ('^c3dbff等级3^ffffff：驱散减速、定身，并在3秒内无视眩晕和这类效果。', '^c3dbffLevel 3^ffffff: Removes Slows and Immobilize, and ignores Stun and such effects for 3 sec.'),
    ('^ffcc00特效^ffffff - 命中修正-20。', '^ffcc00Special Effect^ffffff - Hit Modifier -20.'),
    ('^ffffff“碎石打”造成的致残效果持续时间内，', '^ffffffWhile the Cripple caused by “Boulder Strike” lasts,'),
    ('^ffffff使用“砸击”招式击中正在出招的对手时，', '^ffffffWhen the “Smash” move hits an opponent who is winding up,'),
    ('^ffffff使用快攻有一定概率造成沉默无法出招。', '^ffffffQuick Attack has a chance to Silence the target, preventing actions.'),
    ('^ffffff使用空刃有一定概率使沉默。', '^ffffffVoid Blade has a chance to Silence.'),
    ('^ffffff使用突击攻击敌人时，有几率获得待伏效果8秒，', '^ffffffWhen attacking an enemy with Charge, you have a chance to gain the Ambush effect for 8 sec,'),
    ('^ffffff使用速射有一定概率造成定身。', '^ffffffRapid Fire has a chance to Immobilize.'),
    ('^ffffff使神威枪根据当前连击数增加伤害。', '^ffffffMakes Divine Might Spear deal bonus damage based on your current Combo count.'),
    ('^ffffff向目标进行快速的突打，', '^ffffffLaunches a quick strike at the target,'),
    ('^ffffff呼风唤雨造成绊马效果的概率提升。', '^ffffffIncreases the chance for Call Wind and Rain to apply the Leg Bind effect.'),
    ('^ffffff咒印术冷却时间缩短。', '^ffffffCurse Seal Art cool-down reduced.'),
    ('^ffffff咒印术效果持续时间延长。', '^ffffffCurse Seal Art effect duration increased.'),
    ('^ffffff增加离甲劈伤敌人的机率。', '^ffffffIncreases the chance for Armor Sunder to wound enemies.'),
    ('^ffffff增强突击后造成的攻速提升效果。', '^ffffffEnhances the attack-speed boost applied after Charge.'),
    ('^ffffff增强突袭后造成的攻速提升效果。', '^ffffffEnhances the attack-speed boost applied after Raid.'),
    ('^ffffff对周围敌人造成大量伤害，', '^ffffffDeals heavy damage to surrounding enemies,'),
    ('^ffffff强袭打的伤害会出现波动，', '^ffffffFierce Raid Strike’s damage fluctuates,'),
    ('^ffffff快速反应，召出一柄的利枪刺向最远8米的敌人，', '^ffffffReact swiftly, summoning a keen spear to strike the enemy up to 8 m away,'),
    ('^ffffff快速反应，召出一柄的利枪刺向远处的敌人。', '^ffffffReact swiftly, summoning a keen spear to strike a distant enemy.'),
    ('^ffffff扬起马鞭，提升骑乘的移动速度。', '^ffffffRaise your riding crop to boost mounted movement speed.'),
    ('^ffffff挥舞战锤对目标进行两次快速攻击，', '^ffffffSwing your warhammer to strike the target twice in quick succession,'),
    ('^ffffff挥舞此枪，龙影相随，势不可挡。', '^ffffffSwing this spear with a dragon shadow in tow—unstoppable.'),
    ('^ffffff提升“砸击”给敌人造成的伤害。', '^ffffffIncreases the damage “Smash” deals to enemies.'),
    ('^ffffff提升“碎石打”给敌人造成致残效果的几率。', '^ffffffIncreases the chance that “Boulder Strike” will Cripple enemies.'),
    ('^ffffff提升招式“碎石打”给敌人造成的伤害。', '^ffffffIncreases the damage the “Boulder Strike” move deals to enemies.'),
    ('^ffffff提升碎骨造成的伤害。', '^ffffffIncreases the damage Bone Crusher deals.'),
    ('^ffffff提升磐石纹身的防御力加成。', '^ffffffIncreases Boulder Tattoo’s Defense bonus.'),
    ('^ffffff提升神威一触造成的伤害。', '^ffffffIncreases the damage Divine Might Touch deals.'),
    ('^ffffff提升神威枪造成的伤害。', '^ffffffIncreases the damage Divine Might Spear deals.'),
    ('^ffffff提升神龙探海造成的伤害。', '^ffffffIncreases the damage Divine Dragon Searches the Sea deals.'),
    ('^ffffff提升离甲造成的伤害。', '^ffffffIncreases the damage Armor Sunder deals.'),
    ('^ffffff提升秋风扫造成的伤害。', '^ffffffIncreases the damage Autumn Wind Sweep deals.'),
    ('^ffffff提升穿云袭造成的伤害。', '^ffffffIncreases the damage Cloud-Piercing Assault deals.'),
    ('^ffffff提升穿心击造成的伤害。', '^ffffffIncreases the damage Heart-Piercer deals.'),
    ('^ffffff提升突刺造成刺伤的机率。加满5层后有20%%概率造成', '^ffffffIncreases the chance that Pierce will wound. At 5 stacks, there is a 20%% chance to deal'),
    ('^ffffff提升突刺造成的伤害。', '^ffffffIncreases the damage Pierce deals.'),
    ('^ffffff提升突袭造成的伤害。', '^ffffffIncreases the damage Raid deals.'),
    ('^ffffff提升粉碎一击造成的伤害。', '^ffffffIncreases the damage Shattering Blow deals.'),
    ('^ffffff提升罗刹造成的伤害。', '^ffffffIncreases the damage Rakshasa deals.'),
    ('^ffffff每个疾风点数为招式额外增加5%%基础伤害', '^ffffffEach Gale point adds 5%% base damage to the move'),
    ('^ffffff流星乱舞、咒印术、极寒箭伤害提升。', '^ffffffMeteor Wild Dance, Curse Seal Art, and Biting Cold Arrow damage increased.'),
    ('^ffffff激励全体队友，增强其马匹间接伤害抗性。', '^ffffffInspires all allies, boosting their mounts’ indirect damage resistance.'),
    ('^ffffff碎环式基础伤害提升。', '^ffffffRing-Shatter base damage increased.'),
    ('^ffffff碎石鞭基础伤害提升，', '^ffffffBoulder Whip base damage increased,'),
    ('^ffffff碎骨有一定几率威摄敌人，使其攻击力降低，', '^ffffffBone Crusher has a chance to Intimidate the enemy, lowering their Attack Power,'),
    ('^ffffff磐石纹身下使用技能，将给目标加上磐石标记，', '^ffffffUsing skills under Boulder Tattoo applies a Boulder Mark to the target,'),
    ('^ffffff神威一触有几率降低目标攻击速度、', '^ffffffDivine Might Touch has a chance to reduce the target’s attack speed,'),
    ('^ffffff神威枪造成刺伤的几率提升。加满5层后有20%%概率造成', '^ffffffDivine Might Spear’s chance to wound is increased. At 5 stacks, there is a 20%% chance to deal'),
    ('^ffffff神龙探海有几率对敌进行追杀，', '^ffffffDivine Dragon Searches the Sea has a chance to pursue the enemy,'),
    ('^ffffff离甲可额外造成敌方普通攻击间隔增长，持续10秒。', '^ffffffArmor Sunder can additionally extend the enemy’s normal attack interval, lasting 10 sec.'),
    ('^ffffff空刺的吟唱时间直接缩短。', '^ffffffVoid Thrust’s cast time is reduced outright.'),
    ('^ffffff穿云袭有一定几率附带无视防御伤害，', '^ffffffCloud-Piercing Assault has a chance to deal bonus Ignore-Defense damage,'),
    ('^ffffff穿心击有一定几率附带无视防御伤害，', '^ffffffHeart-Piercer has a chance to deal bonus Ignore-Defense damage,'),
    ('^ffffff穿肠爪、穿肠爪·伏击有几率无视目标抵抗效果', '^ffffffEviscerating Claw and Eviscerating Claw: Ambush have a chance to ignore the target’s resistance effects'),
    ('^ffffff突击后有几率触发连击模式；', '^ffffffAfter Charge, there is a chance to trigger Combo Mode;'),
    ('^ffffff突击后有几率触发霸气效果；', '^ffffffAfter Charge, there is a chance to trigger the Dominance effect;'),
    ('^ffffff突刺招式有可能定身目标。', '^ffffffThe Pierce move may Immobilize the target.'),
    ('^ffffff突袭有一定几率使目标进入神伤状态，', '^ffffffRaid has a chance to put the target into the Divine Wound state,'),
    ('^ffffff突进矢基础伤害提升。', '^ffffffAdvancing Bolt base damage increased.'),
    ('^ffffff突进矢有几率使目标进入箭伤状态，', '^ffffffAdvancing Bolt has a chance to put the target into the Arrow Wound state,'),
    ('^ffffff粉碎一击有几率使目标进入弱战状态，弱战状态下，', '^ffffffShattering Blow has a chance to put the target into the Weakened Combat state. While in that state,'),
    ('^ffffff红颜冷却时间降低。', '^ffffffBeauty’s cool-down reduced.'),
    ('^ffffff缩短“碎心锤”的招式冷却时间。', '^ffffffReduces the move cool-down of “Heart Crusher”.'),
    ('^ffffff缩短“碎心锤”的招式准备时间。', '^ffffffReduces the move wind-up time of “Heart Crusher”.'),
    ('^ffffff罗刹有几率重创敌人，持续流失生命，', '^ffffffRakshasa has a chance to Devastate the enemy, causing ongoing HP drain,'),
    ('^ffffff聚体力于掌心向敌人推出，', '^ffffffGather Stamina in your palms and thrust it at the enemy,'),
    ('^ffffff聚敛自身锋芒，永久提升防御力。', '^ffffffGather your edge inward, permanently increasing Defense.'),
    ('^ffffff聚集自身能力放出一束空牙，', '^ffffffChannel your power to release a burst of Void Fang,'),
    ('^ffffff跳起此舞，几如九天仙女落凡尘，', '^ffffffDance this dance, as if a celestial fairy descended to the mortal world,'),
    ('^ffffff跳起此舞，彷佛有花之清香入鼻，淡淡飘散。', '^ffffffDance this dance, and a faint floral fragrance drifts to your nose.'),
    ('^ffffff跳起此舞，神迹相随，啸吟长空。', '^ffffffDance this dance, trailed by divine signs, howling across the sky.'),
    ('^ffffff跳起此舞，身畔绿波荡漾，莲叶田田，夏意清凉。', '^ffffffDance this dance, and green waves ripple at your side; lotus leaves spread wide, summer coolness refreshing.'),
    ('^ffffff跳起起舞，笛声悠悠，恍若隔世。', '^ffffffDance this dance, a flute drifting softly, as if from another lifetime.'),
    ('^ffffff降低直攻技能冷却时间。', '^ffffffReduces Direct Strike skill cool-down.'),
    ('^ffffff降低突袭冷却时间。', '^ffffffReduces Raid’s cool-down.'),
    ('^ffffff随意挥舞手中的兵器，', '^ffffffWield your weapon freely,'),
    ('^ffffff需要至少在“强化穿肠爪”上投入5点。', '^ffffffRequires at least 5 points invested in “Enhanced Eviscerating Claw”.'),
    ('^ffffff需要至少在“碎环式·破”专精上投入5点。', '^ffffffRequires at least 5 points invested in “Ring-Shatter: Break” Mastery.'),
    ('^ffffff需要至少在“碎石打·影”专精上投入2点。', '^ffffffRequires at least 2 points invested in “Boulder Strike: Shadow” Mastery.'),
    ('^ffffff需要至少在“突刺·技”上投入5点。', '^ffffffRequires at least 5 points invested in “Pierce: Technique”.'),
    ('^ffffff需要至少在“银蛇缚·魅”上投入3点。', '^ffffffRequires at least 3 points invested in “Silver Serpent Bind: Charm”.'),
    ('^ffffff需要至少在伤类专精上投入10点。', '^ffffffRequires at least 10 points invested in the Wound Mastery.'),
    ('^ffffff需要至少在伤类专精上投入5点。', '^ffffffRequires at least 5 points invested in the Wound Mastery.'),
    ('^ffffff需要至少在力类专精上投入10点。', '^ffffffRequires at least 10 points invested in the Power Mastery.'),
    ('^ffffff需要至少在力类专精上投入20点。', '^ffffffRequires at least 20 points invested in the Power Mastery.'),
    ('^ffffff需要至少在力类专精上投入30点。', '^ffffffRequires at least 30 points invested in the Power Mastery.'),
    ('^ffffff需要至少在力类专精投入10点。', '^ffffffRequires at least 10 points invested in the Power Mastery.'),
    ('^ffffff需要至少在影类专精上投入10点。', '^ffffffRequires at least 10 points invested in the Shadow Mastery.'),
    ('^ffffff需要至少在影类专精上投入25点。', '^ffffffRequires at least 25 points invested in the Shadow Mastery.'),
    ('^ffffff需要至少在怒类专精上投入5点。', '^ffffffRequires at least 5 points invested in the Rage Mastery.'),
    ('^ffffff需要至少在技类专精上投入10点。', '^ffffffRequires at least 10 points invested in the Technique Mastery.'),
    ('^ffffff需要至少在技类专精上投入15点。', '^ffffffRequires at least 15 points invested in the Technique Mastery.'),
    ('^ffffff需要至少在技类专精上投入20点。', '^ffffffRequires at least 20 points invested in the Technique Mastery.'),
    ('^ffffff需要至少在破类专精上投入20点。', '^ffffffRequires at least 20 points invested in the Break Mastery.'),
    ('^ffffff需要至少在突袭·连击专精投入2点。', '^ffffffRequires at least 2 points invested in Raid: Combo Mastery.'),
    ('^ffffff需要至少在舞类专精上投入15点。', '^ffffffRequires at least 15 points invested in the Dance Mastery.'),
    ('^ffffff需要至少在舞类专精上投入5点。', '^ffffffRequires at least 5 points invested in the Dance Mastery.'),
    ('^ffffff需要至少怒类专精上投入10点。', '^ffffffRequires at least 10 points invested in the Rage Mastery.'),
    ('^ffffff马上跳起，向目标区域猛力刺击，', '^ffffffLeap from your horse and thrust fiercely at the target area,'),
    ('“红颜”状态持续10秒。', 'The “Beauty” state lasts 10 sec.'),
    ('一定距离冲刺奔跑突击敌人。', 'Charge at the enemy from a distance.'),
    ('一次性回复生命。', 'Restores HP instantly.'),
    ('下降1米/秒，持续5秒。', 'reduced by 1 m/s, lasting 5 sec.'),
    ('不能和风阵效果共存。', 'Cannot coexist with the Wind Formation effect.'),
    ('专精加满3级将获得“磐石印记”，', 'At 3 mastery points, you gain the “Boulder Mark”,'),
    ('专精招式。', 'Mastery move.'),
    ('专精招式。穿肠爪的偷袭加强版。', 'Mastery move. An enhanced ambush version of Eviscerating Claw.'),
    ('中途有可能被障碍物挡住。', 'It may be blocked by obstacles midway.'),
    ('乱舞迷人眼、心神皆破伤', 'Wild Dance dazzles the eye; mind and spirit both break and wound'),
    ('云中竹笛悠悠声，飘摇江湖惹情伤。', 'A bamboo flute drifts through the clouds, swaying through the martial world, stirring heartache.'),
    ('产生10点斗气。', 'Generates 10 Battle Qi.'),
    ('产生10点斗气。只能在战斗外使用。', 'Generates 10 Battle Qi. Can only be used outside combat.'),
    ('产生10点斗气。必须战斗外使用。', 'Generates 10 Battle Qi. Must be used outside combat.'),
    ('产生15点斗气。有一定几率刺伤敌人。', 'Generates 15 Battle Qi. Has a chance to wound the enemy.'),
    ('产生5点斗气。', 'Generates 5 Battle Qi.'),
    ('任意攻击招式结束效果（燃怒劈除外）。', 'Ends the effect with any attack move (Rage Cleave excluded).'),
    ('伤害值为护卫攻击力的30%%。', 'Damage equals 30%% of the Guard’s Attack Power.'),
    ('伤害抗性降低的效果可连续叠加。', 'The Damage Resistance reduction effect stacks consecutively.'),
    ('但当冲阵多于五层时，马匹难以驾驭，', 'But when Charge Formation exceeds five stacks, the horse becomes hard to control,'),
    ('位移到目标身前，', 'Teleport in front of the target,'),
    ('体内的怒气都会随时间而缓缓积蓄。', 'Rage within the body slowly builds over time.'),
    ('体质提升%d', 'Constitution increased by %d'),
    ('使用可获得“红颜”状态，', 'Using this grants the “Beauty” state,'),
    ('使用后驱散周围队友的受伤状态，自身', 'After use, dispels the injured state of nearby allies, while yourself'),
    ('使用官印技能冲撞时将有额外效果。', 'Charging with an Official Seal skill gains an additional effect.'),
    ('使用手中的双锤快速砸击敌人。', 'Quickly Smash the enemy with your twin hammers.'),
    ('使用技能后会自动下马。', 'Automatically dismounts after using the skill.'),
    ('使用横扫时，也有一定几率获得待伏效果4秒。', 'When using Sweep, you also have a chance to gain the Ambush effect for 4 sec.'),
    ('使用碎石鞭有50%%几率打断目标出招。', 'Boulder Whip has a 50%% chance to interrupt the target’s action.'),
    ('使用磐石纹身，唤醒潜在力量', 'Use Boulder Tattoo to awaken latent power'),
    ('使用突袭后，可以使用突袭·斩,产生5点斗气。突击到目标面前，造成伤害。', 'After using Raid, you can use Raid: Cleave, generating 5 Battle Qi. Charge to the target and deal damage.'),
    ('修治铠甲，齐整军容，', 'Repair armor and straighten the ranks,'),
    ('内心如山一般稳固，无论战斗情势如何变化，', 'The heart is steady as a mountain; no matter how the battle shifts,'),
    ('出其不意，横扫敌人下盘，击倒对手。', 'Catch the enemy off guard, sweep their legs, and knock them down.'),
    ('击中后可对敌人造成150%%基础伤害。', 'On hit, deals 150%% base damage to the enemy.'),
    ('击破敌人护甲，降低其暴击抗性，持续10秒。', 'Shatters the enemy’s armor, reducing their Crit Resistance for 10 sec.'),
    ('分两段向敌人攻击，招式凶狠有力。', 'Attacks the enemy in two strikes; the move is fierce and powerful.'),
    ('利用战车的身体击倒目标。', 'Use the chariot’s body to knock down the target.'),
    ('利用战车的身体攻击目标。', 'Use the chariot’s body to attack the target.'),
    ('剑罡·御心、追风、剑落·弑中，点出其中一个，才可生效。', 'Sword Aura: Mind Guard, Windchase, or Sword Fall: Slay—invest in one of them to activate.'),
    ('单个敌人施放一次灵魂攻击。', 'Unleashes a single Soul attack on one enemy.'),
    ('单个敌人进行连续三次的灵魂攻击。', 'Unleashes three consecutive Soul attacks on one enemy.'),
    ('双爪最为凶狠残忍的招式，使敌人痛不欲生无法行动。', 'The most brutal move of the twin claws, leaving the enemy in unbearable agony, unable to act.'),
    ('受到的所有伤害降低5%%', 'All damage taken reduced by 5%%'),
    ('叠加至3层时使用相应技能（引雷钩、百毒入髓、吴鸿扈稽、', 'When stacked to 3, use the corresponding skill (Lightning Hook, Hundred Poisons Marrow, Wu Hong Hu Ji,'),
    ('只能在使用突袭打之后3秒内使用。', 'Can only be used within 3 sec after using Raid Strike.'),
    ('召唤融入体内的英雄魂魄，加强自身属性，', 'Summon the hero soul fused within you to enhance your own attributes,'),
    ('召唤融入体内的英雄魂魄，对自身施放纵横状态。', 'Summon the hero soul fused within you to cast the Prowess state on yourself.'),
    ('召唤融入体内的英雄魂魄，对身前5米距离内的', 'Summon the hero soul fused within you to target those within 5 m in front of you'),
    ('召唤融入体内的英雄魂魄，对身前7米距离内的', 'Summon the hero soul fused within you to target those within 7 m in front of you'),
    ('可能提升也可能降低。', 'It may increase or decrease.'),
    ('右手持鞭狠狠抽下，', 'Whip down hard with the right hand,'),
    ('右手持鞭迅速挥出，', 'Whip out swiftly with the right hand,'),
    ('同时产生10点斗气，一定几率将敌人击落下马。', 'Also generates 10 Battle Qi, with a chance to knock the enemy off their horse.'),
    ('同时对倒地目标造成一定的无视防御伤害。', 'Also deals bonus Ignore-Defense damage to knocked-down targets.'),
    ('同时技能对敌人造成无视防御伤害，', 'The skill also deals Ignore-Defense damage to the enemy,'),
    ('同时有低概率将敌人击落下马。', 'Also has a low chance to knock the enemy off their horse.'),
    ('同时自身向前腾跃15米。', 'Also leap forward 15 m.'),
    ('同时被击中时可获得天罡状态，提升', 'Also, when hit, you can gain the Celestial Vigor state, boosting'),
    ('同时造成一定的无视防御伤害。', 'Also deals bonus Ignore-Defense damage.'),
    ('向最远25米位置缩地前进，', 'Earth Step up to 25 m away,'),
    ('吟唱速度，降低攻击、吟唱速度效果与', 'cast speed, reducing attack and cast speed effects as well as'),
    ('命中提升。', 'Hit increased.'),
    ('命中敌人将使其受到绊马效果影响，', 'Hitting an enemy applies the Leg Bind effect,'),
    ('回复10斗气。', 'Restores 10 Battle Qi.'),
    ('回复10点斗气。', 'Restores 10 Battle Qi.'),
    ('回复15斗气。', 'Restores 15 Battle Qi.'),
    ('回复5斗气。', 'Restores 5 Battle Qi.'),
    ('在磐石纹身作用下，其他技能会有额外效果', 'While Boulder Tattoo is active, other skills gain additional effects'),
    ('在突进矢·技上加满三点专精后，可获得突进状态，', 'After investing 3 points in Advancing Bolt: Technique, you gain the Advancing state,'),
    ('在自身法术强度>10时，将对目标产生一个延时缴械效果，3秒后目', 'When your Spell Power >10, the target receives a delayed Disarm effect; after 3 sec the tar'),
    ('在隐伏中用爪攻击并造成眩晕效果。', 'Attack with claws while in Ambush and apply the Stun effect.'),
    ('均可无视“魅影”状态层数要求，获得最强效果。', 'Both ignore the “Phantom” stack requirement and grant the strongest effect.'),
    ('基础招式', 'Basic Move'),
    ('增加防御力，持续1分钟。', 'Increases Defense, lasting 1 min.'),
    ('增强突袭后造成的攻速提升效果。', 'Enhances the attack-speed boost applied after Raid.'),
    ('增强追风后造成的攻速提升效果。', 'Enhances the attack-speed boost applied after Windchase.'),
    ('如同利刃一般攻击远方敌人。获得5点斗气。', 'Strike distant enemies like a keen blade. Generates 5 Battle Qi.'),
    ('如同利刃一般攻击远方敌人，', 'Strike distant enemies like a keen blade,'),
    ('如果遭受攻击可能会陷入短暂的眩晕状态。', 'If attacked, you may fall into a brief Stun.'),
    ('对倒地目标造成88%%基础伤害，', 'Deals 88%% base damage to knocked-down targets,'),
    ('对其造成120%%基础伤害（直接伤害）。', 'Deals 120%% base damage to it (direct damage).'),
    ('对其造成153%%基础伤害。', 'Deals 153%% base damage to it.'),
    ('对前方10米范围内所有目标造成300%%基础伤害。', 'Deals 300%% base damage to all targets within 10 m ahead.'),
    ('对前方25米范围内目标造成100%%基础伤害。', 'Deals 100%% base damage to targets within 25 m ahead.'),
    ('对区域内的目标造成大量伤害。', 'Deals heavy damage to targets in the area.'),
    ('对周围5米范围内的敌人造成80%%的基础伤害，', 'Deals 80%% base damage to enemies within 5 m,'),
    ('对周围的敌人造成伤害，', 'Deals damage to surrounding enemies,'),
    ('对敌人造成80%%基础伤害。', 'Deals 80%% base damage to the enemy.'),
    ('对敌人造成定身效果。产生4点斗气，疾风3层下产生额外6点斗气。', 'Applies the Immobilize effect to the enemy. Generates 4 Battle Qi; at 3 Gale stacks, generates an additional 6 Battle Qi.'),
    ('对敌人造成定身效果。招式命中后提升15%%攻速，直到使用', 'Applies the Immobilize effect to the enemy. On hit, boosts attack speed by 15%% until you use'),
    ('对敌人造成定身效果。自身增加15%%攻速，', 'Applies the Immobilize effect to the enemy. Boosts your attack speed by 15%%,'),
    ('对目标及其周围最多5个目标造成伤害。', 'Deals damage to the target and up to 5 targets around them.'),
    ('对目标造成88%%基础伤害，', 'Deals 88%% base damage to the target,'),
    ('对目标造成伤害的同时，使其间接抗性降低，', 'While dealing damage to the target, also reduces their indirect resistance,'),
    ('对目标造成伤害的同时，并对目标造成诅咒', 'While dealing damage to the target, also Curses the target'),
    ('对身前最多3个敌人，造成122%%基础伤害。', 'Deals 122%% base damage to up to 3 enemies in front of you.'),
    ('对马下目标造成短暂眩晕效果。', 'Applies a brief Stun to targets dismounted.'),
    ('将消耗15斗气、5体力。', 'Consumes 15 Battle Qi and 5 Stamina.'),
    ('并且横抡后也有几率触发霸气效果。', 'Also, after a Swing there is a chance to trigger the Dominance effect.'),
    ('并且突刺后也有几率触发连击模式。', 'Also, after Pierce there is a chance to trigger Combo Mode.'),
    ('并使其斗气上限降至零点，持续5秒。', 'Also reduces their Battle Qi cap to zero, lasting 5 sec.'),
    ('并大幅降低目标的骑乘与移动速度。', 'Also greatly reduces the target’s mounted and movement speed.'),
    ('并造成3秒破招效果。', 'Also applies a 3-sec Parry Break effect.'),
    ('开战前，快速跃至目标敌人附近攻击敌人。', 'Before battle, quickly leap near the target enemy and attack.'),
    ('开战前，相隔一定距离冲刺奔跑，突击敌人。', 'Before battle, charge at the enemy from a distance.'),
    ('弱战状态持续8秒。', 'The Weakened Combat state lasts 8 sec.'),
    ('当人物处于“瞬杀”或“破天”状态时，', 'When the character is in the “Instant Kill” or “Heaven Break” state,'),
    ('当前刺杀效果积累情况而减少。', 'reduced based on the current stack count of the Assassinate effect.'),
    ('当斗气大于15且体力不满时，', 'When Battle Qi exceeds 15 and Stamina is not full,'),
    ('当满足以下条件时触发兵法的中级效果：', 'The war tactic’s mid-tier effect triggers when the following conditions are met:'),
    ('当满足以下条件时触发兵法的高级效果：', 'The war tactic’s high-tier effect triggers when the following conditions are met:'),
    ('必须隐伏中使用。', 'Must be used while in Ambush.'),
    ('快速攻击敌人，动作迅捷有力。', 'Attack the enemy quickly; the motion is swift and powerful.'),
    ('快速攻击，对前方直线范围内3名敌人', 'Quickly attack, hitting 3 enemies in a straight line ahead'),
    ('战车两侧箭弩向前方发出弩箭，', 'Crossbows on both sides of the chariot fire bolts forward,'),
    ('战鼓对建筑造成20%%额外伤害', 'The war drum deals 20%% bonus damage to structures'),
    ('手中双锤从正面冲撞敌人，造成60%%基础伤害。', 'Charge the enemy head-on with your twin hammers, dealing 60%% base damage.'),
    ('投掷飞剑攻击附近16米内的1个目标，造成50%%基础攻击伤害,', 'Throw a flying sword at 1 target within 16 m, dealing 50%% base attack damage,'),
    ('护卫计谋值相关，状态持续10秒。', 'scales with the Guard’s Tactics. The state lasts 10 sec.'),
    ('招式会为自身回复10点斗气。', 'The move restores 10 Battle Qi to yourself.'),
    ('招式造成75%%的基础伤害。', 'The move deals 75%% base damage.'),
    ('持弩向前突进10米，然后向前方射程内', 'Charge forward 10 m with your crossbow, then within range ahead'),
    ('持续10分钟。', 'Lasts 10 min.'),
    ('持续流失生命，状态持续10秒。', 'Causes ongoing HP drain; the state lasts 10 sec.'),
    ('持鞭迅速击打敌人造成135%%基础伤害，', 'Whip the enemy quickly, dealing 135%% base damage,'),
    ('持鞭迅速击打敌人造成144%%基础伤害，', 'Whip the enemy quickly, dealing 144%% base damage,'),
    ('持鞭迅速击打敌人造成94%%基础伤害，', 'Whip the enemy quickly, dealing 94%% base damage,'),
    ('接在碎环式后使用，', 'Use after Ring-Shatter,'),
    ('提升结义内将士的攻击强度和防御能力。', 'Boosts the Attack Power and Defense of warriors within the sworn brotherhood.'),
    ('攻击力及生命上限大幅提升，', 'Greatly boosts Attack Power and max HP,'),
    ('攻击敌人造成其眩晕效果数秒。招式的出招时间会随', 'Attack the enemy to Stun them for several seconds. The move’s wind-up time scales with'),
    ('攻击最远20米的敌人，', 'Attack the enemy up to 20 m away,'),
    ('攻击最远20米的敌人，对其造成50%%基础伤害。', 'Attack the enemy up to 20 m away, dealing 50%% base damage.'),
    ('攻击有40%%几率附带10秒的致残效果，', 'Attacks have a 40%% chance to apply the Cripple effect for 10 sec,'),
    ('攻击身前目标及其周围最多5名敌人，', 'Attack the target in front of you and up to 5 enemies around them,'),
    ('攻坚能力极强，为魏之精锐，', 'Exceptionally strong at breaking fortifications; the elite of Wei,'),
    ('效果可持续45秒。', 'The effect lasts up to 45 sec.'),
    ('效果持续时间至少为40秒。', 'The effect lasts at least 40 sec.'),
    ('效果的持续时间不受炼魂等级的影响。', 'The effect duration is not affected by Soul Forging level.'),
    ('新手护卫专用技能，对敌人造成150%%基础伤害', 'A novice Guard-only skill; deals 150%% base damage to the enemy'),
    ('施放的伤害加倍；', 'The cast damage is doubled;'),
    ('旋转武器，对自身周围多个敌人进行攻击。', 'Spin your weapon, attacking multiple enemies around you.'),
    ('暴击抗性提升，状态持续4秒。', 'Crit Resistance increased; the state lasts 4 sec.'),
    ('最多击中5个敌人。', 'Hits up to 5 enemies.'),
    ('最多叠加5层。', 'Stacks up to 5 times.'),
    ('最高可达到目标最大攻击力的5倍。', 'Up to 5 times the target’s max Attack Power.'),
    ('有几率使目标沉默额外沉默2秒，额外沉默效果不会被抵抗。', 'Has a chance to Silence the target for an extra 2 sec; the extra Silence cannot be resisted.'),
    ('有可能立即打断对手出招动作，', 'May immediately interrupt the opponent’s wind-up action,'),
    ('有较大概率震伤敌人，同时令敌人眩晕4秒，', 'High chance to wound the enemy, also Stunning them for 4 sec,'),
    ('有较高概率将目标击落下马，并造成摔马效果。', 'Fairly high chance to knock the target off their horse, applying the Unmount effect.'),
    ('束鞭成棍，向前快速刺出，', 'Curl the whip into a staff and thrust forward quickly,'),
    ('来自祖籍的祝福，', 'A blessing from your heritage,'),
    ('标将无法使用技能。', 'the target will be unable to use skills.'),
    ('此比例受护卫计谋值影响，最小为0.5。', 'This ratio scales with the Guard’s Tactics, with a minimum of 0.5.'),
    ('每个乱舞点数会减少招式准备时间0.1秒。', 'Each Wild Dance point reduces the move’s wind-up time by 0.1 sec.'),
    ('每个乱舞点数会增加10%%的斗气回复。', 'Each Wild Dance point increases Battle Qi recovery by 10%%.'),
    ('每个强攻点数会额外增加4%%招式基础伤害；', 'Each Assault point adds an extra 4%% base damage to the move;'),
    ('每个强攻点数会额外增加8%%招式基础伤害；', 'Each Assault point adds an extra 8%% base damage to the move;'),
    ('每个疾风点数为招式额外增加3.5%%基础伤害', 'Each Gale point adds an extra 3.5%% base damage to the move'),
    ('每个连击点数为招式额外增加1%%基础伤害', 'Each Combo point adds an extra 1%% base damage to the move'),
    ('每个连击点数为招式额外增加1.5%%基础伤害', 'Each Combo point adds an extra 1.5%% base damage to the move'),
    ('每击中1人获1斗气，最多命中5人。', 'Gain 1 Battle Qi per enemy hit, up to 5 enemies.'),
    ('每多一层有12%%概率使自身甩落马下。', 'Each additional stack has a 12%% chance to throw you off your horse.'),
    ('每层冲阵使无视防御伤害提升10%%。', 'Each Charge Formation stack increases Ignore-Defense damage by 10%%.'),
    ('每层冲阵状态提升技能伤害5%%', 'Each Charge Formation stack increases skill damage by 5%%'),
    ('每层刺杀效果减少出招时间0.2秒。', 'Each Assassinate stack reduces wind-up time by 0.2 sec.'),
    ('每层降低目标3%%攻击强度，持续8秒，最多叠加3层，', 'Reduces the target’s Attack Power by 3%% per stack, lasting 8 sec, stacking up to 3 times,'),
    ('每点生命对敌造成一定比例的无视防御伤害，', 'Each HP point deals a proportional amount of Ignore-Defense damage to the enemy,'),
    ('法术强度>10，30%%概率造成缴械。>30，100%%概率造成缴械。', 'Spell Power >10: 30%% chance to Disarm. > 30: 100%% chance to Disarm.'),
    ('流失的生命值为护卫计谋值的50%%，', 'The HP drained equals 50%% of the Guard’s Tactics,'),
    ('流星矢基础伤害提升50%%，却月矢吟唱时间减少1秒。', 'Meteor Arrow’s base damage increased by 50%%; Crescent Moon Arrow’s cast time reduced by 1 sec.'),
    ('牺牲自身1500点生命，', 'Sacrifice 1500 of your own HP,'),
    ('状态持续10秒。', 'The state lasts 10 sec.'),
    ('状态持续3秒。', 'The state lasts 3 sec.'),
    ('猛将之躯，破阵之胆。', 'The body of a fierce general, the courage to break formations.'),
    ('用长枪攻击前方敌人的招式。', 'A move that attacks the enemy ahead with a long spear.'),
    ('疾风3层提升45%%概率，连击10层提升30%%概率，倒地持续2秒。', 'At 3 Gale stacks, chance increased by 45%%; at 10 Combo stacks, chance increased by 30%%. Knockdown lasts 2 sec.'),
    ('疾风3层提升45%%概率，连击10层提升40%%概率，被破防者2秒内无法使用技能。', 'At 3 Gale stacks, chance increased by 45%%; at 10 Combo stacks, chance increased by 40%%. Armor-broken targets cannot use skills for 2 sec.'),
    ('百花不解相思意，浅笑不知缘几许。', 'A hundred flowers cannot fathom lovesickness; a faint smile, destiny unknowable.'),
    ('的一个敌人发动强力射击。', 'one enemy with a powerful shot.'),
    ('目标每次攻击都会对自己造成一定反弹伤害', 'Each of the target’s attacks deals a portion of reflected damage back to them'),
    ('目标每次攻击，将减少攻击力60点，可叠加5层，', 'Each of the target’s attacks reduces their Attack Power by 60, stacking up to 5 times,'),
    ('直到使用其它攻击招式打击敌人为止。', 'until you use another attack move to strike the enemy.'),
    ('相隔一定距离突击敌人，造成先手优势。', 'Charge the enemy from a distance, gaining the first-strike advantage.'),
    ('破系技能，只能在破军技法下使用。', 'A Break-line skill; can only be used under the Break Army technique.'),
    ('积蓄全身力量，奋力一击。', 'Gather strength from your whole body and strike with all your might.'),
    ('移动速度提升%.1f米/秒，穿透、刺破提升%d点。', 'Movement speed increased by %.1f m/s; Penetration and Wound bonus increased by %d.'),
    ('穿透、刺破提升%d点。', 'Penetration and Wound bonus increased by %d.'),
    ('穿透点数提升。', 'Penetration points increased.'),
    ('突破敌阵，自己能在敌阵中更自由的行动。', 'Break through the enemy formation, allowing freer movement within it.'),
    ('突袭后有几率触发连击模式；', 'After Raid, there is a chance to trigger Combo Mode;'),
    ('第一段造成175%%基础伤害，', 'The first strike deals 175%% base damage,'),
    ('第一段造成180%%基础伤害，', 'The first strike deals 180%% base damage,'),
    ('第二段造成78%%基础伤害。', 'The second strike deals 78%% base damage.'),
    ('第二段造成83%%基础伤害。', 'The second strike deals 83%% base damage.'),
    ('红颜状态下使用消耗“魅影”状态层数的连招，', 'Use while in the Beauty state to consume “Phantom” stacks with a combo,'),
    ('自身为圆心6米范围内所有目标造成350%%基础伤害。', 'Deals 350%% base damage to all targets within 6 m of yourself.'),
    ('自身回复10点斗气。', 'Restores 10 Battle Qi to yourself.'),
    ('自身增加15%%攻速，使用任意攻击招式攻击目标一定次数后停止。', 'Boosts your attack speed by 15%%; stops after you hit the target a set number of times with any attack move.'),
    ('自身增加15%%攻速，直到使用其它攻击招式打击敌人为止。', 'Boosts your attack speed by 15%% until you use another attack move to strike the enemy.'),
    ('自身防御与昏迷抗性，持续5秒，', 'Boosts your own Defense and Knockout Resistance, lasting 5 sec,'),
    ('致残状态下遭受攻击会降低伤害抗性，', 'While crippled, taking a hit reduces Damage Resistance,'),
    ('若目标处于突袭造成的“破绽”状态，则有一定概率被击倒，', 'If the target is in the “Opening” state caused by Raid, there is a chance to knock them down,'),
    ('若目标处于防御状态，则直接由疾风与连击的层数决定破防概率，', 'If the target is defending, the Armor Break chance is determined directly by Gale and Combo stacks,'),
    ('获得8秒罡魂状态，持续期间不会受伤，', 'Gain the Vigor Soul state for 8 sec; you cannot be injured while it lasts,'),
    ('落英缤纷飞香雨，翩翩落花映红颜。', 'Petals scatter like fragrant rain; graceful falling blooms reflect a lovely face.'),
    ('蓄力后发出，招式刚猛无比，', 'Unleashed after charging up; the move is overwhelmingly fierce,'),
    ('血之饥渴、大卸八块），目标沉默3秒，', 'Blood Thirst, Dismember), the target is Silenced for 3 sec,'),
    ('被攻击有5%%几率获得神定状态，', 'When attacked, there is a 5%% chance to gain the Divine Focus state,'),
    ('被暴击有10%%几率获得经国状态，', 'When critically hit, there is a 10%% chance to gain the Statecraft state,'),
    ('觉醒下施放，移动速度提升%.1f米/秒，', 'When cast in Awakened state, movement speed increased by %.1f m/s,'),
    ('觉醒状态下释放，有%d%%概率对生命值低于50%%的敌人', 'When cast in Awakened state, there is a %d%% chance against enemies below 50%% HP'),
    ('该效果持续至少5秒。', 'The effect lasts at least 5 sec.'),
    ('跃起后反手持叉猛戳前方地面，', 'Leap and stab the ground ahead fiercely with a reverse-gripped trident,'),
    ('进阶招式', 'Advanced Move'),
    ('连招，接在银蛇缚后使用，', 'A combo used after Silver Serpent Bind,'),
    ('造成10%%基础伤害。', 'Deals 10%% base damage.'),
    ('造成100%%基础伤害。', 'Deals 100%% base damage.'),
    ('造成110%%基础伤害。', 'Deals 110%% base damage.'),
    ('造成110%%基础伤害，有较小几率震伤目标，', 'Deals 110%% base damage, with a small chance to wound the target,'),
    ('造成120%%基础伤害。', 'Deals 120%% base damage.'),
    ('造成145%%基础伤害。', 'Deals 145%% base damage.'),
    ('造成160%%基础伤害。', 'Deals 160%% base damage.'),
    ('造成196%%基础伤害。', 'Deals 196%% base damage.'),
    ('造成254%%基础伤害。', 'Deals 254%% base damage.'),
    ('造成260%%基础伤害。', 'Deals 260%% base damage.'),
    ('造成278%%基础伤害。', 'Deals 278%% base damage.'),
    ('造成30%%基础伤害。', 'Deals 30%% base damage.'),
    ('造成58%%基础伤害。', 'Deals 58%% base damage.'),
    ('造成64%%基础伤害。', 'Deals 64%% base damage.'),
    ('造成75%%基础伤害。', 'Deals 75%% base damage.'),
    ('造成83%%基础伤害。', 'Deals 83%% base damage.'),
    ('造成定身效果，必须战斗外使用。', 'Applies the Immobilize effect; must be used outside combat.'),
    ('造成较大伤害并且有可能刺伤敌人。', 'Deals heavy damage and may wound the enemy.'),
    ('造成额外伤害，且有%d%%概率秒杀生命值低于10%%的目标。', 'Deals bonus damage, with a %d%% chance to instantly kill targets below 10%% HP.'),
    ('醒状态下施放的伤害加倍；', 'cast while in Awakened state, the damage is doubled;'),
    ('释放斗气对敌人进行强烈攻击。', 'Release Battle Qi to strike the enemy fiercely.'),
    ('重伤效果，刺伤效果持续时间高达30秒。', 'the Heavy Wound effect; the wound effect lasts up to 30 sec.'),
    ('随士燮投吴，为当时名儒，', 'Following Shi Xie to Wu, a renowned scholar of his time,'),
    ('集中精力，增加射击的准确性。', 'Focus your mind to improve shooting accuracy.'),
    ('额外有一定几率使敌人移动速度', 'Also has a chance to cause the enemy’s movement speed'),
    ('骑乘速度下降2.5米/秒，持续10秒。', 'Mounted speed reduced by 2.5 m/s, lasting 10 sec.'),
    ('高阶招式', 'High-Level Move'),
    ('高高跃起，积攒全身力量奋力一击，', 'Leap high, gather strength from your whole body, and strike with all your might,'),
    ('魏国首席谋臣，治国有方，', 'Wei’s chief strategist, skilled in governance,'),
    ('^ffffff消耗：体力超过20', '^ffffffCost: over 20 Stamina'),
    ('学习需求：无', 'Learn Requirement: None'),
]
SEG = dict(SEG_LIST)
