# -*- coding: utf-8 -*-
import re

# NAMES: Chinese term -> English. Applied longest-first (sorted at import).
# Covers skill names, UI labels, weapon names, places, status names.
NAMES_LIST = [
    # skill names (variants before base)
    ('碎环式二式', 'Ring-Shatter Form II'), ('碎环式·倒地', 'Ring-Shatter: Knockdown'), ('碎环式·破', 'Ring-Shatter: Break'), ('碎环式', 'Ring-Shatter'),
    ('碎石打·猛击', 'Boulder Strike: Crush'), ('碎石打·力', 'Boulder Strike: Power'), ('碎石打·影', 'Boulder Strike: Shadow'), ('碎石打', 'Boulder Strike'),
    ('碎石鞭·影', 'Boulder Whip: Shadow'), ('碎石鞭', 'Boulder Whip'),
    ('碎骨·威摄', 'Bone Crusher: Intimidate'), ('碎骨·强攻', 'Bone Crusher: Assault'), ('碎骨', 'Bone Crusher'),
    ('碎心锤·强化', 'Heart Crusher: Fortified'), ('碎心锤·舞', 'Heart Crusher: Dance'), ('碎心锤', 'Heart Crusher'),
    ('碎兵', 'Shatter Arms'), ('碟呤', 'Butterfly Chime'), ('碧波旋', 'Azure Wave Spin'),
    ('磐石标记', 'Boulder Mark'), ('磐石纹身·力', 'Boulder Tattoo: Power'), ('磐石纹身', 'Boulder Tattoo'), ('磐石', 'Boulder'),
    ('神伤之舞', 'Divine Wound Dance'), ('神咒初', 'Divine Curse: Initiate'),
    ('神威一触·压制', 'Divine Might Touch: Suppress'), ('神威一触·强攻', 'Divine Might Touch: Assault'), ('神威一触', 'Divine Might Touch'),
    ('神威乱舞', 'Divine Might Wild Dance'), ('神威枪·力', 'Divine Might Spear: Power'), ('神威枪·技', 'Divine Might Spear: Technique'), ('神威枪', 'Divine Might Spear'), ('神威', 'Divine Might'),
    ('神定', 'Divine Focus'), ('神枪破空', 'Divine Spear: Sky Pierce'), ('神舞倚天', 'Divine Dance: Heaven’s Lean'),
    ('神速枪', 'Swift Divine Spear'), ('神鬼莫测', 'Unfathomable'),
    ('神龙探海·强攻', 'Divine Dragon Searches the Sea: Assault'), ('神龙探海·追杀', 'Divine Dragon Searches the Sea: Pursuit'), ('神龙探海', 'Divine Dragon Searches the Sea'),
    ('禁字诀', 'Silence Mantra'), ('禁络', 'Meridian Seal'), ('离影刺', 'Shadow-Leave Thrust'),
    ('离甲·衰弱', 'Armor Sunder: Weaken'), ('离甲·伤', 'Armor Sunder: Wound'), ('离甲·怒', 'Armor Sunder: Rage'), ('离甲', 'Armor Sunder'),
    ('秋风扫·影', 'Autumn Wind Sweep: Shadow'), ('秋风扫', 'Autumn Wind Sweep'),
    ('积芒', 'Accumulated Light'), ('稳固', 'Steadfast'),
    ('空刃', 'Void Blade'), ('空刺', 'Void Thrust'), ('空牙', 'Void Fang'),
    ('穿云式', 'Cloud-Pierce Form'), ('穿云袭·强攻', 'Cloud-Piercing Assault: Assault'), ('穿云袭·飞将', 'Cloud-Piercing Assault: Flying General'), ('穿云袭', 'Cloud-Piercing Assault'),
    ('穿心击·强攻', 'Heart-Piercer: Assault'), ('穿心击·飞将', 'Heart-Piercer: Flying General'), ('穿心击', 'Heart-Piercer'),
    ('穿杨射', 'Willow-Piercing Shot'), ('穿橹', 'Oar Piercer'),
    ('穿肠爪·伏击', 'Eviscerating Claw: Ambush'), ('穿肠爪·破', 'Eviscerating Claw: Break'), ('穿肠爪', 'Eviscerating Claw'),
    ('突击·乱舞', 'Charge: Wild Dance'), ('突击·待伏', 'Charge: Ambush'), ('突击·连击', 'Charge: Combo'), ('突击·霸气', 'Charge: Dominance'), ('突击', 'Charge'),
    ('突刺·定身', 'Pierce: Immobilize'), ('突刺·力', 'Pierce: Power'), ('突刺·技', 'Pierce: Technique'), ('突刺', 'Pierce'),
    ('突破', 'Breakthrough'),
    ('突袭·乱舞', 'Raid: Wild Dance'), ('突袭·强攻', 'Raid: Assault'), ('突袭·斩', 'Raid: Cleave'), ('突袭·神伤', 'Raid: Divine Wound'), ('突袭·连击', 'Raid: Combo'),
    ('突袭打', 'Raid Strike'), ('突袭', 'Raid'),
    ('突进矢·力', 'Advancing Bolt: Power'), ('突进矢·技', 'Advancing Bolt: Technique'), ('突进矢', 'Advancing Bolt'),
    ('立马斩', 'Instant Mount Slash'), ('笑红尘', 'Laughing at the Mortal World'), ('笛音绝', 'Flute’s End'),
    ('策马扬鞭', 'Spur the Horse, Raise the Whip'), ('箭殇', 'Arrow Sorrow'), ('箭袭', 'Arrow Assault'), ('簧击', 'Reed Strike'),
    ('粉碎一击·弱战', 'Shattering Blow: Weakened Combat'), ('粉碎一击·强攻', 'Shattering Blow: Assault'), ('粉碎一击', 'Shattering Blow'),
    ('精准', 'Precision'), ('精锐', 'Elite'), ('精魂', 'Spirit Soul'),
    ('红颜·影', 'Beauty: Shadow'), ('红颜舞', 'Beauty Dance'), ('红颜', 'Beauty'),
    ('线风', 'Thread Wind'), ('经国', 'Statecraft'), ('绝命击', 'Fatal Strike'), ('绝情杀', 'Ruthless Kill'),
    ('绪乱琢', 'Disordered Carve'), ('续晴', 'Clearing Skies'), ('缚心诀', 'Heart-Bind Mantra'), ('缠颈打', 'Neck Lock Strike'),
    ('缤纷百花雨', 'Colorful Hundred Flower Rain'), ('缩地', 'Earth Step'), ('缮甲治兵', 'Armor and Arms'),
    ('罗刹·强攻', 'Rakshasa: Assault'), ('罗刹·重创', 'Rakshasa: Devastate'), ('罗刹', 'Rakshasa'),
    ('罡魂', 'Vigor Soul'), ('羁碟绊暮', 'Butterfly Tether at Dusk'),
    ('砸击·破', 'Smash: Break'), ('砸击·舞', 'Smash: Dance'), ('砸击', 'Smash'),
    ('破阵锤', 'Formation Breaker'), ('破魂刺', 'Soul-Shattering Thrust'),
    ('强化穿肠爪', 'Enhanced Eviscerating Claw'), ('强袭打', 'Fierce Raid Strike'),
    ('流星乱舞', 'Meteor Wild Dance'), ('流星矢', 'Meteor Arrow'), ('却月矢', 'Crescent Moon Arrow'), ('极寒箭', 'Biting Cold Arrow'),
    ('咒印术', 'Curse Seal Art'), ('呼风唤雨', 'Call Wind and Rain'), ('燃怒劈', 'Rage Cleave'),
    ('速射', 'Rapid Fire'), ('快攻', 'Quick Attack'), ('直攻', 'Direct Strike'), ('横扫', 'Sweep'),
    ('银蛇缚·魅', 'Silver Serpent Bind: Charm'), ('银蛇缚', 'Silver Serpent Bind'),
    ('引雷钩', 'Lightning Hook'), ('百毒入髓', 'Hundred Poisons Marrow'), ('吴鸿扈稽', 'Wu Hong Hu Ji'),
    ('天罡', 'Celestial Vigor'), ('神伤', 'Divine Wound'), ('魅影', 'Phantom'), ('瞬杀', 'Instant Kill'), ('破天', 'Heaven Break'),
    ('破绽', 'Opening'), ('破防', 'Armor Break'), ('破招', 'Parry Break'), ('冲阵', 'Charge Formation'),
    ('待伏', 'Ambush'), ('霸气', 'Dominance'), ('连击', 'Combo'), ('乱舞', 'Wild Dance'), ('强攻', 'Assault'), ('飞将', 'Flying General'),
    ('压制', 'Suppress'), ('重创', 'Devastate'), ('威摄', 'Intimidate'), ('衰弱', 'Weaken'),
    ('定身', 'Immobilize'), ('眩晕', 'Stun'), ('沉默', 'Silence'), ('缴械', 'Disarm'),
    ('绊马', 'Leg Bind'), ('摔马', 'Unmount'), ('致残', 'Cripple'), ('暴击', 'Crit'), ('破阵', 'Formation Break'),
    ('剑罡·御心', 'Sword Aura: Mind Guard'), ('御心', 'Mind Guard'), ('追风', 'Windchase'), ('剑落·弑', 'Sword Fall: Slay'),
    ('风阵', 'Wind Formation'), ('官印', 'Official Seal'),
    ('中级效果', 'Mid-tier effect'), ('高级效果', 'High-tier effect'),
    ('骁勇', 'Valor'), ('坚阵', 'Steadfast Formation'), ('仁威', 'Benevolent Might'), ('强兵', 'Strong Arms'),
    ('命中提升', 'Hit Boost'), ('体质', 'Constitution'),
    ('薛综', 'Xue Zong'), ('荀彧', 'Xun Yu'), ('士燮', 'Shi Xie'), ('虎豹骑', 'Tiger and Leopard Cavalry'),
    ('伤类专精', 'Wound Mastery'), ('力类专精', 'Power Mastery'), ('影类专精', 'Shadow Mastery'), ('怒类专精', 'Rage Mastery'),
    ('技类专精', 'Technique Mastery'), ('破类专精', 'Break Mastery'), ('舞类专精', 'Dance Mastery'),
    ('基础招式', 'Basic Move'), ('进阶招式', 'Advanced Move'), ('高阶招式', 'High-Level Move'),
    ('技能类别', 'Skill Class'), ('技能品质', 'Skill Grade'), ('学习需求', 'Learn Requirement'), ('学习等级需求', 'Learn Level Requirement'),
    ('技能生效祖籍限制', 'Heritage Restriction'), ('祖籍', 'Heritage'), ('属性', 'Attribute'), ('被动', 'Passive'),
    ('魂技类型', 'Soul Skill Type'), ('魂技效果', 'Soul Skill Effect'), ('攻击类', 'Offense'), ('护佑类', 'Guard'),
    ('战车专用', 'Chariot Only'), ('特效', 'Special Effect'), ('命中修正', 'Hit Modifier'),
    ('交州', 'Jiao Prefecture'), ('豫州', 'Yu Prefecture'), ('司隶', 'Sili'),
    ('近程', 'Melee'), ('远程', 'Ranged'),
    ('勇猛系', 'Valor Line'), ('灵活系', 'Agility Line'), ('智慧系', 'Wisdom Line'), ('专注系', 'Focus Line'),
    ('壹', 'I'), ('贰', 'II'), ('叁', 'III'), ('肆', 'IV'), ('伍', 'V'),
    # stat labels
    ('结义兵法', 'Sworn Brotherhood Tactic'), ('兵法', 'War Tactic'), ('兵器', 'Weapon'), ('武技', 'Martial Art'),
    ('招式', 'Move'), ('策略', 'Tactic'), ('骑术', 'Mounted'), ('专精', 'Mastery'),
    ('瞬发', 'Instant'), ('出招', 'Execute'), ('准备', 'Prep'), ('激活', 'Activate'),
    ('冷却时间', 'Cool-down'), ('初始冷却', 'Initial Cool-down'), ('冷却', 'Cool-down'),
    ('持续时间', 'Duration'), ('消耗', 'Cost'), ('体力', 'Stamina'), ('斗气', 'Battle Qi'),
    ('基本准备时间等同攻速', 'Base wind-up time equals attack speed'),
    ('纵横天下', 'Conquer the World'),
    ('立即出招', 'Instant Cast'),
    ('不多于', 'no more than'),
    ('不少于', 'no less than'),
    ('持续', 'Duration'),
    # weapon names (only remaining after skill names translated)
    ('单手近战兵器', 'One-Handed Melee Weapon'), ('近战兵器', 'Melee Weapon'), ('不限', 'Any'), ('法器', 'Focus'),
    ('环', 'Ring Blade'), ('杖', 'Staff'), ('舞', 'Dance'), ('扇', 'Fan'), ('弓', 'Bow'), ('鞭', 'Whip'), ('弩', 'Crossbow'),
    ('爪', 'Claws'), ('刀', 'Saber'), ('剑', 'Sword'), ('戟', 'Halberd'), ('钺', 'Battleaxe'),
    ('斧', 'Axe'), ('枪', 'Spear'), ('锤', 'Hammer'), ('钩', 'Hook'), ('叉', 'Trident'),
]
NAMES = sorted(NAMES_LIST, key=lambda x: -len(x[0]))

# RX: regexes for numeric+unit bindings (padding-safe). Applied after NAMES.
RX = [
    (re.compile(r'等级\s*%d'), 'Level %d'),
    (re.compile(r'等级(\d+)'), r'Level \1'),
    (re.compile(r'英雄(\d+)级'), r'Hero Level \1'),
    (re.compile(r'(\d+)级'), r'Level \1'),
    (re.compile(r'(\d+(?:\.\d+)?)分钟'), r'\1 min'),
    (re.compile(r'(\d+(?:\.\d+)?)分'), r'\1 min'),
    (re.compile(r'(\d+(?:\.\d+)?)秒'), r'\1 sec'),
    (re.compile(r'(\d+(?:\.\d+)?)米/秒'), r'\1 m/s'),
    (re.compile(r'(\d+(?:\.\d+)?)米'), r'\1 m'),
    (re.compile(r'体力(\d+)点'), r'Stamina \1 pts'),
    (re.compile(r'(\d+)点'), r'\1 pts'),
    (re.compile(r'(\d+)层'), r'\1 stacks'),
    (re.compile(r'(\d+)名敌人'), r'\1 enemies'),
    (re.compile(r'(\d+)个敌人'), r'\1 enemies'),
    (re.compile(r'(\d+)人'), r'\1 enemies'),
    (re.compile(r'(\d+)(Stamina|Battle Qi)'), r'\1 \2'),
    (re.compile(r'([a-z])(\d)'), r'\1 \2'),
]

# PUNCT: applied last.
PUNCT = [
    ('。', '. '), ('，', ', '), ('：', ': '), ('、', ', '), ('；', '; '),
    ('（', '('), ('）', ')'),
]
