import fs from 'node:fs';

const T = [];
const push = (v) => T.push(v);

push(" 0: Physical Attack");
push(" 1: Physical Attack Cap");
push(" 2: Physical Attack (%)");
push(" 3: Magic Attack");
push(" 4: Magic Attack Cap");
push(" 5: Magic Attack (%)");
push(" 6: +PDef-PAtk");
push(" 7: +PAtk-PDef");
push(" 8: +MAtk-MDef");
push(" 9: Attack Speed");
push("/*  Element Bonus Attribute Table");
push("//  0: Physical Attack");
push("//  1: Physical Attack Cap");
push("//  2: Physical Attack (%)");
push("//  3: Magic Attack");
push("//  4: Magic Attack Cap");
push("//  5: Magic Attack (%)");
push("//  6: +PDef-PAtk");
push("//  7: +PAtk-PDef");
push("//  8: +MAtk-MDef");
push("//  9: Attack Speed");
push("//  Zone ID 4D Scenario 01");
push("//  Zone ID Qixi Festival");
push("//  Zone ID Seven Star Lake");
push("//  Zone ID Central Army Camp");
push("//  Zone ID Legend of the Immortals");
push("//  Zone ID Guanzhong");
push("//  Zone ID Legend of Dian Wei");
push("//  Zone ID Legion Base 1");
push("//  Zone ID Legion Base 2");
push("//  Zone ID Legion Base 3");
push("//  Zone ID Legion Base 4");
push("//  Zone ID Fengming Mountain");
push("//  Zone ID Huarong Pass");
push("//  Zone ID Lone Rider Saves the Lord");
push("//  Zone ID Southern Barbarians");
push("//  Zone ID Wolong Ascends the Nine Heavens");
push("//  Zone ID Wolong Ascends the Nine Heavens-Boss");
push("//  Zone ID Battle of Hefei");
push("//  Zone ID Jianye, Wu Capital");
push("//  Zone ID National Quest");
push("//  Zone ID Nation War Test Battlefield");
push("//  Zone ID Side Story 03 Legend of Liu Bei");
push("//  Zone ID Side Story 04 Legend of Cao Cao");
push("//  Zone ID Side Story PVE30");
push("//  Zone ID Side Story PVE55");
push("//  Zone ID Battle of Yiling");
push("//  Zone ID Surprise Battle Surprise Battle Battlefield");
push("//  Zone ID Ziwu Valley");
push("//  Zone ID Legend of Sun Quan");
push("//  Zone ID Battle of Guandu");
push("//  Zone ID Mount Dingjun");
push("//  Zone ID Bashu");
push("//  Zone ID Illusory Eight Formations 1");
push("//  Zone ID Illusory Eight Formations 2");
push("//  Zone ID Illusory Eight Formations 3");
push("//  Zone ID Illusory Eight Formations 4");
push("//  Zone ID Illusory Eight Formations 5");
push("//  Zone ID Crossing the River with the People");
push("//  Zone ID Tournament Season 1 1");
push("//  Zone ID Tournament Season 1 2");
push("//  Zone ID Tournament Season 1 3");
push("//  Zone ID Tournament Season 1 4");
push("//  Zone ID Tournament Season 1 5");
push("//  Zone ID Tournament Season 1 6");
push("//  Zone ID Tournament Season 1 7");
push("//  Zone ID Tournament Lightweight 1");
push("//  Zone ID Tournament Lightweight 2");
push("//  Zone ID Tournament Lightweight 3");
push("//  Zone ID Tournament Lightweight 4");
push("//  Zone ID Tournament Lightweight 5");
push("//  Zone ID Tournament Lightweight 6");
push("//  Zone ID Tournament Lightweight 7");
push("//  Zone ID Tournament Lightweight 8");
push("//  Zone ID Novice Village");
push("//  Zone ID New Wushuang 07");
push("//  Zone ID Wushuang2PVE25");
push("//  Zone ID Wushuang2PVE25-Boss1");
push("//  Zone ID Wushuang2PVE25-Boss2");
push("//  Zone ID Wushuang2PVE25-Boss3");
push("//  Zone ID Wushuang3PVE60");
push("//  Zone ID Wushuang3PVE60-Boss1");
push("//  Zone ID Wushuang3PVE60-Boss2");
push("//  Zone ID Wushuang3PVE60-Boss3");
push("//  Zone ID Wushuang3PVE60-Boss4");
push("//  Zone ID Wushuang3PVE60-Boss5");
push("//  Zone ID WushuangPVE60");
push("//  Zone ID WushuangPVE60-Boss1");
push("//  Zone ID WushuangPVE60-Boss2");
push("//  Zone ID WushuangPVE60-Boss3");
push("//  Zone ID WushuangPVE60-Boss4");
push("//  Zone ID WushuangPVE60-Boss5");
push("//  Zone ID Free-for-All Training Ground");
push("//  Zone ID Legend of Cao Zhi");
push("//  Zone ID Loulan Ancient Palace");
push("//  Zone ID Loulan Ancient Palace-Boss1");
push("//  Zone ID Loulan Ancient Palace-Boss2");
push("//  Zone ID Loulan Ancient Palace-Boss3");
push("//  Zone ID Loulan Ancient Palace-Boss4");
push("//  Zone ID Loulan Ancient Palace-Boss5");
push("//  Zone ID Loulan Sand Sea");
push("//  Zone ID Snowfield of the Fallen");
push("//  Zone ID Jiangnan");
push("//  Zone ID Hebei");
push("//  Zone ID Testb9");
push("//  Zone ID Testz13");
push("//  Zone ID Test Scene 1");
push("//  Zone ID Test Scene 2");
push("//  Zone ID Test Scene 3");
push("//  Zone ID Yanyi15PVE-Boss3");
push("//  Zone ID Yanyi15PVE-Boss4");
push("//  Zone ID Yanyi15PVE-Boss5");
push("//  Zone ID Battle of Puyang PVP");
push("//  Zone ID Battle of Puyang PVP-2-1");
push("//  Zone ID Battle of Puyang PVP-2-1b (Prep Only)");
push("//  Zone ID Battle of Puyang PVP-2-2");
push("//  Zone ID Battle of Puyang PVP-2-2b (Prep Only)");
push("//  Zone ID Battle of Puyang PVP-2-3");
push("//  Zone ID Battle of Puyang PVP-2-3b (Prep Only)");
push("//  Zone ID Battle of Puyang PVP-2-4");
push("//  Zone ID Battle of Puyang PVP-2-4b (Prep Only)");
push("//  Zone ID Battle of Puyang PVP-2-5");
push("//  Zone ID Battle of Puyang PVP-2-5b (Prep Only)");
push("//  Zone ID Battle of Puyang (Hero Tier)");
push("//  Zone ID Spirit Mountain Secret Path");
push("//  Zone ID Remnant Fragrance Valley");
push("//  Zone ID White Emperor City");
push("//  Zone ID Battle of Yizhou");
push("//  Zone ID Arena 12 Players");
push("//  Zone ID Arena 1 Player");
push("//  Zone ID Arena Hero Battle 1");
push("//  Zone ID Arena Hero Battle 2");
push("//  Zone ID Arena Hero Battle 3");
push("//  Zone ID Arena Hero Battle 4");
push("//  Zone ID Arena Hero Battle 5");
push("//  Zone ID Martial Arts Ground");
push("//  Zone ID Free Practice Ground");
push("//  Zone ID Jingxiang");
push("//  Zone ID Battle of Luofeng Slope PVE50");
push("//  Zone ID Jiang Gan Steals the Book");
push("//  Zone ID Hanzhong, Shu Capital");
push("//  Zone ID Xiliang");
push("//  Zone ID Mirage City of the Western Regions");
push("//  Zone ID Side Story of Diao Chan");
push("//  Zone ID Racecourse");
push("//  Zone ID Legend of Zhao Yun");
push("//  Zone ID Trade Run");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 10");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 11");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 3");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 4");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 5");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 6");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 7");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 8");
push("//  Zone ID Cross-Server Arena • Cross-Server Match Line 9");
push("//  Zone ID Cross-Server Arena • Qualifier Line 3");
push("//  Zone ID Cross-Server Arena • Qualifier Line 4");
push("//  Zone ID Cross-Server Arena • Qualifier Line 5");
push("//  Zone ID Cross-Server Arena • Qualifier Line 6");
push("//  Zone ID Cross-Server Arena • Qualifier Line 7");
push("//  Zone ID Cross-Server Arena • Qualifier Line 8");
push("//  Zone ID Cross-Server Arena Training Ground");
push("//  Zone ID Xuanyuan Ruins");
push("//  Zone ID Xuanyuan Ruins-Boss1");
push("//  Zone ID Xuanyuan Ruins-Boss2");
push("//  Zone ID Xuanyuan Ruins-Boss3");
push("//  Zone ID Xuanyuan Ruins-Boss4");
push("//  Zone ID Xuanyuan Ruins-Boss5");
push("//  Zone ID Through Passes and Slay Generals 1");
push("//  Zone ID Through Passes and Slay Generals 10");
push("//  Zone ID Through Passes and Slay Generals 2");
push("//  Zone ID Through Passes and Slay Generals 3");
push("//  Zone ID Through Passes and Slay Generals 4");
push("//  Zone ID Through Passes and Slay Generals 5");
push("//  Zone ID Through Passes and Slay Generals 6");
push("//  Zone ID Through Passes and Slay Generals 7");
push("//  Zone ID Through Passes and Slay Generals 8");
push("//  Zone ID Through Passes and Slay Generals 9");
push("//  Zone ID Maze Flower Rainforest");
push("//  Zone ID Xiaoyao Ford");
push("//  Zone ID Common Treasure Hunt");
push("//  Zone ID Xiang Yu Demon Realm");
push("//  Zone ID Xiang Yu Demon Realm-Boss1");
push("//  Zone ID Xiang Yu Demon Realm-Boss2");
push("//  Zone ID Xiang Yu Demon Realm-Boss3");
push("//  Zone ID Xiang Yu Demon Realm-Boss4");
push("//  Zone ID Xiang Yu Demon Realm-Boss5");
push("//  Zone ID Battle of Yingchuan PVE20");
push("//  Zone ID Battle of Yingchuan PVE40");
push("//  Zone ID Battle of Yingchuan PVE60");
push("//  Zone ID Battle of Yingchuan PVP");
push("//  Zone ID Mounted Combat Tutorial 1");
push("//  Zone ID Mounted Combat Tutorial 2");
push("//  Zone ID Mounted Combat Tutorial 3");
push("//  Zone ID Mounted Combat Tutorial 4");
push("//  Zone ID Mounted Combat Tutorial 5");
push("//  Zone ID Legend of Ma Chao - Revenge at Tong Pass");
push("//  Zone ID Legend of Ma Chao\u00cd\u0140\u0166Capturing Cao Cao");
push("//  Zone ID Nightmare Soul Cave");
push("//  Zone ID Xuchang, Wei Capital");
push("//  Zone ID Battle of Maicheng");
push("//  Zone IDYanyi15PVE-Boss1");
push("//  Zone IDYanyi15PVE-Boss2");
push("// 10: Attack Range");
push("// 11: Cast Time");
push("// 12: Physical Defense");
push("// 13: Physical Defense (%)");
push("// 14: Five Elements Defense");
push("// 15: Metal Defense");
push("// 16: Metal Defense (%)");
push("// 17: Wood Defense");
push("// 18: Wood Defense (%)");
push("// 19: Water Defense");
push("// 20: Water Defense (%)");
push("// 21: Fire Defense");
push("// 22: Fire Defense (%)");
push("// 23: Earth Defense");
push("// 24: Earth Defense (%)");
push("// 25: +Metal Def (%)-Fire Def (%)");
push("// 26: +Wood Def (%)-Metal Def (%)");
push("// 27: +Water Def (%)-Earth Def (%)");
push("// 28: +Fire Def (%)-Water Def (%)");
push("// 29: +Earth Def (%)-Wood Def (%)");
push("// 30: +Metal Def-Fire Def");
push("// 31: +Wood Def-Metal Def");
push("// 32: +Water Def-Earth Def");
push("// 33: +Fire Def-Water Def");
push("// 34: +Earth Def-Wood Def");
push("// 39: HP Recovery Speed");
push("// 40: MP Recovery Speed");
push("// 41: Strength");
push("// 42: Agility");
push("// 43: Spirit Power");
push("// 44: Vitality");
push("// 45: Critical Hit Rate");
push("// 46: Accuracy");
push("// 47: Accuracy (%)");
push("// 48: Movement Speed");
push("// 49: Movement Speed (%)");
push("// 50: Evasion");
push("// 51: Evasion (%)");
push("// 52: Durability");
push("// 53: Durability (%)");
push("// 54: Physical Immunity");
push("// 55: Bonus Skill");
push("// 56: Equipment Requirement");
push("// 57: Unknown Attribute");
push("// 58: EXP Bonus");
push("//Status Pack Resource");
push("10: Attack Range");
push("11: Cast Time");
push("12: Physical Defense");
push("13: Physical Defense (%)");
push("14: Five Elements Defense");
push("15: Metal Defense");
push("16: Metal Defense (%)");
push("17: Wood Defense");
push("18: Wood Defense (%)");
push("19: Water Defense");
push("20: Water Defense (%)");
push("21: Fire Defense");
push("22: Fire Defense (%)");
push("23: Earth Defense");
push("24: Earth Defense (%)");
push("2553 is standard Destruction<CRLF>2554 is enhanced Destruction (\uff08Defense Destruction effect +50%\uff09)");
push("25: +Metal Def (%)-Fire Def (%)");
push("26: +Wood Def (%)-Metal Def (%)");
push("27: +Water Def (%)-Earth Def (%)");
push("28: +Fire Def (%)-Water Def (%)");
push("29: +Earth Def (%)-Wood Def (%)");
push("30: +Metal Def-Fire Def");
push("31: +Wood Def-Metal Def");
push("32: +Water Def-Earth Def");
push("33: +Fire Def-Water Def");
push("34: +Earth Def-Wood Def");
push("39: HP Recovery Speed");
push("40: MP Recovery Speed");
push("41: Strength");
push("42: Agility");
push("43: Spirit Power");
push("44: Vitality");
push("45: Critical Hit Rate");
push("46: Accuracy");
push("47: Accuracy (%)");
push("48: Movement Speed");
push("49: Movement Speed (%)");
push("4D Scenario 01");
push("50: Evasion");
push("51: Evasion (%)");
push("52: Durability");
push("53: Durability (%)");
push("54: Physical Immunity");
push("55: Bonus Skill");
push("56: Equipment Requirement");
push("57: Unknown Attribute");
push("58: EXP Bonus");
push("Five minutes have passed, and the male roe buck is at peace.<CRLF>At this very moment,<CRLF>if the doe is still alive, you will receive the \u201cHunt and Release\u201d reward.<CRLF>If the doe has died as well, you will only get two pieces of roe venison.");
push("GM Reset Cooldown 1");
push("GM Reset Cooldown 3");
push("PVE Scenario Event 04 Chariot Test Drive");
push("PVP Battlefield 2-1");
push("PVP Battlefield 2-2");
push("PVP Battlefield 2-3");
push("PVP Battlefield 2-4");
push("PVP Battlefield 2-5");
push("PVP Chariot Battlefield 1");
push("PVP Chariot Battlefield 10");
push("PVP Chariot Battlefield 2");
push("PVP Chariot Battlefield 3");
push("PVP Chariot Battlefield 4");
push("PVP Chariot Battlefield 5");
push("PVP Chariot Battlefield 6");
push("PVP Chariot Battlefield 7");
push("PVP Chariot Battlefield 8");
push("PVP Chariot Battlefield 9");
push("^c3dbffGM Boost Injectant<CRLF><CRLF>^ffffffLegend says only world peacekeepers may use this.");
push("^c3dbffVIP<CRLF>Today is my birthday!");
push("^c3dbff\u3010Veteran Player Medal\u3011<CRLF><CRLF>^ffffffReturn triumphantly to Chibi and rid the people of evil!<CRLF>Attack Power +30<CRLF>Defense +30<CRLF>Constitution +1000<CRLF>Training and Experience gains increased.");
push("^c3dbffUnder One Command<CRLF><CRLF>^ffffffHigh rewards will be awarded!");
push("^c3dbffSword Through the Wind<CRLF><CRLF>^ffffffDamage resistance greatly increased");
push("^c3dbffDone in One Stroke<CRLF><CRLF>^ffffffFluid, flowing combat on the battlefield.<CRLF>Grants a short-lived boost when switching between mounted and foot combat.");
push("^c3dbffDone in One Stroke<CRLF><CRLF>^ffffffFluid, flowing combat on the battlefield.<CRLF>Grants a short-lived boost when switching between mounted and foot combat.<CRLF>For 8 seconds, direct resistance and control resistance increase, and Attack Power rises with Fighting Spirit.");
push("^c3dbffDrink Till the End<CRLF><CRLF>^ffffffSomeone has filled your empty wine bowl with fine wine!<CRLF>Long live the single life! To freedom, cheers!");
push("^c3dbffOne Dragon<CRLF><CRLF>^ffffffIndirect resistance increased");
push("^c3dbffDing<CRLF>^ffffffGo attack the Wooden Dummy - guess.");
push("^c3dbffDing<CRLF>^ffffffFears players in the Shelled state.");
push("^c3dbffSeven Stars<CRLF><CRLF>^ffffffSeven Star Formation activated, Max HP increased");
push("^c3dbffSeven Steps Poem<CRLF><CRLF>^ffffffUse the Seven Steps Poem from your bag on Cao Pi within 5 seconds,<CRLF>or you will die");
push("^c3dbffSeven Steps Poem<CRLF><CRLF>^ffffffUse the Seven Steps Poem from your bag on a player within 5 seconds,<CRLF>or you will die");
push("^c3dbffSeven Steps Poem<CRLF><CRLF>^ffffffCao Pi dealt a blow to Cao Zhi");
push("^c3dbffPine Wind in Myriad Valleys<CRLF><CRLF>Critical Hit increased");
push("^c3dbffMyriad Venoms Attack the Heart<CRLF>^ffffffCorrupted by the Mulu Gu poison, your movement direction is completely reversed. Enter the Antidote Zone to clear the deadly poison.");
push("^c3dbffThree Laments<CRLF><CRLF>^ffffffHealing effect increased");
push("^c3dbffDeliberation<CRLF><CRLF>^ffffffWhen hit, has a chance to gain one of Balance,<CRLF>Chain Evasion, or Solid Shield.");
push("^c3dbffThree Strategies<CRLF><CRLF>^ffffffThis book can be read in a safe zone, granting a certain amount of Military Merit every 5 minutes.");
push("^c3dbffIt's Snowing<CRLF><CRLF>^ffffffMerry Christmas!");
push("^c3dbffUnfalling<CRLF><CRLF>^ffffffImmune to the vast majority of damage");
push("^c3dbffStillness<CRLF><CRLF>^ffffffReduces the effects of earthquake weather.");
push("^c3dbffStillness<CRLF><CRLF>^ffffffReduces the impact of earthquake weather");
push("^c3dbffImmovable Honor<CRLF><CRLF>^ffffffConverts part of your Attack Power into Defense and Critical Resistance.");
push("^c3dbffInviolable<CRLF><CRLF>^ffffffEvery attack from an attacker is slowed");
push("^c3dbffInviolable<CRLF><CRLF>^ffffffEach time you are attacked, you gain 1 point of Rage");
push("^c3dbffBad Omen<CRLF><CRLF>^ffffffInstant Death");
push("^c3dbffUnyielding<CRLF><CRLF>^ffffffFinal indirect damage taken is reduced");
push("^c3dbffUnyielding!<CRLF><CRLF>^ffffffThe character gains 10 points of direct and indirect resistance,<CRLF>and the effect ends when HP is above 50%.");
push("^c3dbffImpure Zeal<CRLF><CRLF>^ffffffTrade the inability to be healed for a large increase in Attack Power");
push("^c3dbffUnblinking Eye<CRLF><CRLF>^ffffffA skill honed over long years of fishing training,<CRLF>developed with immense focus and endurance,<CRLF>that grants 5% Max HP and 5 Accuracy.");
push("^c3dbffKarmic Fire Weather<CRLF><CRLF>^ffffffHP drains continuously.");
push("^c3dbffEast Outpost Reward<CRLF><CRLF>^ffffffElite Cavalry Token issued");
push("^c3dbffWeapon Lost<CRLF><CRLF>^ffffffYour weapon is lost. You cannot attack targets.");
push("^c3dbffSevere Collapse<CRLF><CRLF>^ffffffDefense greatly reduced.");
push("^c3dbffHit by an Egg<CRLF><CRLF>^ffffffYou were just hit by an egg!");
push("^c3dbffCentral Outpost Reward<CRLF><CRLF>^ffffffElite Cavalry Token issued");
push("^c3dbffCentral Arrow Tower Destroyed<CRLF><CRLF>^ffffffReward issued");
push("^c3dbffPoisoned<CRLF><CRLF>^ffffffYou are poisoned. Movement Speed has decreased.");
push("^c3dbffPoisoned<CRLF><CRLF>^ffffffHP drains continuously.");
push("^c3dbffPoisoned<CRLF>^ffffffYou are poisoned. What happens when Zhang Jiao sucks out your poisoned blood?");
push("^c3dbffPoisoned<CRLF>^ffffffCorroded by poison gas.");
push("^c3dbffMedium Difficulty<CRLF>^ffffffRecommended for Heroes level 31-47");
push("^c3dbffArrow Hit<CRLF><CRLF>^ffffffAn arrow struck the scarecrow's knee. Remember to collect it in time.");
push("^c3dbffCalled at a Critical Moment<CRLF><CRLF>^ffffffA truly loyal minister!!!");
push("^c3dbffCalled at a Critical Moment<CRLF>^ffffffIt seems only you can wipe out the raiding bandits in time!.");
push("^c3dbffFatigue<CRLF><CRLF>^ffffffYour arms are weakening,<CRLF>chance of rooting and interrupt immunity reduced by 30%.");
push("^c3dbffFatigue<CRLF><CRLF>^ffffffAttack Power reduced.");
push("^c3dbffBattle Fatigue<CRLF><CRLF>Critical bonus damage reduced");
push("^c3dbffHelpful<CRLF>^ffffffWhile taking part in the Legend of Huang Zhong,<CRLF>if more than 2 players in the party are below Hero level 48,<CRLF>you will receive the Unity<CRLF>and Mutual Aid award.");
push("^c3dbffBenevolence<CRLF><CRLF>^ffffffHP regenerates continuously");
push("^c3dbffPursue the Victorious<CRLF>^ffffffThe Strategist must already know our fortifications have been destroyed. Reinforcements will arrive soon!");
push("^c3dbffNine Swords<CRLF><CRLF>^ffffffCountless sword energies whirl around you, striking in circles, leaving no energy for other attacks");
push("^c3dbffJiu Tian Piggy's Blessing<CRLF><CRLF>^ffffffAttack Power, Attack Strength, Critical Hit, Max HP, and Healing increased");
push("^c3dbffNine Heavens Divine Thunder<CRLF><CRLF>^ffffffAn ancient arcane art. Those struck cannot move and can barely attack.");
push("^c3dbffNine Mysterious Soul Chaos Curse<CRLF><CRLF>^ffffffSoul chaos. Energy drains rapidly. Attack increased.");
push("^c3dbffChaotic Blade<CRLF><CRLF>^ffffffMax targets of AoE skills increased by 2");
push("^c3dbffChaotic Heart<CRLF><CRLF>^ffffffEach hit lowers your own Attack Power.");
push("^c3dbffChaotic Heart<CRLF>^ffffffDisturbed by flame");
push("^c3dbffFeathers Blind the Eyes<CRLF><CRLF>^ffffffAccuracy decreased.");
push("^c3dbffWild Dance<CRLF><CRLF>^ffffffAttack Speed increased");
push("^c3dbffWild Dance Art<CRLF><CRLF>^ffffffA combat art used by generals who wield hammers<CRLF>When activated, dual-hammer attacks gain Wild Dance points");
push("^c3dbffWild Dance Points<CRLF><CRLF>^ffffffMovement Speed and Melee Attack Speed increased<CRLF>Some hammer moves are enhanced<CRLF>Accumulates up to 10 points");
push("^c3dbffHeavenly Firmament Energy<CRLF><CRLF>Bonus damage increased");
push("^c3dbffAspiration to Wander<CRLF><CRLF>^ffffffZuo Ci is about to set out on a journey.");
push("^c3dbffWuzhang Plain Fighting Soldiers<CRLF><CRLF>");
push("^c3dbffBenevolence<CRLF><CRLF>^ffffffWin the world through benevolence. Recovers 2% HP every 3 seconds.");
push("^c3dbffBenevolence<CRLF><CRLF>^ffffffWhen hit, has a chance to gain the People's Heart state.");
push("^c3dbffBenevolence<CRLF><CRLF>^ffffffHealing received is increased");
push("^c3dbffLatent Hatred<CRLF><CRLF>^ffffffYour hatred for the enemy lies deep in your heart and will erupt at the right moment");
push("^c3dbffImmortal Talent<CRLF><CRLF>^ffffffHitting a target can trigger the Sudden Wit state.");
push("^c3dbffImmortal Fruit<CRLF><CRLF>^ffffffIncreases HP and Defense.");
push("^c3dbffImmortal Wine<CRLF><CRLF>^ffffffIncreases HP and Attack.");
push("^c3dbffAwait the Exhausted Enemy<CRLF><CRLF>Reduces damage taken");
push("^c3dbffRest<CRLF><CRLF>^ffffffAfter a period out of combat, Vitality recovery speed increases.");
push("^c3dbffRest<CRLF><CRLF>^ffffffThis unit is in the Resting state. Both Vitality recovery speed<CRLF>and the recovery effect of food are enhanced.<CRLF>The Resting state is cancelled when attacked or damaged.");
push("^c3dbffInsight<CRLF><CRLF>^ffffffCritical Hit chance increased<CRLF>");
push("^c3dbffInsight<CRLF><CRLF>^ffffffCritical Hit chance increased.");
push("^c3dbffTeleport Protection<CRLF><CRLF>^ffffffAttack doubled, Defense increased by half. Nothing can stop you!<CRLF>");
push("^c3dbffPassing<CRLF><CRLF>^ffffffDamage taken is reduced.");
push("^c3dbffFeint to Strike<CRLF><CRLF>^ffffffEvasion and indirect resistance increased.");
push("^c3dbffFalse Report");
push("^c3dbffDisguise<CRLF><CRLF>^ffffffYou have turned into a wooden dummy,<CRLF>and cannot move freely.");
push("^c3dbffDisguise<CRLF><CRLF>^ffffffWith your face concealed, you look just like Yue He,<CRLF>and no one will spot the flaw for a short time.");
push("^c3dbffShield of Vitality<CRLF><CRLF>^ffffffEvery point of Vitality blocks 5 points of damage");
push("^c3dbffMax Vitality increased");
push("^c3dbffMax Vitality decreased");
push("^c3dbffVitality recovery speed increased");
push("^c3dbffVitality recovery speed decreased");
push("^c3dbffVitality Shield<CRLF><CRLF>^ffffffAbsorbs damage.");
push("^c3dbffAfterwave<CRLF><CRLF>^ffffffStun, slow, and reduced direct damage");
push("^c3dbffLingering Melody<CRLF><CRLF>^ffffffA Christmas tune whose echoes linger.<CRLF>Hearing it lifts the spirit and raises the Vitality cap<CRLF><CRLF>");
push("^c3dbffYou have earned the gratitude of the Guardian of Luoyang!");
push("^c3dbffYou obtained the Chicken Feather Letter hidden beneath the Great Messenger Bird's wings!");
push("^c3dbffFine Wine<CRLF><CRLF>^ffffffRestores Fighting Spirit for each monster killed.<CRLF>Only one drink effect can be active at a time.");
push("^c3dbffTo His Advantage<CRLF><CRLF>^ffffffDodge all hits of Sky Net and Earth Trap");
push("^c3dbffScout<CRLF><CRLF>^ffffffThe target is revealed because its HP is below 20%,<CRLF>and direct and indirect resistance decrease.");
push("^c3dbffOnslaught<CRLF><CRLF>^ffffffYour body feels slightly off.");
push("^c3dbffDefender!<CRLF><CRLF>^ffffffSuccessfully stopped a group of Cao Ren's troops from escaping in Xu Shu's Stratagem room");
push("^c3dbffConditioning<CRLF><CRLF>^ffffffSlowly restores mount stamina.");
push("^c3dbffKnocked Down<CRLF><CRLF>^ffffffStaggered by a heavy blow. Unable to move or attack,<CRLF>direct resistance decreases.");
push("^c3dbffBacked by Heaven<CRLF><CRLF>^ffffffHealing received is reduced");
push("^c3dbffNation Toppling<CRLF><CRLF>^ffffffCritical Hit damage greatly increased.");
push("^c3dbffOverwhelming Beauty<CRLF><CRLF>^ffffffGains a boost each time you hit an enemy.");
push("^c3dbffNation Toppling Exhaustion<CRLF><CRLF>^ffffffToo much energy has been spent. You need to<CRLF>rest and cannot concentrate at the moment.");
push("^c3dbffCity Toppling<CRLF><CRLF>^ffffffCritical Hit damage increased.");
push("^c3dbffLieutenant Defeated<CRLF><CRLF>^ffffffReward issued");
push("^c3dbffBody Toning Art<CRLF><CRLF>Constitution increased");
push("^c3dbffFirst Strike<CRLF><CRLF>^ffffffTriggers the First Strike state, allowing you to use<CRLF>the First Strike Rush combo within 2 seconds.");
push("^c3dbffBlinding Light<CRLF><CRLF>^ffffffYou are bathed in intense light. Your next three attacks are enhanced");
push("^c3dbffRestraint<CRLF><CRLF>^ffffffAfter stacking 3 times, you will be dismounted.");
push("^c3dbffOverwhelm<CRLF><CRLF>^ffffffIncreases the number of targets hit by Daring Assault.");
push("^c3dbffImmunity<CRLF><CRLF>^ffffffYou are immune to spike trap damage.<CRLF>");
push("^c3dbffImmune State<CRLF><CRLF>^ffffffImmune to debuffs.");
push("^c3dbffImmune Restriction<CRLF><CRLF>^ffffffImmune to restriction effects.");
push("^c3dbffLord Rabbit submits!<CRLF><CRLF>^ffffffYour martial skill is truly unmatched!<CRLF>Lord Rabbit concedes to you!<CRLF>");

const src = fs.readFileSync(new URL('./in/batch_000.jsonl', import.meta.url), 'utf8')
  .split(/\r?\n/)
  .filter((l) => l.trim().length > 0);

if (T.length !== src.length) {
  console.error('TRANSLATION COUNT MISMATCH: expected ' + src.length + ', got ' + T.length);
  process.exit(1);
}

const out = [];
for (let i = 0; i < src.length; i++) {
  const rec = JSON.parse(src[i]);
  out.push(JSON.stringify({ id: rec.id, english: T[i] }));
}
fs.writeFileSync(new URL('./out/batch_000.jsonl', import.meta.url), out.join('\n') + '\n', 'utf8');
console.log('OK, wrote ' + out.length + ' records');
