#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const inPath = '/Users/zlns/personal-www/pck-translate/.work/tr/in/batch_008.jsonl';
const outPath = '/Users/zlns/personal-www/pck-translate/.work/tr/out/batch_008.jsonl';

// Load existing translations from other batches
const outDir = '/Users/zlns/personal-www/pck-translate/.work/tr/out';
const priorMap = new Map();
try {
  const files = fs.readdirSync(outDir).filter(f => f.endsWith('.jsonl') && f !== 'batch_008.jsonl');
  for (const f of files) {
    const content = fs.readFileSync(path.join(outDir, f), 'utf8');
    const lines = content.split(/\r?\n/).filter(l => l.trim());
    for (const line of lines) {
      try {
        const obj = JSON.parse(line);
        if (obj.source && obj.english) priorMap.set(obj.source, obj.english);
      } catch (e) {}
    }
  }
} catch (e) {}

// Load glossary
const glossaryMap = new Map();
try {
  const glossaryPath = '/Users/zlns/personal-www/pck-translate/memory/glossary.db';
  const result = execSync(`sqlite3 "${glossaryPath}" "SELECT source||'\\t'||english FROM terms;"`, {encoding: 'utf8'});
  const lines = result.split(/\r?\n/).filter(l => l.trim());
  for (const line of lines) {
    const idx = line.indexOf('\t');
    if (idx > 0) {
      const src = line.slice(0, idx);
      const eng = line.slice(idx + 1);
      if (!glossaryMap.has(src)) glossaryMap.set(src, eng);
    }
  }
} catch (e) {}

// Manual translation map for batch_008
const specific = new Map([
  // Lines 1-100
  ['^ffffff测试法系状态<CRLF>^c3dbff法系暴击伤害1点 <CRLF>马匹法系暴击伤害1点<CRLF>法术抗性5 <CRLF>马匹法系抗性5<CRLF>法术伤害减免50点<CRLF>', '^ffffffTest Magic Status<CRLF>^c3dbffMagic Crit Damage 1 pt <CRLF>Horse Magic Crit Damage 1 pt<CRLF>Magic Resistance 5 <CRLF>Horse Magic Resistance 5<CRLF>Magic Damage Reduction 50 pts<CRLF>'],
  ['^ffffff混沌<CRLF>此状态叠加4层后将会立即死亡！<CRLF>请各位速速击打照明灯解除状态！<CRLF>', '^ffffffChaos<CRLF>After 4 stacks, instant death!<CRLF>Everyone attack the lamps quickly to dispel this status!<CRLF>'],
  ['^ffffff生命上限降低', '^ffffffMax HP Reduced'],
  ['^ffffff生命回复<CRLF>', '^ffffffHP Recovery<CRLF>'],
  ['^ffffff生命回复速度为零', '^ffffffHP Recovery Speed Is Zero'],
  ['^ffffff直接伤害抗性降低。', '^ffffffDirect Damage Resistance Reduced.'],
  ['^ffffff箭塔建造升级中，<CRLF>无法进行攻击。', '^ffffffArrow Tower is being built/upgraded.<CRLF>Cannot attack.'],
  ['^ffffff裸衣上阵<CRLF>攻击力防御力大幅提升.', '^ffffffFighting Bare-Chested<CRLF>Attack Power and Defense greatly increased.'],
  ['^ffffff谷内刮风，是策马奔腾的好时机。<CRLF>骑乘速度提升1米/秒', '^ffffffIt is windy in the valley—a fine time for a ride.<CRLF>Mount Speed +1 m/s'],
  ['^ffffff谷内落雨，路滑请小心。<CRLF>移动速度提高1米/秒', '^ffffffIt is raining in the valley. The road is slippery, so take care.<CRLF>Movement Speed +1 m/s'],
  ['^ffffff谷内飘雪，多加些衣服吧。<CRLF>防御提升20点', '^ffffffSnow is falling in the valley. Put on more clothes.<CRLF>Defense +20 pts'],
  ['^ffffff赤壁前哨战结束，你将被传出场景。', '^ffffffThe Chibi Skirmish has ended. You will be teleported out of the scene.'],
  ['^ffffff还未在赤壁大战中获得战功，<CRLF>请和战友们乘船攻打敌国水寨，<CRLF>击杀敌国守将，获取战功！', '^ffffffYou have yet to earn War Merit in the Battle of Red Cliffs.<CRLF>Board the ships with your comrades, attack the enemy naval camp,<CRLF>and defeat enemy guards to earn War Merit!'],
  ['auto_revive // 自动复活', 'auto_revive // Auto Revive'],
  ['auto_revive_time 0 // 自动复活等待时间 （毫秒）', 'auto_revive_time 0 // Auto Revive Wait Time (ms)'],
  ['auto_revive_time 5000 // 自动复活等待时间', 'auto_revive_time 5000 // Auto Revive Wait Time'],
  ['一世陪伴<CRLF>您需要找到一位拥有状态“一生承诺”的异性玩家组队。<CRLF>男方做队长，可在柳小月处领取任务“一生一世”。<CRLF>完成任务可获得大量奖励！', 'Lifelong Companionship<CRLF>You need to find an opposite-sex player with the status "Lifelong Promise" to form a team.<CRLF>The male player should be leader; accept the quest "A Lifetime Together" from Liu Xiaoyue.<CRLF>Complete the quest for great rewards!'],
  ['一生承诺<CRLF>您需要找到一位拥有状态“一世陪伴”的异性玩家组队。<CRLF>男方做队长，可在柳小月处领取任务“一生一世”。<CRLF>完成任务可获得大量奖励！', 'Lifelong Promise<CRLF>You need to find an opposite-sex player with the status "Lifelong Companionship" to form a team.<CRLF>The male player should be leader; accept the quest "A Lifetime Together" from Liu Xiaoyue.<CRLF>Complete the quest for great rewards!'],
  ['七夕', 'Qixi Festival'],
  ['七夕情缘值排行', 'Qixi Romance Value Rankings'],
  ['七擒孟获1', 'Seven Captures of Meng Huo 1'],
  ['七擒孟获2', 'Seven Captures of Meng Huo 2'],
  ['七擒孟获3', 'Seven Captures of Meng Huo 3'],
  ['七擒孟获4', 'Seven Captures of Meng Huo 4'],
  ['七擒孟获5', 'Seven Captures of Meng Huo 5'],
  ['七星湖', 'Seven Star Lake'],
  ['上周击杀排行', "Last Week's Kill Rankings"],
  ['上周吴国军团活跃度', "Last Week Wu Kingdom Legion Activity"],
  ['上周吴国军团资金获得 ', "Last Week Wu Kingdom Legion Funds Earned "],
  ['上周吴国玩家资金获得 ', "Last Week Wu Kingdom Player Funds Earned "],
  ['上周获得名望', "Last Week's Renown Earned"],
  ['上周获得活跃度总榜', "Last Week's Activity Leaderboard"],
  ['上周蜀国军团活跃度', "Last Week Shu Kingdom Legion Activity"],
  ['上周蜀国军团资金获得 ', "Last Week Shu Kingdom Legion Funds Earned "],
  ['上周蜀国玩家资金获得 ', "Last Week Shu Kingdom Player Funds Earned "],
  ['上周魏国军团活跃度', "Last Week Wei Kingdom Legion Activity"],
  ['上周魏国军团资金获得 ', "Last Week Wei Kingdom Legion Funds Earned "],
  ['上周魏国玩家资金获得 ', "Last Week Wei Kingdom Player Funds Earned "],
  ['上月个人竞技经验', "Last Month's Personal Arena EXP"],
  ['上月获得名望', "Last Month's Renown Earned"],
  ['上月获得师德排行', "Last Month's Mentor Virtue Rankings"],
  ['上月获得消费积分排行', "Last Month's Spending Points Rankings"],
  ['下一击必暴', 'Next Hit Guaranteed Crit'],
  ['与快马加鞭完全同步，无实际效果，不会被驱散', 'Fully synchronized with Swift Spur; no actual effect; cannot be dispelled'],
  ['东海', 'Eastern Sea'],
  ['个人击杀排行榜', 'Personal Kill Leaderboard'],
  ['个人势力声望榜', 'Personal Faction Reputation Leaderboard'],
  ['个人地区声望榜', 'Personal Regional Reputation Leaderboard'],
  ['个人战斗力评分', 'Personal Combat Power Score'],
  ['个人战魂评分', 'Personal War Soul Score'],
  ['个人排名：', 'Personal Rank:'],
  ['个人排行榜', 'Personal Leaderboard'],
  ['个人治疗评分', 'Personal Healing Score'],
  ['个人竞技排行榜', 'Personal Arena Leaderboard'],
  ['个人竞技等级', 'Personal Arena Level'],
  ['个人竞技经验', 'Personal Arena EXP'],
  ['个人等级', 'Personal Level'],
  ['个人综合排行榜', 'Personal Overall Leaderboard'],
  ['个人综合评分', 'Personal Overall Score'],
  ['个人防御评分', 'Personal Defense Score'],
  ['个人阵营声望榜', 'Personal Faction Reputation Leaderboard'],
  ['中军大营', 'Central Army Camp'],
  ['中毒了，普通士兵中毒60秒后会死亡。', 'Poisoned. Common soldiers will die after being poisoned for 60 seconds.'],
  ['主人<CRLF><CRLF>小虎已经臣服于你！今后你就是它的主人了。', 'Master<CRLF><CRLF>Xiaohu has submitted to you! From now on, you are its master.'],
  ['主人名称', 'Master Name'],
  ['主城争夺战.建业', 'Capital City Battle. Jianye'],
  ['主城争夺战.汉中', 'Capital City Battle. Hanzhong'],
  ['主城争夺战.许昌', 'Capital City Battle. Xuchang'],
  ['乱舞战法隐藏状态', 'Wild Dance Tactic Hidden Status'],
  ['人数', 'Player Count'],
  ['人气无敌<CRLF><CRLF>您获得了朋友送出的鲜花。', 'Popularity Invincible<CRLF><CRLF>You received flowers sent by a friend.'],
  ['仁义值排行', 'Benevolence Value Rankings'],
  ['仅对高于2级的角色加斗气', 'Only grants Combat Qi to characters above Level 2'],
  ['仙人传', "Immortal's Tale"],
  ['伏虎令', 'Tiger Quelling Token'],
  ['众人合力解决了谷内妖孽乱行的危机，护谷之魂范蠡表达对众人的感激！', 'Everyone worked together to resolve the crisis of demons running rampant in the valley. Fan Li, the Spirit of the Valley, expresses his gratitude!'],
  ['会心击中回斗气效果6', 'Critical Hit Combat Qi Recovery Effect 6'],
  ['传送道具', 'Teleport Item'],
  ['伤害抗性大幅提升', 'Damage Resistance Greatly Increased'],
  ['伺机自带被动状态', 'Ambush Innate Passive Status'],
  ['低于25生成1', 'Generate 1 When Below 25'],
  ['作废', 'Void'],
  ['你中了鬼王的咒术！每3秒损失1%生命值，需要杀死鬼王才能解除！', 'You are cursed by the Ghost King! Lose 1% HP every 3 seconds. Kill the Ghost King to dispel it!'],
  ['你击败了怪力破坏大将军！', 'You defeated the Berserk Destroyer General!'],
  ['你已成功击败了孟获！', 'You have successfully defeated Meng Huo!'],
  ['你得到了击败贼心不死的毛贼的奖励！', 'You received a reward for defeating the Persistent Bandit!'],
  ['你得到了护谷之魂西施的感谢！', 'You received the thanks of Xi Shi, Spirit of the Valley!'],
  ["你携带了兀突骨的贵重铠甲！", "You are carrying Wutugu's precious armor!"],
  ['你杀死了公獐子！<CRLF>在接下来的5分钟之内，<CRLF>若母獐子没有死，可以获得“围猎放生”的奖励。<CRLF>若母獐子也死了，只能获得二块獐子肉。', 'You killed the male musk deer!<CRLF>Within the next 5 minutes,<CRLF>if the female musk deer is not killed, you may receive the "Hunt and Release" reward.<CRLF>If the female musk deer also dies, you can only receive two musk deer meat.'],
  ['你杀死了怀孕的母獐子！<CRLF>杀鸡取卵、赶尽杀绝，短视会使你丧失今后的围猎机会，现在拿走二块獐子肉吧。', 'You killed the pregnant female musk deer!<CRLF>Killing the hen for eggs and extermination—short-sightedness will cost you future hunting opportunities. Take the two musk deer meat now.'],
  ['你杀死了水贼头领孙恩！', 'You killed Sun En, the Water Bandit Leader!'],
  ['你杀死了鬼王！', 'You killed the Ghost King!'],
  ["你获得了英雄的祝福！<CRLF><CRLF>^c3dbff同时拥有此状态和英雄玄石，可触发“得到英雄的祝福！”任务获得奖励", "You received the Hero's Blessing!<CRLF><CRLF>^c3dbffHaving both this status and the Hero Mystic Stone triggers the \"Receive the Hero's Blessing!\" quest for a reward"],
  ['侦察主效果，生命值低于35%则加上', 'Scout Main Effect. Applied When HP Below 35%'],
  ['修行之证', 'Proof of Cultivation'],
  ['倾城之舞', 'Dance of City-Toppling Beauty'],
  ['免冶疗', 'Immune to Healing'],
  ['免疫制霸<CRLF>', 'Immune to Domination<CRLF>'],
  ['免疫祖籍状态', 'Immune to Ancestral Status'],
  ['免疫许褚杀招', "Immune to Xu Chu's Killing Move"],
  ['免疫连中CD', 'Immune to Consecutive Hit CD'],
  ['免疫重轲凝岳', 'Immune to Heavy Halberd Mountain Crush'],
  ['免疫金鼓撼地', 'Immune to Golden Drum Earthshaker'],
  ['全免', 'Full Immunity'],
  ['关中', 'Guanzhong'],
  ['关中赛马', 'Guanzhong Horse Race'],
  ['其实就是普通治疗效果', 'Actually just a normal healing effect'],
  ['典韦传1', 'Tale of Dian Wei 1'],
  ['典韦传2', 'Tale of Dian Wei 2'],
  ['典韦传3', 'Tale of Dian Wei 3'],
  ['典韦传4', 'Tale of Dian Wei 4'],
  ['典韦传5', 'Tale of Dian Wei 5'],
  ['军团人数', 'Legion Member Count'],
  ['军团名望获得榜', 'Legion Renown Earned Leaderboard'],
  ['军团地区声望榜', 'Legion Regional Reputation Leaderboard'],
  ['军团建设度', 'Legion Construction Level'],
  ['军团排名：', 'Legion Rank:'],
  ['军团排行榜', 'Legion Leaderboard'],
  ['军团活跃度榜', 'Legion Activity Leaderboard'],
  ['军团等级', 'Legion Level'],
  ['军团统御度', 'Legion Command Level'],
  ['军团综合排行榜', 'Legion Overall Leaderboard'],
  ['军团财富', 'Legion Wealth'],
  ['军团阵营声望榜', 'Legion Faction Reputation Leaderboard'],
  ['冥思', 'Meditation'],
  ['冬岛', 'Winter Island'],
  ['冲撞击晕，无效果', 'Charge Stun, No Effect'],
  ['冲撞打断', 'Charge Interrupt'],
  ['冲撞无视防御伤害', 'Charge Ignores Defense Damage'],
  ['冲撞破防', 'Charge Breaks Defense'],
  ['冲锋状态不显示', 'Charge Status Not Displayed'],
  ['减速', 'Slow'],
  ['凤鸣山', 'Phoenix Cry Mountain'],
  ['凭此可以自动获得华容道<CRLF>当前积分的奖励。', 'With this, you automatically receive the Huarong Road<CRLF>current points reward.'],
  ['凭此可以自动获得华容道<CRLF>当前积分的奖励。<CRLF>', 'With this, you automatically receive the Huarong Road<CRLF>current points reward.<CRLF>'],
  ['击杀', 'Kill'],
  ['击杀单于', 'Slay the Chanyu'],
  ['击杀南方旱匪的证明！', 'Proof of defeating the Southern bandits!'],
  ['击杀斧头精！', 'Slay the Axe Spirit!'],
  ['击杀火尾虎', 'Slay the Fire-Tail Tiger'],
  ['击杀神秘人', 'Slay the Mysterious Man'],
  ['击杀董卓', 'Slay Dong Zhuo'],
  ['击杀虞姬', 'Slay Consort Yu'],
  ['击杀项羽', 'Slay Xiang Yu'],
  ['击破首领奖励！', 'Boss Defeat Reward!'],
  ['击败了苍龙隐士！<CRLF>', 'Defeated the Azure Dragon Hermit!<CRLF>'],
  ['击败了霍乱的树妖！', 'Defeated the Plagued Tree Demon!'],
  ['击退了鬼马！', 'Repelled the Ghost Horse!'],
  ['击退了黑衣人！<CRLF><CRLF>', 'Repelled the Black-Clad Man!<CRLF><CRLF>'],
  ['切场景消失型', 'Disappears on Scene Change'],
  ['刚使用过快马加鞭，短时再次使用会产生疾驰效果', 'If Swift Spur was just used, using it again shortly after triggers a Gallop effect'],
  ['刚进行过奋力攻击', 'Just performed a Fervent Attack'],
  ['刚进行过奋力攻击被打用', 'Applied when struck after a Fervent Attack'],
  ['刚进行过普通攻击被打用', 'Applied when struck after a Normal Attack'],
  ['刚进行过标准攻击', 'Just performed a Standard Attack'],
  ['刚进行过牵制攻击', 'Just performed a Suppression Attack'],
  ['刚进行过牵制攻击被打用', 'Applied when struck after a Suppression Attack'],
  ['刺杀<CRLF><CRLF>用以加强各类刺杀招式。', 'Assassination<CRLF><CRLF>Used to strengthen various assassination skills.'],
  ['加油！世界杯！', 'Go, World Cup!'],
  ['势力声望', 'Faction Reputation'],
  ['北邙皇陵要坍塌了！', 'The Northern Mang Imperial Mausoleum is collapsing!'],
  ['华容道胜利<CRLF><CRLF>成功护送曹操突破华容道！', 'Huarong Road Victory<CRLF><CRLF>Successfully escorted Cao Cao through Huarong Road!'],
  ['南蛮', 'Southern Barbarians'],
  ['博学值排名', 'Erudition Value Rankings'],
  ['卧龙九天', 'Crouching Dragon Nine Heavens'],
  ['卧龙九天-首领', 'Crouching Dragon Nine Heavens-Boss'],
  ['历练道具', 'Training Item'],
  ['叉', 'Fork'],
  ['发动了攻击。', 'Launched an attack.'],
  ['发放上钩之鱼', 'Grant Hooked Fish'],
  ['发放喜庆元宝', 'Grant Festive Ingots'],
  ['发放生日寿面', 'Grant Birthday Longevity Noodles'],
  ['发放福气元宝', 'Grant Fortunate Ingots'],
  ['发放雪球', 'Grant Snowballs'],
  ['可以对水贼岛进行探索。', 'You can explore Water Bandit Island.'],
  ['可获得交友卡片<CRLF>', 'May obtain a Friend Card<CRLF>'],
  ['名望上周获得', "Renown Earned Last Week"],
  ['名望上月获得', "Renown Earned Last Month"],
  ['名望本周获得', "Renown Earned This Week"],
  ['名望本月获得', "Renown Earned This Month"],
  ['吴上周五丈原贡献', "Wu Last Week Wuzhang Plains Contribution"],
  ['吴国上周击杀排行', "Wu Kingdom Last Week's Kill Rankings"],
  ['吴国上周获得名望', "Wu Kingdom Last Week's Renown Earned"],
  ['吴国上月获得名望', "Wu Kingdom Last Month's Renown Earned"],
  ['吴国军团国家资金', 'Wu Kingdom Legion National Funds'],
  ['吴国名望', 'Wu Kingdom Renown'],
  ['吴国守护状态：激战', 'Wu Kingdom Guard Status: Fierce Battle'],
  ['吴国守护状态：苦战', 'Wu Kingdom Guard Status: Desperate Battle'],
  ['吴国守护状态：铁壁', 'Wu Kingdom Guard Status: Iron Wall'],
  ['吴国总击杀排行', 'Wu Kingdom Total Kill Rankings'],
  ['吴国排行榜', 'Wu Kingdom Leaderboard'],
  ['吴国文勋', 'Wu Kingdom Civil Merit'],
  ['吴国本周获得名望', "Wu Kingdom This Week's Renown Earned"],
  ['吴国本月获得名望', "Wu Kingdom This Month's Renown Earned"],
  ['吴国武勋', 'Wu Kingdom Military Merit'],
  ['吴国玩家国家资金', 'Wu Kingdom Player National Funds'],
  ['吴都建业', 'Wu Capital Jianye'],
  ['吸魂', 'Soul Drain'],
  ['商城消费积分排行榜', 'Cash Shop Spending Points Leaderboard'],
  ['嘲讽', 'Taunt'],
  ['回旋刀连掷第一击命中标记', 'Mark for First Hit of Spinning Blade Combo Throws'],
  ['回马枪<CRLF><CRLF>下一次回马枪会立即出招并回复20斗气。', 'Spear Feint<CRLF><CRLF>The next Spear Feint strikes immediately and restores 20 Combat Qi.'],
  ['国家任务', 'National Quest'],
  ['国家资金排行榜', 'National Funds Leaderboard'],
  ['图鉴品质排行', 'Codex Quality Rankings'],
  ['在地愿做连理枝。', 'On earth, may we become a tree with joined branches.'],
  ['在赤壁大战中取得了胜利！', 'You won the Battle of Red Cliffs!'],
  ['在赤壁大战中攻入敌军水寨！', 'You breached the enemy naval camp in the Battle of Red Cliffs!'],
  ['地宫石怪被击退！', 'The Palace Stone Demon has been repelled!'],
  ['地老天荒<CRLF>您需要找到一位拥有状态“至死不渝”的异性玩家组队。<CRLF>男方做队长，可在汉献帝处领取任务“愿做鸳鸯不羡仙”。<CRLF>完成任务可获得大量奖励！', 'Love Beyond Time<CRLF>You need to find an opposite-sex player with the status "Love Beyond Death" to form a team.<CRLF>The male player should be leader; accept the quest "Rather Be Mandarin Ducks Than Immortals" from Emperor Xian of Han.<CRLF>Complete the quest for great rewards!'],
  ['坐骑', 'Mount'],
  ['基地免疫战魂伤害buff', 'Base Immune to War Soul Damage Buff'],
  ['增加治疗点数50', 'Healing Points +50'],
  ['增强大量防御', 'Greatly Increases Defense'],
  ['士气道具', 'Morale Item'],
  ['声望值', 'Prestige Value'],
  ['声望排行', 'Prestige Rankings'],
  ['多段生成第一段击中标记', 'Mark for First Hit of Multi-Hit Generation'],
  ['多段第一段击中的标记', 'Mark for First Hit of Multi-Hit'],
  ['大声说出你的心意！', "Shout out your heart's desire!"],
  ['天陨泉', 'Skyfall Spring'],
  ['头饰', 'Headgear'],
  ['夷陵之战', 'Battle of Yiling'],
  ['奋力攻击自身组', 'Fervent Attack - Self Group'],
  ['好礼相赠，幸福人生', 'Gifts Given, a Happy Life'],
  ['威风凛凛天神被打败了，你们军团的团结超乎想象！', "The majestic Heavenly God has been defeated! Your Legion's unity is beyond imagination!"],
  ['子午谷', 'Ziwu Valley'],
  ['存档带击中计数型', 'Save Type with Hit Counter'],
  ['存档带时间及杀人计数型', 'Save Type with Time and Kill Counter'],
  ['存档带时间型', 'Save Type with Time'],
  ['存档带时间并切场景消失型', 'Save Type with Time, Disappears on Scene Change'],
  ['存档带杀人计数', 'Save Type with Kill Counter'],
  ['存档带被击中生效型', 'Save Type, Activates When Hit'],
  ['存档普通型', 'Save Type, Normal'],
  ['孙权传1', 'Tale of Sun Quan 1'],
  ['孙权传2', 'Tale of Sun Quan 2'],
  ['孙权传3', 'Tale of Sun Quan 3'],
  ['孙权传4', 'Tale of Sun Quan 4'],
  ['孙权传5', 'Tale of Sun Quan 5'],
  ['官渡之战', 'Battle of Guandu'],
  ['官职奖励', 'Official Rank Reward'],
  ['宝物土系被动状态', 'Treasure Earth Passive Status'],
  ['宝物木系被动状态', 'Treasure Wood Passive Status'],
  ['宝物水系被动状态', 'Treasure Water Passive Status'],
  ['宝物火系被动状态', 'Treasure Fire Passive Status'],
  ['宝物金系被动状态', 'Treasure Metal Passive Status'],
  ['导引<CRLF><CRLF>加快某些射击招式的出招速度。', 'Guidance<CRLF><CRLF>Speeds up the execution of certain shooting skills.'],
  ['小村落', 'Small Village'],
  ['小金粽', 'Small Golden Zongzi'],
  ['川南', 'Southern Sichuan'],
  ['巡礼三国的证明！', 'Proof of touring the Three Kingdoms!'],
  ['巴蜀', 'Bashu'],
  ['布雷兵埋弹', 'Sapper Plants Mines'],
  ['师德值', 'Virtue Value'],
  ['幸运星的照耀<CRLF>每隔60秒可以触发一次奖励。', "Lucky Star's Shine<CRLF>A reward can be triggered every 60 seconds."],
  ['幻想八阵图', 'Fantasy Eight Trigrams'],
  ['幻想八阵图·七星阵', 'Fantasy Eight Trigrams · Seven Star Formation'],
  ['废弃', 'Obsolete'],
  ['废弃<CRLF>', 'Obsolete<CRLF>'],
  ['废弃^c3dbff疾风晕<CRLF><CRLF>^ffffff被剑疾风状态下击中，叠<CRLF>加到3层时将被眩晕。<CRLF>', 'Obsolete^c3dbffGale Stun<CRLF><CRLF>^ffffffStruck while in Sword Gale status; stacking<CRLF>to 3 layers will stun.<CRLF>'],
  ['延时扣除生命', 'Delayed HP Deduction'],
  ['延时生成瞬杀', 'Delayed Instant Kill Generation'],
  ['延时生成破天', 'Delayed Heaven-Breaking Generation'],
  ['建设度', 'Construction Points'],
  ['开启徽记光效', 'Enable Insignia Light Effect'],
  ['开启被动技能“追风升龙”', "Activate Passive Skill 'Windchaser Ascending Dragon'"],
  ['弓', 'Bow'],
  ['引雷钩驱散加攻速状态', 'Lightning Hook Dispels Attack Speed Buff'],
  ['强化升级道具', 'Enhancement Upgrade Item'],
  ['强化石', 'Enhancement Stone'],
  ['强攻战法隐藏状态', 'Fierce Assault Tactic Hidden Status'],
  ['强行下马', 'Forced Dismount'],
  ['强袭<CRLF><CRLF>^c3dbff暴击和暴击伤害上升', 'Fierce Assault<CRLF><CRLF>^c3dbffCritical rate and critical damage increased'],
  ['当前所在地区：七星湖', 'Current Region: Seven Star Lake'],
  ['当前所在地区：凤鸣山', 'Current Region: Phoenix Cry Mountain'],
  ['当前所在地区：子午谷', 'Current Region: Ziwu Valley'],
  ['当前所在地区：水贼岛', 'Current Region: Water Bandit Island'],
  ['当前所在地区：白帝城', 'Current Region: Baidi City'],
  ['当前所在地区：逍遥津', 'Current Region: Xiaoyao Ford'],
  ['当前攻击力', 'Current Attack Power'],
  ['当前生命值', 'Current HP'],
  ['当前计谋', 'Current Strategy'],
  ['当月经验', "This Month's EXP"],
  ['待伏延时斗气减少', 'Delayed Combat Qi Reduction for Ambush'],
  ['得到了上古英雄的神力！', 'You received the divine power of an ancient hero!'],
  ['御风刺后接直刺', 'Direct Thrust follows Wind-Riding Thrust'],
  ['忠诚度道具', 'Loyalty Item'],
  ['怪物通用光环', 'Monster Generic Aura'],
  ['怪物通用延时自杀<CRLF>', 'Monster Generic Delayed Self-Destruct<CRLF>'],
  ['总击杀排行', 'Total Kill Rankings'],
  ['总斩杀数排名', 'Total Slain Count Rankings'],
  ['恢复健康', 'Health Restored'],
  ['恭喜您击败林飘飘！', 'Congratulations on defeating Lin Piaopiao!'],
  ['恭喜您挑战关羽获胜！', 'Congratulations on defeating Guan Yu in challenge!'],
  ['恭喜您挑战典韦获胜！', 'Congratulations on defeating Dian Wei in challenge!'],
  ['恭喜您挑战吕布获胜！', 'Congratulations on defeating Lu Bu in challenge!'],
  ['恭喜您挑战赵云获胜！', 'Congratulations on defeating Zhao Yun in challenge!'],
  ['恭喜您挑战马超获胜！', 'Congratulations on defeating Ma Chao in challenge!'],
  ['恭喜您获得圣诞礼物！', 'Congratulations on receiving a Christmas gift!'],
  ['恭喜获胜！', 'Congratulations on your victory!'],
  ['恭喜！<CRLF>您已获得灵气奖励。', 'Congratulations!<CRLF>You have received a Spirit Energy reward.'],
  ['您已进入了白帝城。<CRLF>争夺战正在进行中，注意危险！', 'You have entered Baidi City.<CRLF>The contest is underway—beware of danger!'],
  ['您获得了GM送出的礼物！', 'You received a gift from a GM!'],
  ['情人节特有的效果<CRLF>提升战斗内外生命回复的速度', "A special Valentine's Day effect<CRLF>Speeds up HP recovery in and out of combat"],
  ['情妖的哀怨。', "The Love Demon's Lament."],
  ['情意绵绵。', 'Affection runs deep.'],
  ['愚人之节', "Fool's Day"],
  ['成功击杀丰收的恶霸<CRLF>', 'Successfully slew the Harvest Bully<CRLF>'],
  ['成功格挡的话增加斗气', 'Successful block restores Combat Qi'],
  ['成功退敌！', 'Enemies successfully repelled!'],
  ['我军取得了赤壁决战的胜利！', 'Our army won the Chibi Decisive Battle!'],
  ['我军取得了赤壁前哨战的胜利！', 'Our army won the Chibi Skirmish!'],
  ['我的个人排行榜', 'My Personal Leaderboard'],
  ['我的全部个人排名', 'All My Personal Ranks'],
  ['我的全部军团排名', 'All My Legion Ranks'],
  ['我的全部竞技排名', 'All My Arena Ranks'],
  ['我的全部阵营排名', 'All My Camp Ranks'],
  ['我的军团排行榜', 'My Legion Leaderboard'],
  ['我的排行榜', 'My Leaderboard'],
  ['我的竞技排行榜', 'My Arena Leaderboard'],
  ['我的阵营排行榜', 'My Camp Leaderboard'],
  ['战功值排名', 'War Merit Value Rankings'],
  ['战功显赫', 'Illustrious War Merit'],
  ['战斗中14秒冷却', '14s Cooldown in Combat'],
  ['战斗力评分', 'Combat Power Score'],
  ['战魂', 'War Soul'],
  ['战魂相关', 'War Soul Related'],
  ['战魂评分', 'War Soul Score'],
  ['戟', 'Halberd'],
  ['所有骑战技能74级后才会消耗斗气<CRLF><CRLF>改了', 'All mounted combat skills only consume Combat Qi after Level 74<CRLF><CRLF>Changed'],
  ['扇', 'Fan'],
  ['打败妖梦住持！<CRLF>', 'Defeated the Nightmare Abbot!<CRLF>'],
  ['打败风流公子！', 'Defeated the Charming Noble!'],
  ['技能书', 'Skill Book'],
  ['技能格道具', 'Skill Slot Item'],
  ['技能连中状态', 'Consecutive Hit Status'],
  ['抓捕道具', 'Capture Item'],
  ['护具', 'Armor'],
  ['护卫技能书', 'Guard Skill Book'],
  ['护卫排名：', 'Guard Rank:'],
  ['护卫攻击力排行榜', 'Guard Attack Power Leaderboard'],
  ['护卫生命值排行榜', 'Guard HP Leaderboard'],
  ['护卫相关', 'Guard Related'],
  ['护卫综合排行榜', 'Guard Overall Leaderboard'],
  ['护卫计谋排行榜', 'Guard Strategy Leaderboard'],
  ['报名打断', 'Registration Interrupt'],
  ['拥有月宫使者的祝福，你可获得每日一次的奖励！', "With the Moon Palace Messenger's blessing, you may claim a daily reward!"],
  ['拨马回身<CRLF><CRLF>诱敌深入，此时任意招式命中敌人则效果消失。', 'Wheel About<CRLF><CRLF>Lure the enemy in. If any skill hits the enemy while this is active, the effect disappears.'],
  ['持续加经验', 'Continuous EXP Gain'],
  ['挑战塔', 'Challenge Tower'],
  ['控制重置觅心刺CD频率，20S内最多生效一次。', 'Controls the reset of Heartseeker Thrust CD; takes effect at most once every 20s.'],
  ['提升斗气上限', 'Raises Max Combat Qi'],
  ['搅海式一式目标', 'Stirring Sea Form 1 Target'],
  ['擂台大会第一季', 'Arena Tournament Season 1'],
  ['擂台大会轻量级', 'Arena Tournament Lightweight Class'],
  ['收藏图鉴品质', 'Collection Codex Quality'],
  ['文勋排行', 'Civil Merit Rankings'],
  ['文官上月获得名望', "Civil Officials' Renown Earned Last Month"],
  ['文官本月获得名望', "Civil Officials' Renown Earned This Month"],
  ['斧', 'Axe'],
  ['斩将', 'Slay the General'],
  ['斩杀总数', 'Total Slain Count'],
  ['新国战PVP', 'New National War PVP'],
  ['新国战PVP.关中', 'New National War PVP. Guanzhong'],
  ['新国战PVP.巴蜀', 'New National War PVP. Bashu'],
  ['新国战PVP.建业', 'New National War PVP. Jianye'],
  ['新国战PVP.汉中', 'New National War PVP. Hanzhong'],
  ['新国战PVP.江南', 'New National War PVP. Jiangnan'],
  ['新国战PVP.河北', 'New National War PVP. Hebei'],
  ['新国战PVP.洛阳', 'New National War PVP. Luoyang'],
  ['新国战PVP.荆襄', 'New National War PVP. Jingxiang'],
  ['新国战PVP.西凉', 'New National War PVP. Xiliang'],
  ['新国战PVP.许昌', 'New National War PVP. Xuchang'],
  ['新婚燕尔，甜蜜的新婚状态', 'Newlywed Bliss, a sweet newlywed status'],
  ['新年拔得头筹，领受至高的吉祥吧！', 'Claim the top spot in the New Year and receive the highest good fortune!'],
  ['新无双07', 'Peerless 07'],
  ['新春福运', 'New Spring Fortune'],
  ['旋风式计数，最多叠加8层', 'Whirlwind Type Counter, stacks up to 8 times'],
  ['无双楼兰古殿', 'Peerless Loulan Ancient Palace'],
  ['无双项王魔域1', 'Peerless Demon Realm of the Hegemon King 1'],
  ['无双项王魔域2', 'Peerless Demon Realm of the Hegemon King 2'],
  ['无双项王魔域3', 'Peerless Demon Realm of the Hegemon King 3'],
  ['无双项王魔域4', 'Peerless Demon Realm of the Hegemon King 4'],
  ['无双项王魔域5', 'Peerless Demon Realm of the Hegemon King 5'],
  ['无双项王魔域6', 'Peerless Demon Realm of the Hegemon King 6'],
  ['无双项王魔域7', 'Peerless Demon Realm of the Hegemon King 7'],
  ['无双项王魔域8', 'Peerless Demon Realm of the Hegemon King 8'],
  ['无双项王魔域9', 'Peerless Demon Realm of the Hegemon King 9'],
  ['无双项王魔域10', 'Peerless Demon Realm of the Hegemon King 10'],
  ['无差别练习', 'Free-for-all Practice'],
  ['无敌', 'Invincible'],
  ['无用', 'Useless'],
  ['无用，无图标', 'Useless, No Icon'],
  ['无视破坏', 'Ignores Destruction'],
  ['暂废', 'Temporarily Void'],
  ['暴击率降低', 'Critical Rate Reduced'],
  ['暴击计数', 'Critical Counter'],
  ['曹植传', 'Tale of Cao Zhi'],
  ['替身娃娃', 'Substitute Doll'],
  ['本周获得名望', "This Week's Renown Earned"],
  ['本周获得活跃度总榜', "This Week's Total Activity Rankings"],
  ['本月获得名望', "This Month's Renown Earned"],
  ['本月获得师德排行', "This Month's Virtue Earned Rankings"],
  ['本月获得消费积分排行', "This Month's Spending Points Earned Rankings"],
  ['朱雀烈炎瞬间伤害，无图标', 'Vermilion Bird Flame Instant Damage, No Icon'],
  ['机率免疫击晕', 'Chance to Be Immune to Stun'],
  ['机率免疫定身', 'Chance to Be Immune to Immobilize'],
  ['杂类', 'Miscellaneous'],
  ['枪', 'Spear'],
  ['标准攻击自身组', 'Standard Attack - Self Group'],
  ['梦境空间（第一层）', 'Dream Space (Floor 1)'],
  ['梦境空间（第三层）', 'Dream Space (Floor 3)'],
  ['梦境空间（第二层）', 'Dream Space (Floor 2)'],
  ['棍', 'Staff'],
  ['楼兰古殿', 'Loulan Ancient Palace'],
  ['楼兰沙海', 'Loulan Sand Sea'],
  ['歌楼舞榭赏翩翩', 'Song Lounges and Dance Terraces, Admire the Graceful'],
  ['此项作废', 'This Entry Is Void'],
  ['武勋排行', 'Military Merit Rankings'],
  ['武官上月获得名望', "Military Officials' Renown Earned Last Month"],
  ['武官本月获得名望', "Military Officials' Renown Earned This Month"],
  ['殇之雪域', 'Snowfield of Sorrow'],
  ['每分钟获得一定历练。', 'Gain a certain amount of Training every minute.'],
  ['水贼岛', 'Water Bandit Island'],
  ['江南', 'Jiangnan'],
  ['河北', 'Hebei'],
  ['治疗耐力', 'Healing Stamina'],
  ['治疗评分', 'Healing Score'],
  ['洛阳', 'Luoyang'],
  ['活动点数到达1000！<CRLF>可获得一级奖励！', 'Activity Points reached 1000!<CRLF>Tier 1 reward available!'],
  ['活动点数到达2000！<CRLF>可获得二级奖励！', 'Activity Points reached 2000!<CRLF>Tier 2 reward available!'],
  ['活动点数到达2500！<CRLF>可获得四级奖励！', 'Activity Points reached 2500!<CRLF>Tier 4 reward available!'],
  ['活动点数到达3000！<CRLF>可获得三级奖励！', 'Activity Points reached 3000!<CRLF>Tier 3 reward available!'],
  ['活动点数到达3000！<CRLF>可获得五级奖励！', 'Activity Points reached 3000!<CRLF>Tier 5 reward available!'],
  ['测试-无用', 'Test-Useless'],
  ['测试_加受伤抗性', 'Test_Increase Injury Resistance'],
  ['测试_加命中<CRLF>杨俊北邙用了，别乱动', 'Test_Increase Accuracy<CRLF>Yang Jun used this in Northern Mang, do not mess with it'],
  ['测试_加封印抗性 ', 'Test_Increase Seal Resistance '],
  ['测试_加攻 <CRLF>杨俊北邙用了，别乱动', 'Test_Increase Attack <CRLF>Yang Jun used this in Northern Mang, do not mess with it'],
  ['测试_加暴击抗性 ', 'Test_Increase Critical Resistance '],
  ['测试_加流失抗性 ', 'Test_Increase Drain Resistance '],
  ['测试_加虚弱抗性', 'Test_Increase Weakness Resistance'],
  ['测试_加闪避', 'Test_Increase Dodge'],
  ['测试_加防<CRLF>杨俊北邙用了，别乱动', 'Test_Increase Defense<CRLF>Yang Jun used this in Northern Mang, do not mess with it'],
  ['测试_加限制抗性', 'Test_Increase Restriction Resistance'],
  ['测试_直接减血', 'Test_Direct HP Reduction'],
  ['测试_直间抗双加', 'Test_Direct and Resistance Dual Boost'],
  ['测试_血斗体全加 ', 'Test_Blood-Fury Physique Full Boost '],
  ['测试_重置技能CD', 'Test_Reset Skill CD'],
  ['测试z13', 'Testz13'],
  ['测试z8', 'Testz8'],
  ['测试专用场景', 'Test-Only Scene'],
  ['测试专用技能对应状态', 'Test-Only Skill Corresponding Status'],
  ['测试反弹状态', 'Test Reflect Status'],
  ['测试场景1', 'Test Scene 1'],
  ['测试场景2', 'Test Scene 2'],
  ['测试场景3', 'Test Scene 3'],
  ['测试生成反弹状态 ', 'Test Generate Reflect Status '],
  ['消耗类道具', 'Consumable Item'],
  ['溺水中，大幅减少生命直至死亡。', 'Drowning. HP greatly reduced until death.'],
  ['演义益州之战', 'Romance: Battle of Yizhou'],
  ['演武场', 'Martial Arena'],
  ['潜行冷却', 'Stealth Cooldown'],
  ['激活秘石光效', 'Activate Mystic Stone Light Effect'],
  ['濮阳之战-II', 'Battle of Puyang-II'],
  ['濮阳之战（英雄级）', 'Battle of Puyang (Heroic)'],
  ['濮阳英雄级征战战场中失败', 'Defeat in Puyang Heroic Expedition Battlefield'],
  ['濮阳英雄级征战战场平局', 'Draw in Puyang Heroic Expedition Battlefield'],
  ['濮阳英雄级征战战场胜利', 'Victory in Puyang Heroic Expedition Battlefield'],
  ['灵山密道', 'Spirit Mountain Secret Path'],
  ['点卯', 'Roll Call'],
  ['炼魂状态', 'Soul Refining Status'],
  ['熊瞎子被赶走了，猎场恢复了祥和。<CRLF>领受你的奖励吧。', 'The blind bear has been driven off, and the hunting grounds are peaceful again.<CRLF>Claim your reward.'],
  ['燃烧<CRLF><CRLF>', 'Burn<CRLF><CRLF>'],
  ['爪', 'Claws'],
  ['牧神', 'Shepherd God'],
  ['物品', 'Item'],
  ['牵制攻击破坏效果', 'Suppression Attack Destruction Effect'],
  ['牵制攻击自身组', 'Suppression Attack - Self Group'],
  ['猛蹿的火苗被扑灭了，牛肉不必担心会被烤焦了。<CRLF>扑鼻的香味让你垂涎三尺，烤牛的经验增长了。<CRLF>扑灭火苗3次可以获得丰厚奖励！', "The leaping flames have been put out—the beef won't be scorched.<CRLF>The mouth-watering aroma makes you drool; your EXP from grilling the beef has increased.<CRLF>Put out the flames 3 times to claim a generous reward!"],
  ['玄武之心', 'Heart of the Black Tortoise'],
  ['环', 'Ring'],
  ['生成休息', 'Generate Rest'],
  ['生成奋勇', 'Generate Valor'],
  ['生成御风', 'Generate Windride'],
  ['生成离开', 'Generate Departure'],
  ['甲板<CRLF>战船的甲板', 'Deck<CRLF>The deck of a warship'],
  ['界桥之战', 'Battle of Jieqiao'],
  ['留芳幽谷', 'Valley of Lasting Fragrance'],
  ['白帝城2', 'Baidi City 2'],
  ['直接恢复耐力', 'Instant Stamina Recovery'],
  ['盾', 'Shield'],
  ['看不到，被打生成加防效果', 'Invisible; generates defense boost when hit'],
  ['瞬回血', 'Instant HP Recovery'],
  ['瞬回血并持续回', 'Instant HP Recovery with Continuous Regen'],
  ['破军', 'Army Breaker'],
  ['礼物包', 'Gift Pack'],
  ['礼袋', 'Gift Bag'],
  ['祈福状态', 'Prayer Status'],
  ['神州赛马', 'Shenzhou Horse Race'],
  ['禁止生命回复、体力回复、禁止暴击', 'Blocks HP Recovery, Stamina Recovery, and Criticals'],
  ['禄星高照', 'Prosperity Star Shines High'],
  ['福星高照', 'Lucky Star Shines High'],
  ['种植榆树的证明！<CRLF>集齐白杨、竹子、榆树、红枫四个证明<CRLF>可领取惊喜奖励！', 'Proof of planting elm trees!<CRLF>Collect all four proofs—poplar, bamboo, elm, and red maple<CRLF>to claim a surprise reward!'],
  ['种植白杨的证明！<CRLF>集齐白杨、竹子、榆树、红枫四个证明<CRLF>可领取惊喜奖励！', 'Proof of planting poplar trees!<CRLF>Collect all four proofs—poplar, bamboo, elm, and red maple<CRLF>to claim a surprise reward!'],
  ['种植竹子的证明！<CRLF>集齐白杨、竹子、榆树、红枫四个证明<CRLF>可领取惊喜奖励！', 'Proof of planting bamboo!<CRLF>Collect all four proofs—poplar, bamboo, elm, and red maple<CRLF>to claim a surprise reward!'],
  ['种植红枫的证明！<CRLF>集齐白杨、竹子、榆树、红枫四个证明<CRLF>可领取惊喜奖励！', 'Proof of planting red maples!<CRLF>Collect all four proofs—poplar, bamboo, elm, and red maple<CRLF>to claim a surprise reward!'],
  ['秘文', 'Secret Text'],
  ['积分', 'Points'],
  ["稳固的破釜沉舟效果", "Steady 'Sink the Boats' Effect"],
  ['竞技军团上周贡献度', 'Arena Legion Contributions Last Week'],
  ['竞技军团排名：', 'Arena Legion Rank:'],
  ['竞技军团排行榜', 'Arena Legion Leaderboard'],
  ['竞技军团等级排名', 'Arena Legion Level Rankings'],
  ['竞技场12人', 'Arena 12 Players'],
  ['竞技场1人', 'Arena 1 Player'],
  ['竞技排名：', 'Arena Rank:'],
  ['竞技排行', 'Arena Rankings'],
  ['竞技排行榜', 'Arena Leaderboard'],
  ['竞技英雄战', 'Arena Hero Battle'],
  ['等级', 'Level'],
  ['等级排行', 'Level Rankings'],
  ['约战', 'Duel Challenge'],
  ['练习马场', 'Practice Racetrack'],
  ['结义上周总贡献度', 'Sworn Brotherhood Contributions Last Week'],
  ['结义总贡献度', 'Sworn Brotherhood Total Contributions'],
  ['结义总贡献排行榜', 'Sworn Brotherhood Total Contribution Leaderboard'],
  ['结义排名：', 'Sworn Brotherhood Rank:'],
  ['绛纹蛇毒', 'Crimson-Striped Snake Venom'],
  ['统御度', 'Command Value'],
  ['综合评价', 'Overall Rating'],
  ['综合评分', 'Overall Score'],
  ['群英会', "Heroes' Assembly"],
  ['群英会·决赛', "Heroes' Assembly · Finals"],
  ['群英会·初赛', "Heroes' Assembly · Preliminaries"],
  ['群英会·复赛', "Heroes' Assembly · Second Round"],
  ['群英会野外', "Heroes' Assembly Field"],
  ['耳饰', 'Earrings'],
  ['聚贤谷', 'Valley of Gathered Worthies'],
  ['肩铠', 'Shoulder Armor'],
  ['背后击中绊马', 'Trips Mount When Hit from Behind'],
  ['背袭<CRLF><CRLF>增加暴击伤害和背面攻击暴击率。', 'Backstab<CRLF><CRLF>Increases critical damage and critical rate of attacks from behind.'],
  ['胸铠', 'Chest Armor'],
  ['腕甲', 'Wrist Armor'],
  ['腕铠', 'Wrist Armor'],
  ['腾跃打断', 'Leap Interrupt'],
  ['腾跃无视防御伤害', 'Leap Ignores Defense'],
  ['腾跃破防', 'Leap Breaks Defense'],
  ['腿甲', 'Leg Armor'],
  ['腿铠', 'Leg Armor'],
  ['自动复活', 'Auto Revive'],
  ['自由练习', 'Free Practice'],
  ['至死不渝<CRLF>您需要找到一位拥有状态“地老天荒”的异性玩家组队。<CRLF>男方做队长，可在汉献帝处领取任务“愿做鸳鸯不羡仙”。<CRLF>完成任务可获得大量奖励！', 'Love Beyond Death<CRLF>You need to find an opposite-sex player with the status "Love Beyond Time" to form a team.<CRLF>The male player should be leader; accept the quest "Rather Be Mandarin Ducks Than Immortals" from Emperor Xian of Han.<CRLF>Complete the quest for great rewards!'],
  ['舞', 'Dance'],
  ['苦想', 'Pondering'],
  ['荆襄', 'Jingxiang'],
  ['草原', 'Grassland'],
  ['草船借箭', 'Borrowing Arrows with Straw Boats'],
  ['草船借箭上周积分榜', "Borrowing Arrows with Straw Boats Last Week's Points Leaderboard"],
  ['草船借箭上月积分榜', "Borrowing Arrows with Straw Boats Last Month's Points Leaderboard"],
  ['荣耀值排名', 'Glory Value Rankings'],
  ['药品', 'Medicine'],
  ['落缨射<CRLF><CRLF>下一次射击的攻击强度和攻击力增加。', 'Falling Plume Shot<CRLF><CRLF>Increases the attack strength and attack power of the next shot.'],
  ['董卓行宫', "Dong Zhuo's Imperial Palace"],
  ['葭萌关限时', 'Jiameng Pass Time-Limited'],
  ['虎年打虎，开门大吉。', 'Hunt tigers in the Year of the Tiger—a great start to the year.'],
  ['虎牢关', 'Hulao Pass'],
  ['虎虎生威礼包', 'Tiger Vigor Gift Pack'],
  ['虚拟币', 'Virtual Currency'],
  ['蜀上周五丈原贡献', 'Shu Last Week Wuzhang Plains Contribution'],
  ['蜀国上周击杀排行', "Shu Kingdom Last Week's Kill Rankings"],
  ['蜀国上周获得名望', "Shu Kingdom Last Week's Renown Earned"],
  ['蜀国上月获得名望', "Shu Kingdom Last Month's Renown Earned"],
  ['蜀国军团国家资金', 'Shu Kingdom Legion National Funds'],
  ['蜀国名望', 'Shu Kingdom Renown'],
  ['蜀国守护状态：激战', 'Shu Kingdom Guard Status: Fierce Battle'],
  ['蜀国守护状态：苦战', 'Shu Kingdom Guard Status: Desperate Battle'],
  ['蜀国守护状态：铁壁', 'Shu Kingdom Guard Status: Iron Wall'],
  ['蜀国总击杀排行', 'Shu Kingdom Total Kill Rankings'],
  ['蜀国排行榜', 'Shu Kingdom Leaderboard'],
  ['蜀国文勋', 'Shu Kingdom Civil Merit'],
  ['蜀国本周获得名望', "Shu Kingdom This Week's Renown Earned"],
  ['蜀国本月获得名望', "Shu Kingdom This Month's Renown Earned"],
  ['蜀国武勋', 'Shu Kingdom Military Merit'],
  ['蜀国玩家国家资金', 'Shu Kingdom Player National Funds'],
  ['蜀都汉中', 'Shu Capital Hanzhong'],
  ['蝶梦香', 'Butterfly Dream Incense'],
  ['血勇+爆抗', 'Blood Valor + Blast Resistance'],
  ['血勇的不动如山效果', "Blood Valor's Immovable Mountain Effect"],
  ['血勇的坚定心志效果', "Blood Valor's Steadfast Will Effect"],
  ['血药', 'HP Potion'],
  ['表情', 'Emote'],
  ['被告白，心花怒放。', 'You have been confessed to—your heart blooms with joy.'],
  ['裂云击', 'Cloud-Splitting Strike'],
  ['襄阳之战', 'Battle of Xiangyang'],
  ['西凉', 'Xiliang'],
  ['西凉缭乱', 'Xiliang Turmoil'],
  ['西域蜃楼城', 'Western Regions Mirage City'],
  ['要塞争夺参战', 'Fortress Contest Participation'],
  ['要塞争夺平局', 'Fortress Contest Draw'],
  ['要塞争夺胜利', 'Fortress Contest Victory'],
  ['许褚传胜利<CRLF><CRLF>成功通关许褚传！', "Tale of Xu Chu Victory<CRLF><CRLF>Successfully cleared Tale of Xu Chu!"],
  ['许褚传胜利<CRLF><CRLF>成功通关难度1许褚传！', "Tale of Xu Chu Victory<CRLF><CRLF>Successfully cleared Difficulty 1 Tale of Xu Chu!"],
  ['许褚传胜利<CRLF><CRLF>成功通关难度2许褚传！', "Tale of Xu Chu Victory<CRLF><CRLF>Successfully cleared Difficulty 2 Tale of Xu Chu!"],
  ['许褚传胜利<CRLF><CRLF>成功通关难度3许褚传！', "Tale of Xu Chu Victory<CRLF><CRLF>Successfully cleared Difficulty 3 Tale of Xu Chu!"],
  ['许褚传胜利<CRLF><CRLF>成功通关难度4许褚传！', "Tale of Xu Chu Victory<CRLF><CRLF>Successfully cleared Difficulty 4 Tale of Xu Chu!"],
  ['许褚传胜利<CRLF><CRLF>成功通关难度5许褚传！', "Tale of Xu Chu Victory<CRLF><CRLF>Successfully cleared Difficulty 5 Tale of Xu Chu!"],
  ['试_加暴击', 'Trial_Increase Crit'],
  ['详细', 'Details'],
  ['貂禅外传', 'Diaochan: The Untold Tale'],
  ['贡献度', 'Contribution Value'],
  ['财富排行', 'Wealth Rankings'],
  ['财富（金）', 'Wealth (Gold)'],
  ['赛马使用位移技能后的眩晕', 'Stun After Using a Movement Skill in Horse Race'],
  ['赛马热身状态', 'Horse Race Warm-Up Status'],
  ['赤壁之战', 'Battle of Chibi'],
  ['赤壁决战结束', 'Chibi Decisive Battle Ended'],
  ['赤壁前哨战结束', 'Chibi Skirmish Ended'],
  ['赤壁大战PVP', 'Battle of Red Cliffs PVP'],
  ['赵云传', 'Tale of Zhao Yun'],
  ['赶回了一只围猎兽！', 'Driven back a hunting beast!'],
  ['赶走了圣诞黑衣人！', 'Drove off the Christmas Black-Clad Man!'],
  ['跑商进行中，不能使用白帝城传送令旗和秘道令。', 'Trade run in progress. You cannot use the Baidi City Teleport Flag or the Secret Path Token.'],
  ['跨服PK战', 'Cross-Server PK Battle'],
  ['跨服PK赛资格选拔', 'Cross-Server PK Qualifier'],
  ['跨服城战', 'Cross-Server City War'],
  ['跨服战场中转', 'Cross-Server Battlefield Transfer'],
  ['跨服排行榜', 'Cross-Server Leaderboard'],
  ['跨服竞技练习场', 'Cross-Server Arena Practice Field'],
  ['轩辕遗迹', 'Xuanyuan Ruins'],
  ['轻骑长驱隐藏效果，被打生成绊马', 'Light Cavalry Long Charge hidden effect; generates a mount trip when hit'],
  ['过关斩将', 'Through Passes, Slashing Generals'],
  ['运畴隐藏', 'Stratagem Hidden'],
  ['连中模式<CRLF><CRLF>15秒内连续射击会有增强效果。', 'Consecutive Hit Mode<CRLF><CRLF>Continuous firing within 15 seconds grants a boosted effect.'],
  ['连中模式<CRLF><CRLF>30秒内连续射击会有增强效果。', 'Consecutive Hit Mode<CRLF><CRLF>Continuous firing within 30 seconds grants a boosted effect.'],
  ['连刺<CRLF>', 'Continuous Thrust<CRLF>'],
  ['连劈', 'Continuous Cleave'],
  ['连劈第一下命中则加下，用来判断连劈是否两下均击中。', 'If the first hit of Continuous Cleave lands, add the next—used to judge whether both hits connected.'],
  ['连杀<CRLF><CRLF>任何攻击招式会击晕敌人', 'Chain Kill<CRLF><CRLF>Any attack skill stuns the enemy'],
  ['连舞击中回斗气效果10', 'Continuous Dance Hit Combat Qi Recovery Effect 10'],
  ['连舞击中回斗气效果8', 'Continuous Dance Hit Combat Qi Recovery Effect 8'],
  ['迷花雨林', 'Enchanted Flower Rainforest'],
  ['追踪<CRLF><CRLF>找到了刻有记号的石头！继续努力，追踪状态叠加到6层就大功告成了。', 'Tracking<CRLF><CRLF>Found a marked stone! Keep going—when the tracking status stacks to 6 layers, the job is done.'],
  ['追风使用后持续3秒。<CRLF>测试时间用<CRLF>生成风遁5905的技能。<CRLF>吸收伤害最大不超过2万。<CRLF>免疫眩晕与减速。<CRLF>调整攻击间隔20%。<CRLF>调整攻击距离3米。', 'After using Windchaser, lasts 3 seconds.<CRLF>For testing time use<CRLF>Generates the Wind Escape skill (5905).<CRLF>Absorbed damage max 20,000.<CRLF>Immune to stun and slow.<CRLF>Adjust attack interval by 20%.<CRLF>Adjust attack range by 3 meters.'],
  ['逍遥津', 'Xiaoyao Ford'],
  ['逍遥隐士悄悄递给了你一个信函。', 'The Carefree Hermit quietly handed you a letter.'],
  ['配方卷轴', 'Recipe Scroll'],
  ['醉蝶香', 'Drunken Butterfly Incense'],
  ['金币', 'Gold Coins'],
  ['钓鱼驱散', 'Fishing Dispel'],
  ['钩', 'Hook'],
  ['钺', 'Broadaxe'],
  ['铮铮之舞5秒后每秒加斗气', 'Clanging Dance: after 5 seconds, gain Combat Qi every second'],
  ['铮铮之舞前5秒每秒加斗气', 'Clanging Dance: for the first 5 seconds, gain Combat Qi every second'],
  ['锏', 'Iron Mace'],
  ['锤', 'Hammer'],
  ['锤大招<CRLF>会生成种族大招加强状态和眩晕', 'Hammer Ultimate Skill<CRLF>Generates a race ultimate-skill boost status and stun'],
  ['锤格挡时<CRLF>会生成强攻和乱舞点数', 'When Hammer blocks<CRLF>generates Fierce Assault and Wild Dance points'],
  ['闪击<CRLF><CRLF>隐伏现身后攻击提升。', 'Flash Strike<CRLF><CRLF>Attack increased after emerging from stealth.'],
  ['闪避<CRLF><CRLF>3秒内躲避敌人招式攻击。', 'Evasion<CRLF><CRLF>Dodge enemy skill attacks for 3 seconds.'],
  ['队伍竞技排行榜', 'Team Arena Leaderboard'],
  ['队伍等级', 'Team Level'],
  ['队伍等级排名', 'Team Level Rankings'],
  ['队伍经验', 'Team EXP'],
  ['队伍综合评分', 'Team Overall Score'],
  ['队伍综合评分排名', 'Team Overall Score Rankings'],
  ['防御评分', 'Defense Score'],
  ['阵营声望', 'Camp Prestige'],
  ['阵营排名：', 'Camp Rank:'],
  ['阵营排行榜', 'Camp Leaderboard'],
  ['阵营约战.建业', 'Camp Duel. Jianye'],
  ['阵营约战.汉中', 'Camp Duel. Hanzhong'],
  ['阵营约战.许昌', 'Camp Duel. Xuchang'],
  ['附加属性类型定义：', 'Additional Attribute Type Definitions:'],
  ['降低大量防御', 'Greatly Reduces Defense'],
  ['隐藏', 'Hidden'],
  ['隐藏状态', 'Hidden Status'],
  ['雩神降临！<CRLF>凭此状态向一位雩祭使者领取该地区声望奖励。<CRLF>下线消失！切换场景消失！', 'The Rain God Descends!<CRLF>Use this status to claim the region Prestige reward from a Rain Prayer Messenger.<CRLF>Disappears on logout! Disappears on scene change!'],
]);

// Common map for short strings
const common = new Map([
  ['排名：', 'Rank:'],
  ['排行榜', 'Leaderboard'],
  ['排行', 'Rankings'],
  ['排名', 'Rank'],
  ['声望值', 'Prestige Value'],
  ['声望', 'Prestige'],
  ['名望', 'Renown'],
  ['活跃度', 'Activity'],
  ['财富', 'Wealth'],
  ['贡献度', 'Contribution'],
  ['贡献', 'Contribution'],
  ['积分', 'Points'],
  ['点数', 'Points'],
  ['战功值', 'War Merit'],
  ['战功', 'War Merit'],
  ['文勋', 'Civil Merit'],
  ['武勋', 'Military Merit'],
  ['仁义值', 'Benevolence'],
  ['仁义', 'Benevolence'],
  ['博学值', 'Erudition'],
  ['博学', 'Erudition'],
  ['师德', 'Mentor Virtue'],
  ['荣耀值', 'Glory'],
  ['荣耀', 'Glory'],
  ['经验值', 'EXP'],
  ['经验', 'EXP'],
  ['战斗力', 'Combat Power'],
  ['战魂', 'War Soul'],
  ['等级', 'Level'],
  ['称号', 'Title'],
  ['奖励', 'Reward'],
  ['刷新', 'Refresh'],
  ['每月', 'Monthly'],
  ['每周', 'Weekly'],
  ['每日', 'Daily'],
  ['统计', 'Statistics'],
  ['说明', 'Notes'],
  ['攻击力', 'Attack Power'],
  ['防御力', 'Defense'],
  ['生命值', 'HP'],
  ['生命上限', 'Max HP'],
  ['生命回复', 'HP Recovery'],
  ['法力值', 'Mana'],
  ['综合评价', 'Overall Rating'],
  ['综合评分', 'Overall Score'],
  ['主人', 'Master'],
  ['当前', 'Current'],
  ['传送', 'Teleport'],
  ['道具', 'Item'],
  ['物品', 'Item'],
  ['装备', 'Equipment'],
  ['强化', 'Enhancement'],
  ['符玉', 'Jade Talisman'],
  ['类', 'Type'],
  ['攻击', 'Attack'],
  ['防御', 'Defense'],
  ['火', 'Fire'],
  ['水', 'Water'],
  ['雷', 'Thunder'],
  ['风', 'Wind'],
  ['物理', 'Physical'],
  ['魔法', 'Magic'],
  ['体质', 'Constitution'],
  ['力量', 'Strength'],
  ['敏捷', 'Agility'],
  ['智力', 'Intelligence'],
  ['生命', 'HP'],
  ['法力', 'Mana'],
  ['复活', 'Revive'],
  ['自动', 'Automatic'],
  ['等待时间', 'Wait Time'],
  ['毫秒', 'ms'],
  ['颜色', 'Color'],
  ['效果', 'Effect'],
  ['光效', 'Light Effect'],
  ['状态', 'Status'],
  ['无敌', 'Invincible'],
  ['提升', 'Boost'],
  ['能力', 'Power'],
  ['变化', 'Change'],
  ['无', 'None'],
  ['废', 'Obsolete'],
  ['测试', 'Test'],
  ['作废', 'Void'],
  ['全部', 'All'],
  ['我的', 'My'],
  ['本周', 'This Week'],
  ['上周', 'Last Week'],
  ['本月', 'This Month'],
  ['上月', 'Last Month'],
  ['评分', 'Score'],
  ['斗气', 'Combat Qi'],
  ['治疗', 'Healing'],
  ['耐力', 'Stamina'],
  ['体力', 'Stamina'],
  ['历练', 'Training'],
  ['统御度', 'Command Value'],
  ['建设度', 'Construction Level'],
  ['坐骑', 'Mount'],
  ['技能书', 'Skill Book'],
  ['药品', 'Medicine'],
  ['秘石', 'Mystic Stone'],
  ['图鉴', 'Codex'],
  ['配方卷轴', 'Recipe Scroll'],
  ['表情', 'Emote'],
  ['弓', 'Bow'],
  ['枪', 'Spear'],
  ['戟', 'Halberd'],
  ['斧', 'Axe'],
  ['锤', 'Hammer'],
  ['扇', 'Fan'],
  ['杖', 'Staff'],
  ['盾', 'Shield'],
  ['环', 'Ring'],
  ['钩', 'Hook'],
  ['爪', 'Claws'],
  ['叉', 'Fork'],
  ['钺', 'Broadaxe'],
  ['锏', 'Iron Mace'],
  ['刀', 'Saber'],
  ['剑', 'Sword'],
  ['舞', 'Dance'],
  ['头饰', 'Headgear'],
  ['耳饰', 'Earrings'],
  ['肩铠', 'Shoulder Armor'],
  ['胸铠', 'Chest Armor'],
  ['胸甲', 'Chest Armor'],
  ['腕甲', 'Wrist Armor'],
  ['腕铠', 'Wrist Armor'],
  ['腿甲', 'Leg Armor'],
  ['腿铠', 'Leg Armor'],
  ['护具', 'Armor'],
  ['披风', 'Cloak'],
  ['血药', 'HP Potion'],
  ['技能格道具', 'Skill Slot Item'],
  ['护卫技能书', 'Guard Skill Book'],
  ['强化石', 'Enhancement Stone'],
  ['强化升级道具', 'Enhancement Upgrade Item'],
  ['消耗类道具', 'Consumable Item'],
  ['抓捕道具', 'Capture Item'],
  ['传送道具', 'Teleport Item'],
  ['士气道具', 'Morale Item'],
  ['忠诚度道具', 'Loyalty Item'],
  ['历练道具', 'Training Item'],
  ['配方卷轴', 'Recipe Scroll'],
  ['礼物包', 'Gift Pack'],
  ['礼袋', 'Gift Bag'],
  ['替身娃娃', 'Substitute Doll'],
  ['徽记', 'Badge'],
  ['秘文', 'Secret Text'],
  ['隐藏', 'Hidden'],
  ['隐藏状态', 'Hidden Status'],
  ['测试', 'Test'],
  ['无用', 'Useless'],
  ['废弃', 'Obsolete'],
  ['暂废', 'Temporarily Obsolete'],
  ['全免', 'Full Immunity'],
  ['无敌', 'Invincible'],
  ['减速', 'Slow'],
  ['嘲讽', 'Taunt'],
  ['吸魂', 'Soul Drain'],
  ['人数', 'Player Count'],
  ['详细', 'Details'],
  ['杂类', 'Miscellaneous'],
  ['东海', 'Eastern Sea'],
  ['关中', 'Guanzhong'],
  ['巴蜀', 'Bashu'],
  ['川南', 'Southern Sichuan'],
  ['江南', 'Jiangnan'],
  ['河北', 'Hebei'],
  ['洛阳', 'Luoyang'],
  ['西凉', 'Xiliang'],
  ['荆襄', 'Jingxiang'],
  ['草原', 'Grassland'],
  ['水贼岛', 'Water Bandit Island'],
  ['逍遥津', 'Xiaoyao Ford'],
  ['白帝城', 'Baidi City'],
  ['虎牢关', 'Hulao Pass'],
  ['濮阳', 'Puyang'],
  ['定军山', 'Mount Dingjun'],
  ['甘露寺', 'Ganlu Temple'],
  ['北邙皇陵', 'Northern Mang Imperial Mausoleum'],
  ['楼兰', 'Loulan'],
  ['楼兰古殿', 'Loulan Ancient Palace'],
  ['楼兰沙海', 'Loulan Sand Sea'],
  ['轩辕遗迹', 'Xuanyuan Ruins'],
  ['天陨泉', 'Skyfall Spring'],
  ['凤鸣山', 'Phoenix Cry Mountain'],
  ['子午谷', 'Ziwu Valley'],
  ['七星湖', 'Seven Star Lake'],
  ['灵山密道', 'Spirit Mountain Secret Path'],
  ['留芳幽谷', 'Valley of Lasting Fragrance'],
  ['聚贤谷', 'Valley of Gathered Worthies'],
  ['殇之雪域', 'Snowfield of Sorrow'],
  ['迷花雨林', 'Enchanted Flower Rainforest'],
  ['西凉缭乱', 'Xiliang Turmoil'],
  ['西域蜃楼城', 'Western Regions Mirage City'],
  ['梦境空间', 'Dream Space'],
  ['往生之境', 'Realm of the Afterlife'],
  ['卧龙九天', 'Crouching Dragon Nine Heavens'],
  ['幻想八阵图', 'Fantasy Eight Trigrams'],
  ['官渡之战', 'Battle of Guandu'],
  ['夷陵之战', 'Battle of Yiling'],
  ['襄阳之战', 'Battle of Xiangyang'],
  ['界桥之战', 'Battle of Jieqiao'],
  ['赤壁之战', 'Battle of Chibi'],
  ['赤壁决战', 'Chibi Decisive Battle'],
  ['赤壁前哨战', 'Chibi Skirmish'],
  ['赤壁大战', 'Battle of Red Cliffs'],
  ['国战', 'National War'],
  ['战场', 'Battlefield'],
  ['奇袭战', 'Raid Battle'],
  ['挑战塔', 'Challenge Tower'],
  ['演武场', 'Martial Arena'],
  ['试炼场', 'Trial Ground'],
  ['群英会', "Heroes' Assembly"],
  ['擂台大会', 'Arena Tournament'],
  ['竞技', 'Arena'],
  ['跨服', 'Cross-Server'],
  ['跨服排行榜', 'Cross-Server Leaderboard'],
  ['吴国', 'Wu Kingdom'],
  ['蜀国', 'Shu Kingdom'],
  ['魏国', 'Wei Kingdom'],
  ['军团', 'Legion'],
  ['阵营', 'Camp'],
  ['势力', 'Faction'],
  ['结义', 'Sworn Brotherhood'],
  ['护卫', 'Guard'],
  ['个人', 'Personal'],
  ['队伍', 'Team'],
  ['国家资金', 'National Funds'],
  ['消费积分', 'Spending Points'],
  ['官职奖励', 'Official Rank Reward'],
  ['国家任务', 'National Quest'],
  ['点卯', 'Roll Call'],
  ['冥思', 'Meditation'],
  ['苦想', 'Pondering'],
  ['治疗耐力', 'Healing Stamina'],
  ['治疗评分', 'Healing Score'],
  ['防御评分', 'Defense Score'],
  ['战斗力评分', 'Combat Power Score'],
  ['战魂评分', 'War Soul Score'],
  ['暴击率降低', 'Critical Rate Reduced'],
  ['暴击计数', 'Critical Counter'],
  ['暴击', 'Critical'],
  ['命中', 'Hit Rate'],
  ['闪避', 'Evasion'],
  ['格挡', 'Block'],
  ['招架', 'Parry'],
  ['打断', 'Interrupt'],
  ['驱散', 'Dispel'],
  ['眩晕', 'Stun'],
  ['定身', 'Immobilize'],
  ['中毒', 'Poison'],
  ['燃烧', 'Burn'],
  ['流血', 'Bleed'],
  ['冻结', 'Freeze'],
  ['致盲', 'Blind'],
  ['沉默', 'Silence'],
  ['恐惧', 'Fear'],
  ['魅惑', 'Charm'],
  ['变形', 'Polymorph'],
  ['免疫', 'Immune'],
  ['抗性', 'Resistance'],
  ['无视', 'Ignore'],
  ['穿透', 'Pierce'],
  ['破防', 'Defense Break'],
  ['击退', 'Knockback'],
  ['击晕', 'Stun'],
  ['击倒', 'Knockdown'],
  ['击中', 'Hit'],
  ['击杀', 'Kill'],
  ['斩杀', 'Slay'],
  ['持续', 'Duration'],
  ['瞬发', 'Instant'],
  ['冷却', 'Cooldown'],
  ['吟唱', 'Cast Time'],
  ['引导', 'Channel'],
  ['被动', 'Passive'],
  ['主动', 'Active'],
  ['开关', 'Toggle'],
  ['切换', 'Switch'],
  ['开启', 'Enable'],
  ['关闭', 'Disable'],
  ['显示', 'Display'],
  ['消失', 'Disappear'],
  ['出现', 'Appear'],
  ['生成', 'Generate'],
  ['触发', 'Trigger'],
  ['条件', 'Condition'],
  ['目标', 'Target'],
  ['自身', 'Self'],
  ['队友', 'Ally'],
  ['敌人', 'Enemy'],
  ['全体', 'All'],
  ['单体', 'Single'],
  ['范围', 'Range'],
  ['最大', 'Max'],
  ['最小', 'Min'],
  ['增加', 'Increase'],
  ['降低', 'Decrease'],
  ['回复', 'Recover'],
  ['恢复', 'Restore'],
  ['解除', 'Remove'],
  ['附带', 'With'],
  ['造成', 'Cause'],
  ['受到', 'Take'],
  ['抵抗', 'Resist'],
  ['反弹', 'Reflect'],
  ['吸收', 'Absorb'],
  ['转移', 'Transfer'],
  ['偷取', 'Steal'],
  ['秒', 'sec'],
  ['分钟', 'min'],
  ['小时', 'hr'],
  ['升级', 'Upgrade'],
  ['任务', 'Quest'],
  ['开启', 'On'],
  ['关闭', 'Off'],
  ['强化', 'Enhance'],
  ['活动', 'Event'],
  ['摆摊', 'Stall'],
  ['交易', 'Trade'],
  ['飞行', 'Fly'],
  ['命中率', 'Accuracy'],
  ['暴击率', 'Crit Rate'],
  ['闪避率', 'Dodge Rate'],
  ['体质', 'Stamina'],
  ['声望', 'Reputation'],
  ['宝物', 'Treasure'],
  ['师德', 'Mentor Virtue'],
  ['战场', 'Battlefield'],
  ['攻击', 'Attack'],
  ['攻击力', 'Attack'],
  ['防御', 'Defense'],
  ['防御力', 'Defense'],
  ['生命', 'HP'],
  ['生命值', 'HP'],
  ['奖励', 'Reward'],
  ['称号', 'Title'],
  ['颜色', 'Color'],
  ['活动', 'Event'],
  ['活跃度', 'Activity'],
  ['排行榜', 'Leaderboard'],
  ['排行', 'Ranking'],
  ['名望', 'Renown'],
  ['国战', 'National War'],
  ['复活', 'Revive'],
  ['开启', 'On'],
  ['关闭', 'Off'],
  ['升级', 'Upgrade'],
  ['任务', 'Quest'],
  ['拾取', 'Pick Up'],
  ['拾取物品', 'Pick Up Item'],
  ['使用物品', 'Use Item'],
  ['使用物品循环', 'Use Item Loop'],
  ['攻击', 'Attack'],
  ['攻击1', 'Attack 1'],
  ['攻击2', 'Attack 2'],
  ['攻击3', 'Attack 3'],
  ['攻击4', 'Attack 4'],
  ['普通攻击', 'Normal Attack'],
  ['普通攻击1', 'Normal Attack 1'],
  ['普通攻击2', 'Normal Attack 2'],
  ['普通攻击3', 'Normal Attack 3'],
  ['普通攻击4', 'Normal Attack 4'],
  ['防御', 'Defend'],
  ['飞行', 'Fly'],
  ['冲锋', 'Charge'],
  ['受伤', 'Injured'],
  ['倒地', 'Prone'],
  ['入场', 'Enter Scene'],
  ['亲吻', 'Kiss'],
  ['亲吻循环', 'Kiss Loop'],
  ['亲吻结束', 'Kiss End'],
  ['伸懒腰', 'Stretch'],
  ['四处张望', 'Look Around'],
  ['地面死亡', 'Ground Death'],
  ['地面死亡循环', 'Ground Death Loop'],
  ['坐下', 'Sit Down'],
  ['坐下循环', 'Sit Down Loop'],
  ['坐下站起', 'Sit Down Stand Up'],
  ['复活', 'Revive'],
  ['大笑', 'Laugh'],
  ['奔跑', 'Run'],
  ['害羞', 'Shy'],
  ['张望', 'Look Out'],
  ['思考', 'Think'],
  ['战斗', 'Combat'],
  ['战斗奔跑', 'Combat Run'],
  ['战斗站立', 'Battle Stand'],
  ['战斗起跳', 'Combat Jump Start'],
  ['战斗跳跃空中循环', 'Combat Jump Air Loop'],
  ['战斗跳跃落地', 'Combat Jump Land'],
  ['战斗轻功循环', 'Combat Light Skill Loop'],
  ['打坐', 'Meditate'],
  ['打坐循环', 'Meditate Loop'],
  ['打坐站起', 'Meditate Stand Up'],
  ['抱拳', 'Fist Salute'],
  ['招手', 'Wave'],
  ['挑衅', 'Taunt'],
  ['摇头', 'Shake Head'],
  ['摔倒', 'Fall Down'],
  ['晕倒', 'Faint'],
  ['死亡', 'Death'],
  ['死亡水中循环', 'Death Water Loop'],
  ['死亡落地循环', 'Death Land Loop'],
  ['水中死亡', 'Water Death'],
  ['沮丧', 'Dejected'],
  ['游动', 'Swim'],
  ['漂浮', 'Float'],
  ['点头', 'Nod'],
  ['生气', 'Angry'],
  ['眨眼', 'Blink'],
  ['空', 'None'],
  ['空中死亡', 'Air Death'],
  ['空中死亡下落循环', 'Air Death Fall Loop'],
  ['空中死亡落地', 'Air Death Land'],
  ['站立', 'Standing'],
  ['翅膀低空下降', 'Wing Low Altitude Descend'],
  ['翅膀前进', 'Wing Forward'],
  ['翅膀悬停', 'Wing Hover'],
  ['翅膀滑翔', 'Wing Glide'],
  ['翅膀落地', 'Wing Land'],
  ['翅膀起飞', 'Wing Take Off'],
  ['翅膀高空下降', 'Wing High Altitude Descend'],
  ['耸肩膀', 'Shrug'],
  ['胜利', 'Victory'],
  ['舞蹈', 'Dance'],
  ['花招跑', 'Fancy Run'],
  ['花招跳', 'Fancy Jump'],
  ['行走', 'Walk'],
  ['被击倒', 'Knocked Down'],
  ['被击倒倒地循环', 'Knocked Down Ground Loop'],
  ['被击倒站起', 'Knocked Down Stand Up'],
  ['被击退', 'Knocked Back'],
  ['起跳', 'Jump Start'],
  ['跳跃空中循环', 'Jump Air Loop'],
  ['跳跃落地', 'Jump Land'],
  ['转动兵器', 'Rotate Weapon'],
  ['轮', 'Wheel'],
  ['轻功循环', 'Light Skill Loop'],
  ['轻功起', 'Light Skill Start'],
  ['采摘', 'Pick'],
  ['采摘植物循环', 'Pick Plant Loop'],
  ['采摘站起', 'Pick Plant Stand Up'],
  ['飞吻', 'Blow Kiss'],
  ['双人亲吻', 'Dual Kiss'],
  ['拾取', 'Pick Up'],
  ['使用物品', 'Use Item'],
  ['使用物品循环', 'Use Item Loop'],
  ['攻击', 'Attack'],
  ['攻击1', 'Attack 1'],
  ['攻击2', 'Attack 2'],
  ['攻击3', 'Attack 3'],
  ['攻击4', 'Attack 4'],
  ['普通攻击', 'Normal Attack'],
  ['普通攻击1', 'Normal Attack 1'],
  ['普通攻击2', 'Normal Attack 2'],
  ['普通攻击3', 'Normal Attack 3'],
  ['普通攻击4', 'Normal Attack 4'],
  ['防御', 'Defend'],
  ['飞行', 'Fly'],
  ['冲锋', 'Charge'],
  ['受伤', 'Injured'],
  ['倒地', 'Prone'],
  ['入场', 'Enter Scene'],
  ['亲吻', 'Kiss'],
  ['亲吻循环', 'Kiss Loop'],
  ['亲吻结束', 'Kiss End'],
  ['伸懒腰', 'Stretch'],
  ['四处张望', 'Look Around'],
  ['地面死亡', 'Ground Death'],
  ['地面死亡循环', 'Ground Death Loop'],
  ['坐下', 'Sit Down'],
  ['坐下循环', 'Sit Down Loop'],
  ['坐下站起', 'Sit Down Stand Up'],
  ['复活', 'Revive'],
  ['大笑', 'Laugh'],
  ['奔跑', 'Run'],
  ['害羞', 'Shy'],
  ['张望', 'Look Out'],
  ['思考', 'Think'],
  ['战斗', 'Combat'],
  ['战斗奔跑', 'Combat Run'],
  ['战斗站立', 'Battle Stand'],
  ['战斗起跳', 'Combat Jump Start'],
  ['战斗跳跃空中循环', 'Combat Jump Air Loop'],
  ['战斗跳跃落地', 'Combat Jump Land'],
  ['战斗轻功循环', 'Combat Light Skill Loop'],
  ['打坐', 'Meditate'],
  ['打坐循环', 'Meditate Loop'],
  ['打坐站起', 'Meditate Stand Up'],
  ['抱拳', 'Fist Salute'],
  ['招手', 'Wave'],
  ['挑衅', 'Taunt'],
  ['摇头', 'Shake Head'],
  ['摔倒', 'Fall Down'],
  ['晕倒', 'Faint'],
  ['死亡', 'Death'],
  ['死亡水中循环', 'Death Water Loop'],
  ['死亡落地循环', 'Death Land Loop'],
  ['水中死亡', 'Water Death'],
  ['沮丧', 'Dejected'],
  ['游动', 'Swim'],
  ['漂浮', 'Float'],
  ['点头', 'Nod'],
  ['生气', 'Angry'],
  ['眨眼', 'Blink'],
  ['空', 'None'],
  ['空中死亡', 'Air Death'],
  ['空中死亡下落循环', 'Air Death Fall Loop'],
  ['空中死亡落地', 'Air Death Land'],
  ['站立', 'Standing'],
  ['翅膀低空下降', 'Wing Low Altitude Descend'],
  ['翅膀前进', 'Wing Forward'],
  ['翅膀悬停', 'Wing Hover'],
  ['翅膀滑翔', 'Wing Glide'],
  ['翅膀落地', 'Wing Land'],
  ['翅膀起飞', 'Wing Take Off'],
  ['翅膀高空下降', 'Wing High Altitude Descend'],
  ['耸肩膀', 'Shrug'],
  ['胜利', 'Victory'],
  ['舞蹈', 'Dance'],
  ['花招跑', 'Fancy Run'],
  ['花招跳', 'Fancy Jump'],
  ['行走', 'Walk'],
  ['被击倒', 'Knocked Down'],
  ['被击倒倒地循环', 'Knocked Down Ground Loop'],
  ['被击倒站起', 'Knocked Down Stand Up'],
  ['被击退', 'Knocked Back'],
  ['起跳', 'Jump Start'],
  ['跳跃空中循环', 'Jump Air Loop'],
  ['跳跃落地', 'Jump Land'],
  ['转动兵器', 'Rotate Weapon'],
  ['轮', 'Wheel'],
  ['轻功循环', 'Light Skill Loop'],
  ['轻功起', 'Light Skill Start'],
  ['采摘', 'Pick'],
  ['采摘植物循环', 'Pick Plant Loop'],
  ['采摘站起', 'Pick Plant Stand Up'],
  ['飞吻', 'Blow Kiss'],
  ['双人亲吻', 'Dual Kiss'],
  ['拾取', 'Pick Up'],
  ['使用物品', 'Use Item'],
  ['使用物品循环', 'Use Item Loop'],
  ['攻击', 'Attack'],
  ['攻击1', 'Attack 1'],
  ['攻击2', 'Attack 2'],
  ['攻击3', 'Attack 3'],
  ['攻击4', 'Attack 4'],
  ['普通攻击', 'Normal Attack'],
  ['普通攻击1', 'Normal Attack 1'],
  ['普通攻击2', 'Normal Attack 2'],
  ['普通攻击3', 'Normal Attack 3'],
  ['普通攻击4', 'Normal Attack 4'],
  ['防御', 'Defend'],
  ['飞行', 'Fly'],
  ['冲锋', 'Charge'],
  ['受伤', 'Injured'],
  ['倒地', 'Prone'],
  ['入场', 'Enter Scene'],
  ['亲吻', 'Kiss'],
  ['亲吻循环', 'Kiss Loop'],
  ['亲吻结束', 'Kiss End'],
  ['伸懒腰', 'Stretch'],
  ['四处张望', 'Look Around'],
  ['地面死亡', 'Ground Death'],
  ['地面死亡循环', 'Ground Death Loop'],
  ['坐下', 'Sit Down'],
  ['坐下循环', 'Sit Down Loop'],
  ['坐下站起', 'Sit Down Stand Up'],
  ['复活', 'Revive'],
  ['大笑', 'Laugh'],
  ['奔跑', 'Run'],
  ['害羞', 'Shy'],
  ['张望', 'Look Out'],
  ['思考', 'Think'],
  ['战斗', 'Combat'],
  ['战斗奔跑', 'Combat Run'],
  ['战斗站立', 'Battle Stand'],
  ['战斗起跳', 'Combat Jump Start'],
  ['战斗跳跃空中循环', 'Combat Jump Air Loop'],
  ['战斗跳跃落地', 'Combat Jump Land'],
  ['战斗轻功循环', 'Combat Light Skill Loop'],
  ['打坐', 'Meditate'],
  ['打坐循环', 'Meditate Loop'],
  ['打坐站起', 'Meditate Stand Up'],
  ['抱拳', 'Fist Salute'],
  ['招手', 'Wave'],
  ['挑衅', 'Taunt'],
  ['摇头', 'Shake Head'],
  ['摔倒', 'Fall Down'],
  ['晕倒', 'Faint'],
  ['死亡', 'Death'],
  ['死亡水中循环', 'Death Water Loop'],
  ['死亡落地循环', 'Death Land Loop'],
  ['水中死亡', 'Water Death'],
  ['沮丧', 'Dejected'],
  ['游动', 'Swim'],
  ['漂浮', 'Float'],
  ['点头', 'Nod'],
  ['生气', 'Angry'],
  ['眨眼', 'Blink'],
  ['空', 'None'],
  ['空中死亡', 'Air Death'],
  ['空中死亡下落循环', 'Air Death Fall Loop'],
  ['空中死亡落地', 'Air Death Land'],
  ['站立', 'Standing'],
  ['翅膀低空下降', 'Wing Low Altitude Descend'],
  ['翅膀前进', 'Wing Forward'],
  ['翅膀悬停', 'Wing Hover'],
  ['翅膀滑翔', 'Wing Glide'],
  ['翅膀落地', 'Wing Land'],
  ['翅膀起飞', 'Wing Take Off'],
  ['翅膀高空下降', 'Wing High Altitude Descend'],
  ['耸肩膀', 'Shrug'],
  ['胜利', 'Victory'],
  ['舞蹈', 'Dance'],
  ['花招跑', 'Fancy Run'],
  ['花招跳', 'Fancy Jump'],
  ['行走', 'Walk'],
  ['被击倒', 'Knocked Down'],
  ['被击倒倒地循环', 'Knocked Down Ground Loop'],
  ['被击倒站起', 'Knocked Down Stand Up'],
  ['被击退', 'Knocked Back'],
  ['起跳', 'Jump Start'],
  ['跳跃空中循环', 'Jump Air Loop'],
  ['跳跃落地', 'Jump Land'],
  ['转动兵器', 'Rotate Weapon'],
  ['轮', 'Wheel'],
  ['轻功循环', 'Light Skill Loop'],
  ['轻功起', 'Light Skill Start'],
  ['采摘', 'Pick'],
  ['采摘植物循环', 'Pick Plant Loop'],
  ['采摘站起', 'Pick Plant Stand Up'],
  ['飞吻', 'Blow Kiss'],
  ['双人亲吻', 'Dual Kiss'],
]);

// Pattern-based translations for repetitive entries
function applyPatterns(src) {
  let m;
  // 军团基地地图N
  if ((m = src.match(/^军团基地地图(\d+)$/))) return `Legion Base Map ${m[1]}`;
  // 军团基地N
  if ((m = src.match(/^军团基地(\d)$/))) return `Legion Base ${m[1]}`;
  // 国战N
  if ((m = src.match(/^国战(\d+)$/))) return `National War ${m[1]}`;
  // 奇袭战N
  if ((m = src.match(/^奇袭战(\d+)$/))) return `Raid Battle ${m[1]}`;
  // 战场1-N[X]
  if ((m = src.match(/^战场1-(\d+)([A-J])$/))) return `Battlefield 1-${m[1]}${m[2]}`;
  // 竞技场NNN[place]
  if ((m = src.match(/^竞技场(\d{3})(寝陵|红枫谷|五丁壮士谷|祝融殿|五丁壮士冢)$/))) {
    const placeMap = {'寝陵': 'Mausoleum', '红枫谷': 'Red Maple Valley', '五丁壮士谷': 'Five Braves Valley', '祝融殿': 'Zhurong Hall', '五丁壮士冢': 'Five Braves Tomb'};
    return `Arena ${m[1]} ${placeMap[m[2]]}`;
  }
  // 定军山N
  if ((m = src.match(/^定军山(\d+)$/))) return `Mount Dingjun ${m[1]}`;
  // 北邙皇陵N
  if ((m = src.match(/^北邙皇陵(\d+)$/))) return `Northern Mang Imperial Mausoleum ${m[1]}`;
  // 甘露寺N
  if ((m = src.match(/^甘露寺(\d+)$/))) return `Ganlu Temple ${m[1]}`;
  // 华容道N
  if ((m = src.match(/^华容道(\d+)$/))) return `Huarong Road ${m[1]}`;
  // 华容道一N
  if ((m = src.match(/^华容道一(\d+)$/))) return `Huarong Road One ${m[1]}`;
  // 华容道二N
  if ((m = src.match(/^华容道二(\d+)$/))) return `Huarong Road Two ${m[1]}`;
  // 合肥之战N
  if ((m = src.match(/^合肥之战(\d+)$/))) return `Battle of Hefei ${m[1]}`;
  // 蒋干盗书N
  if ((m = src.match(/^蒋干盗书(\d+)$/))) return `Jiang Gan Steals the Letter ${m[1]}`;
  // 荆襄逃亡N
  if ((m = src.match(/^荆襄逃亡(\d+)$/))) return `Jingxiang Escape ${m[1]}`;
  // 南中争霸战N
  if ((m = src.match(/^南中争霸战(\d+)$/))) return `Battle for Nanzhong ${m[1]}`;
  // 单骑救主N
  if ((m = src.match(/^单骑救主(\d+)$/))) return `Lone Rider Rescues His Lord ${m[1]}`;
  // 往生之境N
  if ((m = src.match(/^往生之境(\d+)$/))) return `Realm of the Afterlife ${m[1]}`;
  // 炼魂+N状态
  if ((m = src.match(/^炼魂\+(\d+)状态$/))) return `Soul Refining +${m[1]} Status`;
  // 无双轩辕遗迹N
  if ((m = src.match(/^无双轩辕遗迹(\d+)$/))) return `Peerless Xuanyuan Ruins ${m[1]}`;
  // 无双项王魔域N
  if ((m = src.match(/^无双项王魔域(\d+)$/))) return `Peerless Demon Realm of the Hegemon King ${m[1]}`;
  // 虎牢关群英会英雄级N
  if ((m = src.match(/^虎牢关群英会英雄级(\d+)$/))) return `Hulao Pass Heroes Assembly Heroic ${m[1]}`;
  // 英雄志NN[许褚|甘宁]传N
  if ((m = src.match(/^英雄志(\d{2})(许褚|甘宁)传(\d)$/))) {
    const nameMap = {'许褚': 'Xu Chu', '甘宁': 'Gan Ning'};
    return `Heroic Tales ${m[1]}: Tale of ${nameMap[m[2]]} ${m[3]}`;
  }
  // 幻想八阵图休门N
  if ((m = src.match(/^幻想八阵图休门(\d)$/))) return `Fantasy Eight Trigrams Rest Gate ${m[1]}`;
  // 幻想八阵图开门N
  if ((m = src.match(/^幻想八阵图开门(\d)$/))) return `Fantasy Eight Trigrams Open Gate ${m[1]}`;
  // 幻想八阵图开门（首领）N
  if ((m = src.match(/^幻想八阵图开门（首领）(\d)$/))) return `Fantasy Eight Trigrams Open Gate (Boss) ${m[1]}`;
  // 英雄志·黄忠传
  if (src === '英雄志·黄忠传') return 'Heroic Tales: Tale of Huang Zhong';
  // 跨服竞技•跨服赛N线
  if ((m = src.match(/^跨服竞技•跨服赛(\d+)线$/))) return `Cross-Server Arena · Cross-Server Tournament Line ${m[1]}`;
  // 跨服竞技•选拔赛N线
  if ((m = src.match(/^跨服竞技•选拔赛(\d+)线$/))) return `Cross-Server Arena · Qualifier Line ${m[1]}`;
  // 第N圈X分之Y
  if ((m = src.match(/^第(\d+)圈(\d+)分之(\d+)\s*$/))) {
    const trailing = src.endsWith(' ') ? ' ' : '';
    return `Lap ${m[1]}, ${m[3]}/${m[2]}${trailing}`;
  }
  // 第N圈完成
  if ((m = src.match(/^第(\d+)圈完成$/))) return `Lap ${m[1]} Complete`;
  return null;
}

// Read input
const inputContent = fs.readFileSync(inPath, 'utf8');
const inputLines = inputContent.split(/\r?\n/).filter(l => l.trim());
const records = inputLines.map(line => JSON.parse(line));

// Translate each record
const outputRecords = records.map(rec => {
  const src = rec.source;
  let eng;
  
  if (specific.has(src)) {
    eng = specific.get(src);
  } else if (priorMap.has(src)) {
    eng = priorMap.get(src);
  } else if (glossaryMap.has(src)) {
    eng = glossaryMap.get(src);
  } else if (common.has(src)) {
    eng = common.get(src);
  } else {
    eng = applyPatterns(src);
    if (!eng) {
      // Try partial match with common map
      let partial = src;
      for (const [k, v] of common) {
        if (partial.includes(k)) {
          partial = partial.split(k).join(v);
        }
      }
      eng = partial;
    }
  }
  
  // Preserve <CRLF>, <LF>, <CR> token counts
  const srcCRLF = (src.match(/<CRLF>/g) || []).length;
  const engCRLF = (eng.match(/<CRLF>/g) || []).length;
  if (srcCRLF > engCRLF) {
    eng = eng + '<CRLF>'.repeat(srcCRLF - engCRLF);
  } else if (engCRLF > srcCRLF) {
    while ((eng.match(/<CRLF>/g) || []).length > srcCRLF) {
      eng = eng.replace(/<CRLF>/, '');
    }
  }
  
  return { id: rec.id, english: eng };
});

// Write output
const outputLines = outputRecords.map(r => JSON.stringify(r));
fs.writeFileSync(outPath, outputLines.join('\n') + '\n', 'utf8');

console.log(`Translated ${outputRecords.length} records to ${outPath}`);

// Validation
const outputContent = fs.readFileSync(outPath, 'utf8');
const outputLinesCheck = outputContent.split(/\r?\n/).filter(l => l.trim());
console.log(`Output lines: ${outputLinesCheck.length}`);
console.log(`Input lines: ${inputLines.length}`);

// Check for Chinese characters remaining
let chineseCount = 0;
for (const line of outputLinesCheck) {
  try {
    const obj = JSON.parse(line);
    if (/[\u4e00-\u9fff]/.test(obj.english)) {
      chineseCount++;
      if (chineseCount <= 5) {
        console.log(`Chinese remaining in id ${obj.id}: ${obj.english.substring(0, 80)}`);
      }
    }
  } catch (e) {}
}
console.log(`Records with Chinese remaining: ${chineseCount}`);
